// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// AccountSwitchType is the OCSF Account Switch Type ID enum. The
// normalized identifier of the account switch method.
//
// OCSF attribute: account_switch_type_id.
type AccountSwitchType int

const (
	// AccountSwitchTypeUnknown: The account switch type is unknown.
	AccountSwitchTypeUnknown AccountSwitchType = 0
	// AccountSwitchTypeSubstituteUser: A utility like sudo, su, or
	// equivalent was used to perform actions in the context of another
	// user.
	AccountSwitchTypeSubstituteUser AccountSwitchType = 1
	// AccountSwitchTypeImpersonate: An API like
	// ImpersonateLoggedOnUser() or equivalent was used to perform
	// actions in the context of another user.
	AccountSwitchTypeImpersonate AccountSwitchType = 2
	// AccountSwitchTypeOther: The account switch type is not mapped.
	// See the account_switch_type attribute, which contains a data
	// source specific value.
	AccountSwitchTypeOther AccountSwitchType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v AccountSwitchType) String() string {
	switch v {
	case AccountSwitchTypeUnknown:
		return "Unknown"
	case AccountSwitchTypeSubstituteUser:
		return "Substitute User"
	case AccountSwitchTypeImpersonate:
		return "Impersonate"
	case AccountSwitchTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
