// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Action is the OCSF Action ID enum. The normalized action taken by a
// control or other policy-based system leading to an outcome or
// disposition.
//
// OCSF attribute: action_id.
type Action int

const (
	// ActionUnknown: The action was unknown.
	ActionUnknown Action = 0
	// ActionAllowed: The activity was allowed.
	ActionAllowed Action = 1
	// ActionDenied: The attempted activity was denied.
	ActionDenied Action = 2
	// ActionOther: The action was not mapped. See the action
	// attribute, which contains a data source specific value.
	ActionOther Action = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Action) String() string {
	switch v {
	case ActionUnknown:
		return "Unknown"
	case ActionAllowed:
		return "Allowed"
	case ActionDenied:
		return "Denied"
	case ActionOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
