// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Algorithm is the OCSF Algorithm ID enum. The normalized identifier of
// the algorithm. See specific usage.
//
// OCSF attribute: algorithm_id.
type Algorithm int

const (
	// AlgorithmUnknown: The algorithm is unknown.
	AlgorithmUnknown Algorithm = 0
	// AlgorithmOther: The algorithm is not mapped. See the algorithm
	// attribute, which contains a data source specific value.
	AlgorithmOther Algorithm = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Algorithm) String() string {
	switch v {
	case AlgorithmUnknown:
		return "Unknown"
	case AlgorithmOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
