// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// AuthType is the OCSF Authentication Type ID enum. The normalized
// identifier of the agreed upon authentication type. See specific usage.
//
// OCSF attribute: auth_type_id.
type AuthType int

const (
	// AuthTypeUnknown: The authentication type is unknown.
	AuthTypeUnknown AuthType = 0
	// AuthTypeOther: The authentication type is not mapped. See the
	// auth_type attribute, which contains a data source specific
	// value.
	AuthTypeOther AuthType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v AuthType) String() string {
	switch v {
	case AuthTypeUnknown:
		return "Unknown"
	case AuthTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
