// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Boundary is the OCSF Boundary ID enum. The normalized identifier of
// the boundary of the connection. For cloud connections, this translates
// to the traffic-boundary (same VPC, through IGW, etc.). For traditional
// networks, this is described as Local, Internal, or External.
//
// OCSF attribute: boundary_id.
type Boundary int

const (
	// BoundaryUnknown: The connection boundary is unknown.
	BoundaryUnknown Boundary = 0
	// BoundaryLocalhost: Local network traffic on the same endpoint.
	BoundaryLocalhost Boundary = 1
	// BoundaryInternal: Internal network traffic between two endpoints
	// inside network.
	BoundaryInternal Boundary = 2
	// BoundaryExternal: External network traffic between two endpoints
	// on the Internet or outside the network.
	BoundaryExternal Boundary = 3
	// BoundarySameVPC: Through another resource in the same VPC
	BoundarySameVPC Boundary = 4
	// BoundaryInternetVPCGateway: Through an Internet gateway or a
	// gateway VPC endpoint
	BoundaryInternetVPCGateway Boundary = 5
	// BoundaryVirtualPrivateGateway: Through a virtual private gateway
	BoundaryVirtualPrivateGateway Boundary = 6
	// BoundaryIntraRegionVPC: Through an intra-region VPC peering
	// connection
	BoundaryIntraRegionVPC Boundary = 7
	// BoundaryInterRegionVPC: Through an inter-region VPC peering
	// connection
	BoundaryInterRegionVPC Boundary = 8
	// BoundaryLocalGateway: Through a local gateway
	BoundaryLocalGateway Boundary = 9
	// BoundaryGatewayVPC: Through a gateway VPC endpoint (Nitro-based
	// instances only)
	BoundaryGatewayVPC Boundary = 10
	// BoundaryInternetGateway: Through an Internet gateway
	// (Nitro-based instances only)
	BoundaryInternetGateway Boundary = 11
	// BoundaryOther: The boundary is not mapped. See the boundary
	// attribute, which contains a data source specific value.
	BoundaryOther Boundary = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Boundary) String() string {
	switch v {
	case BoundaryUnknown:
		return "Unknown"
	case BoundaryLocalhost:
		return "Localhost"
	case BoundaryInternal:
		return "Internal"
	case BoundaryExternal:
		return "External"
	case BoundarySameVPC:
		return "Same VPC"
	case BoundaryInternetVPCGateway:
		return "Internet/VPC Gateway"
	case BoundaryVirtualPrivateGateway:
		return "Virtual Private Gateway"
	case BoundaryIntraRegionVPC:
		return "Intra-region VPC"
	case BoundaryInterRegionVPC:
		return "Inter-region VPC"
	case BoundaryLocalGateway:
		return "Local Gateway"
	case BoundaryGatewayVPC:
		return "Gateway VPC"
	case BoundaryInternetGateway:
		return "Internet Gateway"
	case BoundaryOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
