// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Confidence is the OCSF Confidence ID enum. The normalized confidence
// refers to the accuracy of the rule that created the finding. A rule
// with a low confidence means that the finding scope is wide and may
// create finding reports that may not be malicious in nature.
//
// OCSF attribute: confidence_id.
type Confidence int

const (
	// ConfidenceUnknown: The normalized confidence is unknown.
	ConfidenceUnknown Confidence = 0
	ConfidenceLow     Confidence = 1
	ConfidenceMedium  Confidence = 2
	ConfidenceHigh    Confidence = 3
	// ConfidenceOther: The confidence is not mapped to the defined
	// enum values. See the confidence attribute, which contains a data
	// source specific value.
	ConfidenceOther Confidence = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Confidence) String() string {
	switch v {
	case ConfidenceUnknown:
		return "Unknown"
	case ConfidenceLow:
		return "Low"
	case ConfidenceMedium:
		return "Medium"
	case ConfidenceHigh:
		return "High"
	case ConfidenceOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
