// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// DataLifecycleState is the OCSF Data Lifecycle State ID enum. The stage
// or state that the data was in when it was assessed or scanned by a
// data security tool.
//
// OCSF attribute: data_lifecycle_state_id.
type DataLifecycleState int

const (
	// DataLifecycleStateUnknown: The data lifecycle state is unknown.
	DataLifecycleStateUnknown DataLifecycleState = 0
	// DataLifecycleStateDataAtRest: The data was stored on physical or
	// logical media and was not actively moving through the network
	// nor was being processed. E.g., data stored in a database, PDF
	// files in a file share, or EHR records in object storage.
	DataLifecycleStateDataAtRest DataLifecycleState = 1
	// DataLifecycleStateDataInTransit: The data was actively moving
	// through the network or from one physical or logical location to
	// another. E.g., emails being send, data replication or Change
	// Data Capture (CDC) streams, or sensitive data processed on an
	// API.
	DataLifecycleStateDataInTransit DataLifecycleState = 2
	// DataLifecycleStateDataInUse: The data was being processed,
	// accessed, or read by a system, making it active in memory or
	// CPU. E.g., sensitive data in a Business Intelligence tool, ePHI
	// being processed in an EHR application or a user viewing data
	// stored in a spreadsheet or PDF.
	DataLifecycleStateDataInUse DataLifecycleState = 3
	// DataLifecycleStateOther: The data lifecycle state is not mapped.
	// See the data_lifecycle_state attribute, which contains a data
	// source specific value.
	DataLifecycleStateOther DataLifecycleState = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v DataLifecycleState) String() string {
	switch v {
	case DataLifecycleStateUnknown:
		return "Unknown"
	case DataLifecycleStateDataAtRest:
		return "Data at-Rest"
	case DataLifecycleStateDataInTransit:
		return "Data in-Transit"
	case DataLifecycleStateDataInUse:
		return "Data in-Use"
	case DataLifecycleStateOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
