// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Encoding is the OCSF Encoding ID enum. The normalized identifier of
// the encoding method. See specific usage.
//
// OCSF attribute: encoding_id.
type Encoding int

const (
	// EncodingUnknown: The encoding method is unknown.
	EncodingUnknown Encoding = 0
	// EncodingOther: The encoding method is not mapped. See the
	// encoding attribute, which contains a data source specific value.
	EncodingOther Encoding = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Encoding) String() string {
	switch v {
	case EncodingUnknown:
		return "Unknown"
	case EncodingOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
