// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// FactorType is the OCSF Factor Type ID enum. The normalized identifier
// for the authentication factor.
//
// OCSF attribute: factor_type_id.
type FactorType int

const (
	FactorTypeUnknown FactorType = 0
	// FactorTypeSMS: User receives and inputs a code sent to their
	// mobile device via SMS text message.
	FactorTypeSMS FactorType = 1
	// FactorTypeSecurityQuestion: The user responds to a security
	// question as part of a question-based authentication factor
	FactorTypeSecurityQuestion FactorType = 2
	// FactorTypePhoneCall: System calls the user's registered phone
	// number and requires the user to answer and provide a response.
	FactorTypePhoneCall FactorType = 3
	// FactorTypeBiometric: Devices that verify identity-based on
	// user's physical identifiers, such as fingerprint scanners or
	// retina scanners.
	FactorTypeBiometric FactorType = 4
	// FactorTypePushNotification: Push notification is sent to user's
	// registered device and requires the user to acknowledge.
	FactorTypePushNotification FactorType = 5
	// FactorTypeHardwareToken: Physical device that generates a code
	// to be used for authentication.
	FactorTypeHardwareToken FactorType = 6
	// FactorTypeOTP: Application generates a one-time password (OTP)
	// for use in authentication.
	FactorTypeOTP FactorType = 7
	// FactorTypeEmail: A code or link is sent to a user's registered
	// email address.
	FactorTypeEmail FactorType = 8
	// FactorTypeU2F: Typically involves a hardware token, which the
	// user physically interacts with to authenticate.
	FactorTypeU2F FactorType = 9
	// FactorTypeWebAuthn: Web-based API that enables users to register
	// devices as authentication factors.
	FactorTypeWebAuthn FactorType = 10
	// FactorTypePassword: The user enters a password that they have
	// previously established.
	FactorTypePassword FactorType = 11
	FactorTypeOther    FactorType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v FactorType) String() string {
	switch v {
	case FactorTypeUnknown:
		return "Unknown"
	case FactorTypeSMS:
		return "SMS"
	case FactorTypeSecurityQuestion:
		return "Security Question"
	case FactorTypePhoneCall:
		return "Phone Call"
	case FactorTypeBiometric:
		return "Biometric"
	case FactorTypePushNotification:
		return "Push Notification"
	case FactorTypeHardwareToken:
		return "Hardware Token"
	case FactorTypeOTP:
		return "OTP"
	case FactorTypeEmail:
		return "Email"
	case FactorTypeU2F:
		return "U2F"
	case FactorTypeWebAuthn:
		return "WebAuthn"
	case FactorTypePassword:
		return "Password"
	case FactorTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
