// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// FlagIds is the OCSF Communication Flag IDs enum. The list of
// normalized identifiers of the communication flag IDs. See specific
// usage.
//
// OCSF attribute: flag_ids.
type FlagIds int

const (
	// FlagIdsUnknown: The flag is unknown.
	FlagIdsUnknown FlagIds = 0
	// FlagIdsOther: The flag is not mapped. See the flags attribute,
	// which contains a data source specific value.
	FlagIdsOther FlagIds = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v FlagIds) String() string {
	switch v {
	case FlagIdsUnknown:
		return "Unknown"
	case FlagIdsOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
