// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// InjectionType is the OCSF Injection Type ID enum. The normalized
// identifier of the process injection method.
//
// OCSF attribute: injection_type_id.
type InjectionType int

const (
	// InjectionTypeUnknown: The injection type is unknown.
	InjectionTypeUnknown      InjectionType = 0
	InjectionTypeRemoteThread InjectionType = 1
	InjectionTypeLoadLibrary  InjectionType = 2
	InjectionTypeQueueAPC     InjectionType = 3
	// InjectionTypeOther: The injection type is not mapped. See the
	// injection_type attribute, which contains a data source specific
	// value.
	InjectionTypeOther InjectionType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v InjectionType) String() string {
	switch v {
	case InjectionTypeUnknown:
		return "Unknown"
	case InjectionTypeRemoteThread:
		return "Remote Thread"
	case InjectionTypeLoadLibrary:
		return "Load Library"
	case InjectionTypeQueueAPC:
		return "Queue APC"
	case InjectionTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
