// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// InstallState is the OCSF Install State ID enum. The normalized state
// of the install.
//
// OCSF attribute: install_state_id.
type InstallState int

const (
	// InstallStateUnknown: The normalized install state is unknown.
	InstallStateUnknown InstallState = 0
	// InstallStateInstalled: The item is installed.
	InstallStateInstalled InstallState = 1
	// InstallStateNotInstalled: The item is not installed.
	InstallStateNotInstalled InstallState = 2
	// InstallStateInstalledPendingReboot: The item is installed
	// pending reboot operation.
	InstallStateInstalledPendingReboot InstallState = 3
	// InstallStateOther: The install state is not mapped. See the
	// install_state attribute, which contains a data source specific
	// value.
	InstallStateOther InstallState = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v InstallState) String() string {
	switch v {
	case InstallStateUnknown:
		return "Unknown"
	case InstallStateInstalled:
		return "Installed"
	case InstallStateNotInstalled:
		return "Not Installed"
	case InstallStateInstalledPendingReboot:
		return "Installed Pending Reboot"
	case InstallStateOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
