// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// LaunchType is the OCSF Launch Type ID enum. The normalized identifier
// for the specific type of Launch activity.
//
// OCSF attribute: launch_type_id.
type LaunchType int

const (
	// LaunchTypeUnknown: The launch type is unknown or not specified.
	LaunchTypeUnknown LaunchType = 0
	// LaunchTypeSpawn: Denotes that the Launch event represents atomic
	// creation of a new process on Windows. This launch type ID may
	// also be used to represent both steps of Unix process creation in
	// a single Launch event.
	LaunchTypeSpawn LaunchType = 1
	// LaunchTypeFork: Denotes that the Launch event represents the
	// "fork" step of Unix process creation, where a process creates a
	// clone of itself in a parent-child relationship. WSL1 pico
	// processes on Windows also use the 2-step Unix model.
	LaunchTypeFork LaunchType = 2
	// LaunchTypeExec: Denotes that the Launch event represents the
	// "exec" step of Unix process creation, where a process replaces
	// its executable image, command line, and environment. WSL1 pico
	// processes on Windows also use the 2-step Unix model.
	LaunchTypeExec LaunchType = 3
	// LaunchTypeOther: The launch type is not mapped. See the
	// launch_type attribute, which contains a data source specific
	// value.
	LaunchTypeOther LaunchType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v LaunchType) String() string {
	switch v {
	case LaunchTypeUnknown:
		return "Unknown"
	case LaunchTypeSpawn:
		return "Spawn"
	case LaunchTypeFork:
		return "Fork"
	case LaunchTypeExec:
		return "Exec"
	case LaunchTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
