// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// LogType is the OCSF Log Type ID enum. The normalized log type
// identifier.
//
// OCSF attribute: log_type_id.
type LogType int

const (
	// LogTypeUnknown: The log type is unknown.
	LogTypeUnknown LogType = 0
	// LogTypeOS: The log type is an Operating System log.
	LogTypeOS LogType = 1
	// LogTypeApplication: The log type is an Application log.
	LogTypeApplication LogType = 2
	// LogTypeOther: The log type is not mapped. See the log_type
	// attribute, which contains a data source specific value.
	LogTypeOther LogType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v LogType) String() string {
	switch v {
	case LogTypeUnknown:
		return "Unknown"
	case LogTypeOS:
		return "OS"
	case LogTypeApplication:
		return "Application"
	case LogTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
