// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// LogonType is the OCSF Logon Type ID enum. The normalized logon type
// identifier.
//
// OCSF attribute: logon_type_id.
type LogonType int

const (
	// LogonTypeUnknown: The logon type is unknown.
	LogonTypeUnknown LogonType = 0
	// LogonTypeSystem: Used only by the System account, for example at
	// system startup.
	LogonTypeSystem LogonType = 1
	// LogonTypeInteractive: A local logon to device console.
	LogonTypeInteractive LogonType = 2
	// LogonTypeNetwork: A user or device logged onto this device from
	// the network.
	LogonTypeNetwork LogonType = 3
	// LogonTypeBatch: A batch server logon, where processes may be
	// executing on behalf of a user without their direct intervention.
	LogonTypeBatch LogonType = 4
	// LogonTypeOSService: A logon by a service or daemon that was
	// started by the OS.
	LogonTypeOSService LogonType = 5
	// LogonTypeUnlock: A user unlocked the device.
	LogonTypeUnlock LogonType = 7
	// LogonTypeNetworkCleartext: A user logged on to this device from
	// the network. The user's password in the authentication package
	// was not hashed.
	LogonTypeNetworkCleartext LogonType = 8
	// LogonTypeNewCredentials: A caller cloned its current token and
	// specified new credentials for outbound connections. The new
	// logon session has the same local identity, but uses different
	// credentials for other network connections.
	LogonTypeNewCredentials LogonType = 9
	// LogonTypeRemoteInteractive: A remote logon using Terminal
	// Services or remote desktop application.
	LogonTypeRemoteInteractive LogonType = 10
	// LogonTypeCachedInteractive: A user logged on to this device with
	// network credentials that were stored locally on the device and
	// the domain controller was not contacted to verify the
	// credentials.
	LogonTypeCachedInteractive LogonType = 11
	// LogonTypeCachedRemoteInteractive: Same as Remote Interactive.
	// This is used for internal auditing.
	LogonTypeCachedRemoteInteractive LogonType = 12
	// LogonTypeCachedUnlock: Workstation logon.
	LogonTypeCachedUnlock LogonType = 13
	// LogonTypeOther: The logon type is not mapped. See the logon_type
	// attribute, which contains a data source specific value.
	LogonTypeOther LogonType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v LogonType) String() string {
	switch v {
	case LogonTypeUnknown:
		return "Unknown"
	case LogonTypeSystem:
		return "System"
	case LogonTypeInteractive:
		return "Interactive"
	case LogonTypeNetwork:
		return "Network"
	case LogonTypeBatch:
		return "Batch"
	case LogonTypeOSService:
		return "OS Service"
	case LogonTypeUnlock:
		return "Unlock"
	case LogonTypeNetworkCleartext:
		return "Network Cleartext"
	case LogonTypeNewCredentials:
		return "New Credentials"
	case LogonTypeRemoteInteractive:
		return "Remote Interactive"
	case LogonTypeCachedInteractive:
		return "Cached Interactive"
	case LogonTypeCachedRemoteInteractive:
		return "Cached Remote Interactive"
	case LogonTypeCachedUnlock:
		return "Cached Unlock"
	case LogonTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
