// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Opcode is the OCSF DNS Opcode ID enum. The DNS opcode ID specifies the
// normalized query message type as defined in RFC-5395.
//
// OCSF attribute: opcode_id.
type Opcode int

const (
	// OpcodeQuery: Standard query
	OpcodeQuery Opcode = 0
	// OpcodeInverseQuery: Inverse query, obsolete
	OpcodeInverseQuery Opcode = 1
	// OpcodeStatus: Server status request
	OpcodeStatus Opcode = 2
	// OpcodeReserved: Reserved, not used
	OpcodeReserved Opcode = 3
	// OpcodeNotify: Zone change notification
	OpcodeNotify Opcode = 4
	// OpcodeUpdate: Dynamic DNS update
	OpcodeUpdate Opcode = 5
	// OpcodeDSOMessage: DNS Stateful Operations (DSO)
	OpcodeDSOMessage Opcode = 6
	// OpcodeOther: The DNS Opcode is not defined by the RFC. See the
	// opcode attribute, which contains a data source specific value.
	OpcodeOther Opcode = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Opcode) String() string {
	switch v {
	case OpcodeQuery:
		return "Query"
	case OpcodeInverseQuery:
		return "Inverse Query"
	case OpcodeStatus:
		return "Status"
	case OpcodeReserved:
		return "Reserved"
	case OpcodeNotify:
		return "Notify"
	case OpcodeUpdate:
		return "Update"
	case OpcodeDSOMessage:
		return "DSO Message"
	case OpcodeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
