// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// QueryType is the OCSF Query Type ID enum. The normalized type of
// system query performed against a device or system component.
//
// OCSF attribute: query_type_id.
type QueryType int

const (
	// QueryTypeUnknown: The query type was unknown or not specified.
	QueryTypeUnknown QueryType = 0
	// QueryTypeKernel: A query about kernel resources including system
	// calls, shared mutex, or other kernel components.
	QueryTypeKernel QueryType = 1
	// QueryTypeFile: A query about file attributes, metadata, content,
	// hash values, or properties.
	QueryTypeFile QueryType = 2
	// QueryTypeFolder: A query about folder attributes, metadata,
	// content, or structure.
	QueryTypeFolder QueryType = 3
	// QueryTypeAdminGroup: A query about group membership, privileges,
	// domain, or group properties.
	QueryTypeAdminGroup QueryType = 4
	// QueryTypeJob: A query about scheduled jobs, their command lines,
	// run states, or execution times.
	QueryTypeJob QueryType = 5
	// QueryTypeModule: A query about loaded modules, their base
	// addresses, load types, or function entry points.
	QueryTypeModule QueryType = 6
	// QueryTypeNetworkConnection: A query about active network
	// connections, boundaries, protocols, or TCP states.
	QueryTypeNetworkConnection QueryType = 7
	// QueryTypeNetworkInterfaces: A query about physical or virtual
	// network interfaces, their IP/MAC addresses, or types.
	QueryTypeNetworkInterfaces QueryType = 8
	// QueryTypePeripheralDevice: A query about attached peripheral
	// devices, their classes, models, or vendor information.
	QueryTypePeripheralDevice QueryType = 9
	// QueryTypeProcess: A query about running processes, command
	// lines, ancestry, loaded modules, or execution context.
	QueryTypeProcess QueryType = 10
	// QueryTypeService: A query about system services, their names,
	// versions, labels, or properties.
	QueryTypeService QueryType = 11
	// QueryTypeSession: A query about authenticated user or service
	// sessions, their creation times, or issuer details.
	QueryTypeSession QueryType = 12
	// QueryTypeUser: A query about user accounts, their properties,
	// credentials, or domain information.
	QueryTypeUser QueryType = 13
	// QueryTypeUsers: A query about multiple users belonging to an
	// administrative group.
	QueryTypeUsers QueryType = 14
	// QueryTypeStartupItem: A query about startup configuration items,
	// their run modes, start types, or current states.
	QueryTypeStartupItem QueryType = 15
	// QueryTypeRegistryKey: A Windows-specific query about registry
	// keys, their paths, security descriptors, or modification times.
	QueryTypeRegistryKey QueryType = 16
	// QueryTypeRegistryValue: A Windows-specific query about registry
	// values, their data types, content, or names.
	QueryTypeRegistryValue QueryType = 17
	// QueryTypePrefetch: A Windows-specific query about prefetch
	// files, their run counts, last execution times, or existence.
	QueryTypePrefetch QueryType = 18
	// QueryTypeOther: The query type was not mapped to a standard
	// category. See the query_type attribute for source-specific
	// value.
	QueryTypeOther QueryType = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v QueryType) String() string {
	switch v {
	case QueryTypeUnknown:
		return "Unknown"
	case QueryTypeKernel:
		return "Kernel"
	case QueryTypeFile:
		return "File"
	case QueryTypeFolder:
		return "Folder"
	case QueryTypeAdminGroup:
		return "Admin Group"
	case QueryTypeJob:
		return "Job"
	case QueryTypeModule:
		return "Module"
	case QueryTypeNetworkConnection:
		return "Network Connection"
	case QueryTypeNetworkInterfaces:
		return "Network Interfaces"
	case QueryTypePeripheralDevice:
		return "Peripheral Device"
	case QueryTypeProcess:
		return "Process"
	case QueryTypeService:
		return "Service"
	case QueryTypeSession:
		return "Session"
	case QueryTypeUser:
		return "User"
	case QueryTypeUsers:
		return "Users"
	case QueryTypeStartupItem:
		return "Startup Item"
	case QueryTypeRegistryKey:
		return "Registry Key"
	case QueryTypeRegistryValue:
		return "Registry Value"
	case QueryTypePrefetch:
		return "Prefetch"
	case QueryTypeOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
