// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// QueryLanguage is the OCSF Query Language ID enum. The normalized
// identifier of the query language. See specific usage.
//
// OCSF attribute: query_language_id.
type QueryLanguage int

const (
	// QueryLanguageUnknown: The Query Language is unknown.
	QueryLanguageUnknown QueryLanguage = 0
	// QueryLanguageOther: The Query Language is not mapped. See the
	// query_language attribute, which contains a data source specific
	// value.
	QueryLanguageOther QueryLanguage = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v QueryLanguage) String() string {
	switch v {
	case QueryLanguageUnknown:
		return "Unknown"
	case QueryLanguageOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
