// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// RunModeIds is the OCSF Run Mode IDs enum. The list of normalized
// identifiers that describe application attributes when it is running.
// See specific usage.
//
// OCSF attribute: run_mode_ids.
type RunModeIds int

const (
	// RunModeIdsUnknown: The run mode is unknown.
	RunModeIdsUnknown RunModeIds = 0
	// RunModeIdsOther: The run mode is not mapped. See the run_modes
	// attribute, which contains data source specific values.
	RunModeIdsOther RunModeIds = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v RunModeIds) String() string {
	switch v {
	case RunModeIdsUnknown:
		return "Unknown"
	case RunModeIdsOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
