// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// SecurityLevel is the OCSF Security Level ID enum. The current security
// level of the entity
//
// OCSF attribute: security_level_id.
type SecurityLevel int

const (
	SecurityLevelUnknown     SecurityLevel = 0
	SecurityLevelSecure      SecurityLevel = 1
	SecurityLevelAtRisk      SecurityLevel = 2
	SecurityLevelCompromised SecurityLevel = 3
	// SecurityLevelOther: The security level is not mapped. See the
	// security_level attribute, which contains data source specific
	// values.
	SecurityLevelOther SecurityLevel = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v SecurityLevel) String() string {
	switch v {
	case SecurityLevelUnknown:
		return "Unknown"
	case SecurityLevelSecure:
		return "Secure"
	case SecurityLevelAtRisk:
		return "At Risk"
	case SecurityLevelCompromised:
		return "Compromised"
	case SecurityLevelOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
