// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// Status is the OCSF Status ID enum. The normalized identifier of the
// event status.
//
// OCSF attribute: status_id.
type Status int

const (
	// StatusUnknown: The status is unknown.
	StatusUnknown Status = 0
	StatusSuccess Status = 1
	StatusFailure Status = 2
	// StatusOther: The status is not mapped. See the status attribute,
	// which contains a data source specific value.
	StatusOther Status = 99
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v Status) String() string {
	switch v {
	case StatusUnknown:
		return "Unknown"
	case StatusSuccess:
		return "Success"
	case StatusFailure:
		return "Failure"
	case StatusOther:
		return "Other"
	}
	return strconv.Itoa(int(v))
}
