// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package enums

import "strconv"

// TCPState is the OCSF TCP State ID enum. The state of the TCP socket
// for the network connection.
//
// OCSF attribute: tcp_state_id.
type TCPState int

const (
	// TCPStateUnknown: The socket state is unknown.
	TCPStateUnknown TCPState = 0
	// TCPStateESTABLISHED: The socket has an established connection
	// between a local application and a remote peer.
	TCPStateESTABLISHED TCPState = 1
	// TCPStateSYNSENT: The socket is actively trying to establish a
	// connection to a remote peer.
	TCPStateSYNSENT TCPState = 2
	// TCPStateSYNRECEIVED: The socket has passively received a
	// connection request from a remote peer.
	TCPStateSYNRECEIVED TCPState = 3
	// TCPStateFINWAIT1: The socket connection has been closed by the
	// local application, the remote peer has not yet acknowledged the
	// close, and the system is waiting for it to close its half of the
	// connection.
	TCPStateFINWAIT1 TCPState = 4
	// TCPStateFINWAIT2: The socket connection has been closed by the
	// local application, the remote peer has acknowledged the close,
	// and the system is waiting for it to close its half of the
	// connection.
	TCPStateFINWAIT2 TCPState = 5
	// TCPStateTIMEWAIT: The socket connection has been closed by the
	// local application, the remote peer has closed its half of the
	// connection, and the system is waiting to be sure that the remote
	// peer received the last acknowledgement.
	TCPStateTIMEWAIT TCPState = 6
	// TCPStateCLOSED: The socket is not in use.
	TCPStateCLOSED TCPState = 7
	// TCPStateCLOSEWAIT: The socket connection has been closed by the
	// remote peer, and the system is waiting for the local application
	// to close its half of the connection.
	TCPStateCLOSEWAIT TCPState = 8
	// TCPStateLASTACK: The socket connection has been closed by the
	// remote peer, the local application has closed its half of the
	// connection, and the system is waiting for the remote peer to
	// acknowledge the close.
	TCPStateLASTACK TCPState = 9
	// TCPStateLISTEN: The socket is listening for incoming
	// connections.
	TCPStateLISTEN TCPState = 10
	// TCPStateCLOSING: The socket connection has been closed by the
	// local application and the remote peer simultaneously, and the
	// remote peer has not yet acknowledged the close attempt of the
	// local application.
	TCPStateCLOSING TCPState = 11
)

// String returns the OCSF caption for v, or the underlying
// value if v is outside the known set.
func (v TCPState) String() string {
	switch v {
	case TCPStateUnknown:
		return "Unknown"
	case TCPStateESTABLISHED:
		return "ESTABLISHED"
	case TCPStateSYNSENT:
		return "SYN-SENT"
	case TCPStateSYNRECEIVED:
		return "SYN-RECEIVED"
	case TCPStateFINWAIT1:
		return "FIN-WAIT-1"
	case TCPStateFINWAIT2:
		return "FIN-WAIT-2"
	case TCPStateTIMEWAIT:
		return "TIME-WAIT"
	case TCPStateCLOSED:
		return "CLOSED"
	case TCPStateCLOSEWAIT:
		return "CLOSE-WAIT"
	case TCPStateLASTACK:
		return "LAST-ACK"
	case TCPStateLISTEN:
		return "LISTEN"
	case TCPStateCLOSING:
		return "CLOSING"
	}
	return strconv.Itoa(int(v))
}
