// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package network

import (
	"encoding/json"
	"github.com/hstern/go-ocsf/objects"
)

// FTPActivity describes the OCSF FTP Activity event class: File Transfer
// Protocol (FTP) Activity events report file transfers between a server
// and a client as seen on the network.
//
// OCSF name: ftp_activity. class_uid: 4008.
type FTPActivity struct {
	// Action is the Action. The normalized caption of action_id.
	//
	// OCSF: action (type string_t, requirement optional)
	Action string `json:"action,omitempty"`

	// ActionID is the Action ID. The action taken by a control or other
	// policy-based system leading to an outcome or disposition. Dispositions
	// conform to an action of 1 'Allowed' or 2 'Denied' in most cases. Note
	// that 99 'Other' is not an option. No action would equate to 1
	// 'Allowed'. An unknown action may still correspond to a known
	// disposition. Refer to disposition_id for the outcome of the action.
	//
	// OCSF: action_id (type integer_t, requirement required)
	ActionID int `json:"action_id"`

	// ActivityID is the Activity ID. The normalized identifier of the
	// activity that triggered the event.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The event activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. The actor object describes details about the
	// user/role/process that was the source of the activity.
	//
	// OCSF: actor (type actor, requirement optional)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// AppName is the Application Name. The name of the application
	// associated with the event or object.
	//
	// OCSF: app_name (type string_t, requirement optional)
	AppName string `json:"app_name,omitempty"`

	// Attacks is the MITRE ATT&CK® Details. An array of MITRE ATT&CK®
	// objects describing the tactics, techniques & sub-techniques identified
	// by a security control or finding.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []objects.Attack `json:"attacks,omitempty"`

	// Authorizations is the Authorization Information. Provides details
	// about an authorization, such as authorization outcome, and any
	// associated policies related to the activity/event.
	//
	// OCSF: authorizations (type []authorization, requirement optional)
	Authorizations []objects.Authorization `json:"authorizations,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event was originally created or logged.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Codes is the Response Codes. The list of return codes to the FTP
	// command.
	//
	// OCSF: codes (type []integer_t, requirement recommended)
	Codes []int `json:"codes,omitempty"`

	// Command is the Command. The FTP command.
	//
	// OCSF: command (type string_t, requirement recommended)
	Command string `json:"command,omitempty"`

	// CommandResponses is the Command Responses. The list of responses to
	// the FTP command.
	//
	// OCSF: command_responses (type []string_t, requirement recommended)
	CommandResponses []string `json:"command_responses,omitempty"`

	// ConnectionInfo is the Connection Info. The network connection
	// information.
	//
	// OCSF: connection_info (type network_connection_info, requirement recommended)
	ConnectionInfo *objects.NetworkConnectionInfo `json:"connection_info,omitempty"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Device is the Device. An addressable device, computer system or host.
	//
	// OCSF: device (type device, requirement recommended)
	Device *objects.Device `json:"device,omitempty"`

	// Disposition is the Disposition. The disposition name, normalized to
	// the caption of the disposition_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: disposition (type string_t, requirement optional)
	Disposition string `json:"disposition,omitempty"`

	// DispositionID is the Disposition ID. Describes the outcome or action
	// taken by a security control, such as access control checks, malware
	// detections or various types of policy violations.
	//
	// OCSF: disposition_id (type integer_t, requirement recommended)
	DispositionID int `json:"disposition_id,omitempty"`

	// DstEndpoint is the Destination Endpoint. The responder (server) in a
	// network connection.
	//
	// OCSF: dst_endpoint (type network_endpoint, requirement required)
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The end time of a time period, or the time of
	// the most recent event included in the aggregate event.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// File is the File. The file that is the target of the FTP activity.
	//
	// OCSF: file (type file, requirement optional)
	File *objects.File `json:"file,omitempty"`

	// FirewallRule is the Firewall Rule. The firewall rule that triggered
	// the event.
	//
	// OCSF: firewall_rule (type firewall_rule, requirement optional)
	FirewallRule *objects.FirewallRule `json:"firewall_rule,omitempty"`

	// Ja4FingerprintList is the JA4+ Fingerprints. A list of the JA4+
	// network fingerprints.
	//
	// OCSF: ja4_fingerprint_list (type []ja4_fingerprint, requirement optional)
	Ja4FingerprintList []objects.Ja4Fingerprint `json:"ja4_fingerprint_list,omitempty"`

	// LoadBalancer is the Load Balancer. The Load Balancer object contains
	// information related to the device that is distributing incoming
	// traffic to specified destinations.
	//
	// OCSF: load_balancer (type load_balancer, requirement recommended)
	LoadBalancer *objects.LoadBalancer `json:"load_balancer,omitempty"`

	// Malware is the Malware. A list of Malware objects, describing details
	// about the identified malware.
	//
	// OCSF: malware (type []malware, requirement optional)
	Malware []objects.Malware `json:"malware,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Name is the Name. The name of the data affiliated with the command.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// Port is the Port. The dynamic port established for impending data
	// transfers.
	//
	// OCSF: port (type port_t, requirement recommended)
	Port int `json:"port,omitempty"`

	// Proxy is the Proxy. The proxy (server) in a network connection.
	//
	// OCSF: proxy (type network_proxy, requirement recommended)
	Proxy *objects.NetworkProxy `json:"proxy,omitempty"`

	// ProxyConnectionInfo is the Proxy Connection Info. The connection
	// information from the proxy server to the remote server.
	//
	// OCSF: proxy_connection_info (type network_connection_info, requirement recommended)
	ProxyConnectionInfo *objects.NetworkConnectionInfo `json:"proxy_connection_info,omitempty"`

	// ProxyEndpoint is the Proxy Endpoint. The proxy (server) in a network
	// connection.
	//
	// OCSF: proxy_endpoint (type network_proxy, requirement optional)
	ProxyEndpoint *objects.NetworkProxy `json:"proxy_endpoint,omitempty"`

	// ProxyHTTPRequest is the Proxy HTTP Request. The HTTP Request from the
	// proxy server to the remote server.
	//
	// OCSF: proxy_http_request (type http_request, requirement optional)
	ProxyHTTPRequest *objects.HTTPRequest `json:"proxy_http_request,omitempty"`

	// ProxyHTTPResponse is the Proxy HTTP Response. The HTTP Response from
	// the remote server to the proxy server.
	//
	// OCSF: proxy_http_response (type http_response, requirement optional)
	ProxyHTTPResponse *objects.HTTPResponse `json:"proxy_http_response,omitempty"`

	// ProxyTLS is the Proxy TLS. The TLS protocol negotiated between the
	// proxy server and the remote server.
	//
	// OCSF: proxy_tls (type tls, requirement recommended)
	ProxyTLS *objects.TLS `json:"proxy_tls,omitempty"`

	// ProxyTraffic is the Proxy Traffic. The network traffic refers to the
	// amount of data moving across a network, from proxy to remote server at
	// a given point of time.
	//
	// OCSF: proxy_traffic (type network_traffic, requirement recommended)
	ProxyTraffic *objects.NetworkTraffic `json:"proxy_traffic,omitempty"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// SrcEndpoint is the Source Endpoint. The initiator (client) of the
	// network connection.
	//
	// OCSF: src_endpoint (type network_endpoint, requirement recommended)
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`

	// StartTime is the Start Time. The start time of a time period, or the
	// time of the least recent event included in the aggregate event.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The event status, normalized to the caption of
	// the status_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized identifier of the event
	// status.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TLS is the TLS. The Transport Layer Security (TLS) attributes.
	//
	// OCSF: tls (type tls, requirement optional)
	TLS *objects.TLS `json:"tls,omitempty"`

	// Traffic is the Traffic. The network traffic refers to the amount of
	// data moving across a network at a given point of time. Intended to be
	// used alongside Network Connection.
	//
	// OCSF: traffic (type network_traffic, requirement recommended)
	Traffic *objects.NetworkTraffic `json:"traffic,omitempty"`

	// Type is the Type. The type of FTP network connection (e.g. active,
	// passive).
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for FTP Activity (4008).
// Computed as CategoryUID*1000 + class identifier within the category.
func (FTPActivity) OCSFClassUID() int { return 4008 }

// OCSFClassName returns the OCSF class_name for FTP Activity.
func (FTPActivity) OCSFClassName() string { return "FTP Activity" }

// OCSFCategoryUID returns the OCSF category_uid for the network category (4).
func (FTPActivity) OCSFCategoryUID() int { return 4 }

// OCSFCategoryName returns the OCSF category_name (network).
func (FTPActivity) OCSFCategoryName() string { return "network" }
