// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

// Package ocsf is a Go implementation of the Open Cybersecurity
// Schema Framework (OCSF) — see https://schema.ocsf.io/ — providing
// typed encoder / decoder support for OCSF events.
//
// The bulk of the package surface (per-event-class and per-object
// types) is generated by an internal codegen tool from the vendored
// upstream OCSF JSON schema and lives in the events/ and objects/
// subpackages. Hand-written core in this root package supplies the
// Event interface, the BaseEvent forward-compatibility fallback, the
// Parse entrypoint, and validation primitives.
//
// The wire-format version this package targets is exposed as
// SchemaVersion. Bumping SchemaVersion is a library-minor release;
// consumers that need to pin a specific schema version should pin a
// specific library version.
package ocsf

// Regenerate the events/, objects/, and enums/ packages from the
// vendored OCSF schema. The schema-version directory passed via
// -schema must match SchemaVersion below; when the version bumps
// the path in this directive bumps with it. The `codegen-diff` CI
// job runs this directive and fails on any diff against the
// committed output, catching silent drift between the schema
// version we pin and the generated types we ship.
//
//go:generate go run ./internal/gen -schema internal/schema/v1.3.0 -emit -out .

// SchemaVersion is the OCSF schema version this package's generated
// types track on the wire. It is the single source of truth for the
// schema version pinned by this library release.
const SchemaVersion = "1.3.0"
