// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

// Package ocsf is a Go implementation of the Open Cybersecurity
// Schema Framework (OCSF) — see https://schema.ocsf.io/ — providing
// typed encoder / decoder support for OCSF events.
//
// The bulk of the package surface (per-event-class and per-object
// types) is generated by an internal codegen tool from the vendored
// upstream OCSF JSON schema and lives in the events/ and objects/
// subpackages. Hand-written core in this root package supplies the
// Event interface, the BaseEvent forward-compatibility fallback, the
// Parse entrypoint, and validation primitives.
//
// The wire-format version this package targets is exposed as
// SchemaVersion. Bumping SchemaVersion is a library-minor release;
// consumers that need to pin a specific schema version should pin a
// specific library version.
package ocsf

// Regenerate the events/, objects/, and enums/ packages from the
// upstream OCSF schema checked out under internal/schema/upstream/
// (a git submodule pinned to the upstream tag matching
// SchemaVersion below). When the version bumps, the submodule
// commit advances and SchemaVersion updates in the same PR; the
// codegen-diff CI job runs this directive and fails on any diff
// against the committed output, catching silent drift between the
// schema version we pin and the generated types we ship.
//
// The submodule must be checked out before running go generate.
// CI does this via actions/checkout's submodules: recursive
// option; local invocations need `git submodule update --init`
// at least once after clone.
//
//go:generate go run ./internal/gen -schema internal/schema/upstream -emit -out .

// SchemaVersion is the OCSF schema version this package's
// generated types track on the wire. It is the single source of
// truth for the schema version pinned by this library release
// and must match the upstream tag the internal/schema/upstream
// submodule is checked out at.
const SchemaVersion = "1.8.0"
