// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Account describes the OCSF Account object: The Account object contains
// details about the account that initiated or performed a specific
// activity within a system or application.
//
// OCSF name: account.
type Account struct {
	// Labels is the Labels. The list of labels/tags associated to the
	// account.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// Name is the Name. The name of the account (e.g. GCP Account Name).
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Type is the Type. The account type, normalized to the caption of
	// 'account_type_id'. In the case of 'Other', it is defined by the event
	// source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The normalized account type identifier.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// UID is the Unique ID. The unique identifier of the account (e.g. AWS
	// Account ID).
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
