// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Actor describes the OCSF Actor object: The Actor object contains
// details about the user, role, application, service, or process that
// initiated or performed a specific activity.
//
// OCSF name: actor.
type Actor struct {
	// AppName is the Application Name. The client application or service
	// that initiated the activity. This can be in conjunction with the user
	// if present. Note that app_name is distinct from the process if
	// present.
	//
	// OCSF: app_name (type string_t, requirement optional)
	AppName string `json:"app_name,omitempty"`

	// AppUID is the Application ID. The unique identifier of the client
	// application or service that initiated the activity. This can be in
	// conjunction with the user if present. Note that app_name is distinct
	// from the process.pid or process.uid if present.
	//
	// OCSF: app_uid (type string_t, requirement optional)
	AppUID string `json:"app_uid,omitempty"`

	// Authorizations is the Authorization Information. Provides details
	// about an authorization, such as authorization outcome, and any
	// associated policies related to the activity/event.
	//
	// OCSF: authorizations (type []authorization, requirement optional)
	Authorizations []Authorization `json:"authorizations,omitempty"`

	// Idp is the Identity Provider. This object describes details about the
	// Identity Provider used.
	//
	// OCSF: idp (type idp, requirement optional)
	Idp *Idp `json:"idp,omitempty"`

	// InvokedBy is the Invoked by. The name of the service that invoked the
	// activity as described in the event.
	//
	// OCSF: invoked_by (type string_t, requirement optional)
	//
	// Deprecated: Use <code> app_name, app_uid </code> attributes instead.
	InvokedBy string `json:"invoked_by,omitempty"`

	// Process is the Process. The process that initiated the activity.
	//
	// OCSF: process (type process, requirement recommended)
	Process *Process `json:"process,omitempty"`

	// Session is the Session. The user session from which the activity was
	// initiated.
	//
	// OCSF: session (type session, requirement optional)
	Session *Session `json:"session,omitempty"`

	// User is the User. The user that initiated the activity or the user
	// context from which the activity was initiated.
	//
	// OCSF: user (type user, requirement recommended)
	User *User `json:"user,omitempty"`
}
