// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AffectedCode describes the OCSF Affected Code object: The Affected
// Code object describes details about a code block identified as
// vulnerable.
//
// OCSF name: affected_code.
type AffectedCode struct {
	// EndColumn is the End Column. The column number of the last part of the
	// assessed code identified as vulnerable.
	//
	// OCSF: end_column (type integer_t, requirement recommended)
	EndColumn *int `json:"end_column,omitempty"`

	// EndLine is the End Line. The line number of the last line of code
	// block identified as vulnerable.
	//
	// OCSF: end_line (type integer_t, requirement recommended)
	EndLine *int `json:"end_line,omitempty"`

	// File is the File. Details about the file that contains the affected
	// code block.
	//
	// OCSF: file (type file, requirement required)
	File *File `json:"file"`

	// Owner is the Owner. Details about the user that owns the affected
	// file.
	//
	// OCSF: owner (type user, requirement optional)
	Owner *User `json:"owner,omitempty"`

	// Remediation is the Remediation Guidance. Describes the recommended
	// remediation steps to address identified issue(s).
	//
	// OCSF: remediation (type remediation, requirement optional)
	Remediation *Remediation `json:"remediation,omitempty"`

	// Rule is the Related Rule. Details about the specific rule, e.g., those
	// defined as part of a larger policy, that triggered the finding.
	//
	// OCSF: rule (type rule, requirement recommended)
	Rule *Rule `json:"rule,omitempty"`

	// StartColumn is the Start Column. The column number of the first part
	// of the assessed code identified as vulnerable.
	//
	// OCSF: start_column (type integer_t, requirement recommended)
	StartColumn *int `json:"start_column,omitempty"`

	// StartLine is the Start Line. The line number of the first line of code
	// block identified as vulnerable.
	//
	// OCSF: start_line (type integer_t, requirement recommended)
	StartLine *int `json:"start_line,omitempty"`
}
