// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AffectedPackage describes the OCSF Affected Software Package object:
// The Affected Package object describes details about a software package
// identified as affected by a vulnerability/vulnerabilities.
//
// OCSF name: affected_package.
type AffectedPackage struct {
	// Architecture is the Architecture. Architecture is a shorthand name
	// describing the type of computer hardware the packaged software is
	// meant to run on.
	//
	// OCSF: architecture (type string_t, requirement recommended)
	Architecture string `json:"architecture,omitempty"`

	// CpeName is the The product CPE identifier. The Common Platform
	// Enumeration (CPE) name as described by (NIST) For example:
	// cpe:/a:apple:safari:16.2.
	//
	// OCSF: cpe_name (type string_t, requirement optional)
	CpeName string `json:"cpe_name,omitempty"`

	// Epoch is the Epoch. The software package epoch. Epoch is a way to
	// define weighted dependencies based on version numbers.
	//
	// OCSF: epoch (type integer_t, requirement optional)
	Epoch int `json:"epoch,omitempty"`

	// FixedInVersion is the Fixed In Version. The software package version
	// in which a reported vulnerability was patched/fixed.
	//
	// OCSF: fixed_in_version (type string_t, requirement optional)
	FixedInVersion string `json:"fixed_in_version,omitempty"`

	// Hash is the Hash. Cryptographic hash to identify the binary instance
	// of a software component. This can include any component such file,
	// package, or library.
	//
	// OCSF: hash (type fingerprint, requirement optional)
	Hash *Fingerprint `json:"hash,omitempty"`

	// License is the Software License. The software license applied to this
	// package.
	//
	// OCSF: license (type string_t, requirement optional)
	License string `json:"license,omitempty"`

	// Name is the Name. The software package name.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// PackageManager is the Package Manager. The software packager manager
	// utilized to manage a package on a system, e.g. npm, yum, dpkg etc.
	//
	// OCSF: package_manager (type string_t, requirement optional)
	PackageManager string `json:"package_manager,omitempty"`

	// Path is the Path. The installation path of the affected package.
	//
	// OCSF: path (type string_t, requirement optional)
	Path string `json:"path,omitempty"`

	// Purl is the Package URL. A purl is a URL string used to identify and
	// locate a software package in a mostly universal and uniform way across
	// programming languages, package managers, packaging conventions, tools,
	// APIs and databases.
	//
	// OCSF: purl (type string_t, requirement optional)
	Purl string `json:"purl,omitempty"`

	// Release is the Software Release Details. Release is the number of
	// times a version of the software has been packaged.
	//
	// OCSF: release (type string_t, requirement optional)
	Release string `json:"release,omitempty"`

	// Remediation is the Remediation Guidance. Describes the recommended
	// remediation steps to address identified issue(s).
	//
	// OCSF: remediation (type remediation, requirement optional)
	Remediation *Remediation `json:"remediation,omitempty"`

	// Type is the Type. The type of software package, normalized to the
	// caption of the type_id value. In the case of 'Other', it is defined by
	// the source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The type of software package.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// VendorName is the Vendor Name. The name of the vendor who published
	// the software package.
	//
	// OCSF: vendor_name (type string_t, requirement optional)
	VendorName string `json:"vendor_name,omitempty"`

	// Version is the Version. The software package version.
	//
	// OCSF: version (type string_t, requirement required)
	Version string `json:"version"`
}
