// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AnalysisTarget describes the OCSF Analysis Target object: The analysis
// target defines the scope of monitored activities, specifying what
// entity, system or process is analyzed for activity patterns.
//
// OCSF name: analysis_target.
type AnalysisTarget struct {
	// Name is the Name. The specific name or identifier of the analysis
	// target, such as the username of a User Account, the name of a
	// Kubernetes Cluster, the identifier of a Network Namespace, or the name
	// of an Application Component.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Type is the Type. The category of the analysis target, such as User
	// Account, Kubernetes Cluster, Network Namespace, or Application
	// Component.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`
}
