// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// API describes the OCSF API object: The API, or Application Programming
// Interface, object represents information pertaining to an API request
// and response.
//
// OCSF name: api.
type API struct {
	// Group is the Group. The information pertaining to the API group.
	//
	// OCSF: group (type group, requirement optional)
	Group *Group `json:"group,omitempty"`

	// Operation is the Operation. Verb/Operation associated with the request
	//
	// OCSF: operation (type string_t, requirement required)
	Operation string `json:"operation"`

	// Request is the API Request Details. Details pertaining to the API
	// request.
	//
	// OCSF: request (type request, requirement recommended)
	Request *Request `json:"request,omitempty"`

	// Response is the API Response Details. Details pertaining to the API
	// response.
	//
	// OCSF: response (type response, requirement recommended)
	Response *Response `json:"response,omitempty"`

	// Service is the Service. The information pertaining to the API service.
	//
	// OCSF: service (type service, requirement optional)
	Service *Service `json:"service,omitempty"`

	// Token is the Token. The API or client token used to authenticate or
	// authorize the API request. This attribute contains the base token
	// object that represents: (1) IdP-issued client tokens (type_id: 6) such
	// as Okta API tokens or Microsoft Entra ID Application Registration
	// client secrets, or (2) generic API tokens/keys (type_id: 7) used for
	// SaaS application authentication. Use this attribute when the API
	// request was authenticated using a token that should be tracked as part
	// of the API activity event. Note: Protocol-specific authentication
	// tokens (Kerberos, OIDC, SAML) should be represented using
	// authentication_token in authentication events, not in API activity
	// events.
	//
	// OCSF: token (type token, requirement optional)
	Token *Token `json:"token,omitempty"`

	// Version is the Version. The version of the API service.
	//
	// OCSF: version (type string_t, requirement optional)
	Version string `json:"version,omitempty"`
}
