// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// Application describes the OCSF Application object: An Application
// describes the details for an inventoried application as reported by an
// Application Security tool or other Developer-centric tooling.
// Applications can be defined as Kubernetes resources, Containerized
// resources, or application hosting-specific cloud sources such as AWS
// Elastic BeanStalk, AWS Lightsail, or Azure Logic Apps.
//
// OCSF name: application.
type Application struct {
	// Criticality is the Business Criticality. The criticality of the
	// application as defined by the event source.
	//
	// OCSF: criticality (type string_t, requirement optional)
	Criticality string `json:"criticality,omitempty"`

	// Data is the Data. Additional data describing the application.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Desc is the Application Description. A description or commentary for
	// an application, usually retrieved from an upstream system.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Group is the Group. The name of the related application or associated
	// resource group.
	//
	// OCSF: group (type group, requirement optional)
	Group *Group `json:"group,omitempty"`

	// Hostname is the Hostname. The fully qualified name of the application.
	//
	// OCSF: hostname (type hostname_t, requirement optional)
	Hostname string `json:"hostname,omitempty"`

	// Labels is the Labels. The list of labels associated to the
	// application.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// Name is the Application Name. The name of the application.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Owner is the Owner. The identity of the service or user account that
	// owns the application.
	//
	// OCSF: owner (type user, requirement recommended)
	Owner *User `json:"owner,omitempty"`

	// Region is the Region. The cloud region of the resource.
	//
	// OCSF: region (type string_t, requirement optional)
	Region string `json:"region,omitempty"`

	// ResourceRelationship is the Application Relationship. A graph
	// representation showing how this application relates to and interacts
	// with other entities in the environment. This can include parent/child
	// relationships, dependencies, or other connections.
	//
	// OCSF: resource_relationship (type graph, requirement optional)
	ResourceRelationship *Graph `json:"resource_relationship,omitempty"`

	// RiskLevel is the Risk Level. The risk level, normalized to the caption
	// of the risk_level_id value.
	//
	// OCSF: risk_level (type string_t, requirement optional)
	RiskLevel string `json:"risk_level,omitempty"`

	// RiskLevelID is the Risk Level ID. The normalized risk level id.
	//
	// OCSF: risk_level_id (type integer_t, requirement optional)
	RiskLevelID int `json:"risk_level_id,omitempty"`

	// RiskScore is the Risk Score. The risk score as reported by the event
	// source.
	//
	// OCSF: risk_score (type integer_t, requirement optional)
	RiskScore int `json:"risk_score,omitempty"`

	// Sbom is the Related SBOM. The Software Bill of Materials (SBOM)
	// associated with the application
	//
	// OCSF: sbom (type sbom, requirement optional)
	Sbom *Sbom `json:"sbom,omitempty"`

	// Tags is the Tags. The list of tags; {key:value} pairs associated to
	// the application.
	//
	// OCSF: tags (type []key_value_object, requirement optional)
	Tags []KeyValueObject `json:"tags,omitempty"`

	// Type is the Application Type. The type of application as defined by
	// the event source, e.g., GitHub, Azure Logic App, or Amazon Elastic
	// BeanStalk.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// UID is the Application ID. The unique identifier for the application.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// UIDAlt is the Application Alternative ID. An alternative or contextual
	// identifier for the application, such as a configuration, organization,
	// or license UID.
	//
	// OCSF: uid_alt (type string_t, requirement optional)
	UIDAlt string `json:"uid_alt,omitempty"`

	// URL is the URL. The URL of the application.
	//
	// OCSF: url (type url, requirement optional)
	URL *URL `json:"url,omitempty"`

	// Version is the Application Version. The semantic version of the
	// application, e.g., 1.7.4.
	//
	// OCSF: version (type string_t, requirement optional)
	Version string `json:"version,omitempty"`
}
