// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Attack describes the OCSF MITRE ATT&CK® object: The MITRE ATT&CK®
// object describes the tactic, technique & sub-technique associated to
// an attack as defined in ATT&CK® Matrix.
//
// OCSF name: attack.
type Attack struct {
	// SubTechnique is the Sub Technique. The Sub Technique object describes
	// the sub technique ID and/or name associated to an attack, as defined
	// by ATT&CK® Matrix.
	//
	// OCSF: sub_technique (type sub_technique, requirement optional)
	SubTechnique *SubTechnique `json:"sub_technique,omitempty"`

	// Tactic is the Tactic. The Tactic object describes the tactic ID and/or
	// name that is associated to an attack, as defined by ATT&CK® Matrix.
	//
	// OCSF: tactic (type tactic, requirement optional)
	Tactic *Tactic `json:"tactic,omitempty"`

	// Tactics is the Tactics. The Tactic object describes the tactic ID
	// and/or tactic name that are associated with the attack technique, as
	// defined by ATT&CK® Matrix.
	//
	// OCSF: tactics (type []tactic, requirement optional)
	Tactics []Tactic `json:"tactics,omitempty"`

	// Technique is the Technique. The Technique object describes the
	// technique ID and/or name associated to an attack, as defined by
	// ATT&CK® Matrix.
	//
	// OCSF: technique (type technique, requirement optional)
	Technique *Technique `json:"technique,omitempty"`

	// Version is the Version. The ATT&CK® Matrix version.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
