// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AuthenticationToken describes the OCSF Authentication Token object:
// The Authentication Token object extends the base token object and
// represents standardized authentication tokens, tickets, or assertions
// that conform to established authentication protocols such as Kerberos,
// OIDC, and SAML. This object inherits all attributes from token and
// adds protocol-specific attributes (e.g., kerberos_flags,
// encryption_details) for authentication events. Use this object in
// authentication events to represent protocol-specific tokens: Kerberos
// Ticket Granting Tickets (TGT) and Service Tickets (ST), OIDC Identity
// Tokens and Refresh Tokens, and SAML Assertions. These tokens are
// issued by authentication servers and identity providers and carry
// protocol-specific metadata, lifecycle information, and security
// attributes defined by their respective specifications. When to use
// this object: Use authentication_token when representing
// protocol-specific authentication tokens (type_id values 1-5: Kerberos
// TGT/ST, OIDC ID/Refresh tokens, SAML assertions) in authentication
// events. When NOT to use this object: Do NOT use authentication_token
// for API tokens or client tokens (type_id values 6-7) used in API
// activity events - use the base token object instead. Do NOT use
// authentication_token for generic API keys - use the base token object
// instead.
//
// OCSF name: authentication_token.
type AuthenticationToken struct {
	// CreatedTime is the Created Time. The time that the authentication
	// token was created or issued. This corresponds to the token issuance
	// time, such as the iat (issued at) claim in OIDC tokens, the issue
	// instant in SAML assertions, or the ticket start time in Kerberos
	// tickets.
	//
	// OCSF: created_time (type timestamp_t, requirement recommended)
	CreatedTime int64 `json:"created_time,omitempty"`

	// EncryptionDetails is the Encryption Details. The encryption details of
	// the authentication token.
	//
	// OCSF: encryption_details (type encryption_details, requirement recommended)
	EncryptionDetails *EncryptionDetails `json:"encryption_details,omitempty"`

	// ExpirationTime is the Expiration Time. The expiration time of the
	// authentication token.
	//
	// OCSF: expiration_time (type timestamp_t, requirement optional)
	ExpirationTime int64 `json:"expiration_time,omitempty"`

	// IsRenewable is the Renewable. Indicates whether the authentication
	// token is renewable.
	//
	// OCSF: is_renewable (type boolean_t, requirement optional)
	IsRenewable bool `json:"is_renewable,omitempty"`

	// KerberosFlags is the Kerberos Flags. A bitmask, either in hexadecimal
	// or decimal form, which encodes various attributes or permissions
	// associated with a Kerberos ticket. These flags delineate specific
	// characteristics of the ticket, such as its renewability or
	// forwardability.
	//
	// OCSF: kerberos_flags (type string_t, requirement recommended)
	KerberosFlags string `json:"kerberos_flags,omitempty"`

	// ModifiedTime is the Modified Time. The last time the token was
	// updated.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// Name is the Name. The human-friendly name of a token or key, if
	// available, such as the name from the Okta API Token API.
	//
	// OCSF: name (type string_t, requirement optional)
	Name string `json:"name,omitempty"`

	// TenantUID is the Tenant UID. The unique identifier of the tenant or
	// organization that owns the token or key, or the tenant context in
	// which the token is authorized for use. This is particularly relevant
	// in multi-tenant Identity Provider scenarios where tokens are scoped to
	// specific tenants.
	//
	// OCSF: tenant_uid (type string_t, requirement optional)
	TenantUID string `json:"tenant_uid,omitempty"`

	// Type is the Type. The type of the authentication token.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The normalized authentication token type
	// identifier. This attribute restricts the base token.type_id enum to
	// only protocol-specific authentication token types (values 0, 1-5, 99).
	// API tokens and client tokens (values 6-7) are not valid for
	// authentication_token - use the base token object for those types.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// UID is the Unique ID. The unique ID of a token or key, if available,
	// such as the Secret ID of Entra ID Application Registration Client
	// Secrets.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`

	// Zone is the Network Zone. The network zone or geographic region that
	// the token or key is authorized to be used from. This may represent
	// network-based access restrictions, geographic limitations, or other
	// zone-based authorization policies. Examples include Okta's network
	// zone restrictions or cloud provider region restrictions.
	//
	// OCSF: zone (type string_t, requirement optional)
	Zone string `json:"zone,omitempty"`
}
