// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AuthFactor describes the OCSF Authentication Factor object: An
// Authentication Factor object describes a category of methods used for
// identity verification in an authentication attempt.
//
// OCSF name: auth_factor.
type AuthFactor struct {
	// Device is the Device. Device used to complete an authentication
	// request.
	//
	// OCSF: device (type device, requirement recommended)
	Device *Device `json:"device,omitempty"`

	// EmailAddr is the Email Address. The email address used in an
	// email-based authentication factor.
	//
	// OCSF: email_addr (type email_t, requirement optional)
	EmailAddr string `json:"email_addr,omitempty"`

	// FactorType is the Factor Type. The type of authentication factor used
	// in an authentication attempt.
	//
	// OCSF: factor_type (type string_t, requirement recommended)
	FactorType string `json:"factor_type,omitempty"`

	// FactorTypeID is the Factor Type ID. The normalized identifier for the
	// authentication factor.
	//
	// OCSF: factor_type_id (type integer_t, requirement required)
	FactorTypeID int `json:"factor_type_id"`

	// IsHotp is the HMAC-based One-time Password (HOTP). Whether the
	// authentication factor is an HMAC-based One-time Password (HOTP).
	//
	// OCSF: is_hotp (type boolean_t, requirement recommended)
	IsHotp bool `json:"is_hotp,omitempty"`

	// IsTotp is the Time-based One-time Password (TOTP). Whether the
	// authentication factor is a Time-based One-time Password (TOTP).
	//
	// OCSF: is_totp (type boolean_t, requirement recommended)
	IsTotp bool `json:"is_totp,omitempty"`

	// PhoneNumber is the Phone Number. The phone number used for a
	// telephony-based authentication request.
	//
	// OCSF: phone_number (type string_t, requirement optional)
	PhoneNumber string `json:"phone_number,omitempty"`

	// Provider is the Provider. The name of provider for an authentication
	// factor.
	//
	// OCSF: provider (type string_t, requirement recommended)
	Provider string `json:"provider,omitempty"`

	// SecurityQuestions is the Security Questions. The question(s) provided
	// to user for a question-based authentication factor.
	//
	// OCSF: security_questions (type []string_t, requirement optional)
	SecurityQuestions []string `json:"security_questions,omitempty"`
}
