// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// AutonomousSystem describes the OCSF Autonomous System object: An
// autonomous system (AS) is a collection of connected Internet Protocol
// (IP) routing prefixes under the control of one or more network
// operators on behalf of a single administrative entity or domain that
// presents a common, clearly defined routing policy to the internet.
//
// OCSF name: autonomous_system.
type AutonomousSystem struct {
	// Name is the Name. Organization name for the Autonomous System.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Number is the Number. Unique number that the AS is identified by.
	//
	// OCSF: number (type integer_t, requirement recommended)
	Number int `json:"number,omitempty"`
}
