// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// CisCsc describes the OCSF CIS CSC object: The CIS Critical Security
// Control (CSC) contains information as defined by the Center for
// Internet Security Critical Security Control (CIS CSC). Prioritized set
// of actions to protect your organization and data from cyber-attack
// vectors.
//
// OCSF name: cis_csc.
//
// Deprecated: Use the cis_control object instead.
type CisCsc struct {
	// Control is the Security Control. A Control is prescriptive,
	// prioritized, and simplified set of best practices that one can use to
	// strengthen their cybersecurity posture. e.g. AWS SecurityHub Controls,
	// CIS Controls.
	//
	// OCSF: control (type string_t, requirement required)
	Control string `json:"control"`

	// Version is the Version. The CIS critical security control version.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
