// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// ClassifierDetails describes the OCSF Classifier Details object: The
// Classifier Details object describes details about the classifier used
// for data classification.
//
// OCSF name: classifier_details.
type ClassifierDetails struct {
	// Name is the Name. The name of the classifier.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Type is the Type. The type of the classifier.
	//
	// OCSF: type (type string_t, requirement required)
	Type string `json:"type"`

	// UID is the Unique ID. The unique identifier of the classifier.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
