// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Cloud describes the OCSF Cloud object: The Cloud object contains
// information about a cloud account such as AWS Account ID, regions,
// etc.
//
// OCSF name: cloud.
type Cloud struct {
	// Account is the Account. The account object describes details about the
	// account that was the source or target of the activity.
	//
	// OCSF: account (type account, requirement optional)
	Account *Account `json:"account,omitempty"`

	// Org is the Organization. Organization and org unit relevant to the
	// event or object.
	//
	// OCSF: org (type organization, requirement optional)
	Org *Organization `json:"org,omitempty"`

	// ProjectUID is the Project ID. The unique identifier of a Cloud
	// project.
	//
	// OCSF: project_uid (type string_t, requirement optional)
	ProjectUID string `json:"project_uid,omitempty"`

	// Provider is the Provider. The unique name of the Cloud services
	// provider, such as AWS, MS Azure, GCP, etc.
	//
	// OCSF: provider (type string_t, requirement required)
	Provider string `json:"provider"`

	// Region is the Region. The name of the cloud region, as defined by the
	// cloud provider.
	//
	// OCSF: region (type string_t, requirement recommended)
	Region string `json:"region,omitempty"`

	// Zone is the Network Zone. The availability zone in the cloud region,
	// as defined by the cloud provider.
	//
	// OCSF: zone (type string_t, requirement optional)
	Zone string `json:"zone,omitempty"`
}
