// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Container describes the OCSF Container object: The Container object
// describes an instance of a specific container. A container is a
// prepackaged, portable system image that runs isolated on an existing
// system using a container runtime like containerd.
//
// OCSF name: container.
type Container struct {
	// Hash is the Hash. Commit hash of image created for docker or the
	// SHA256 hash of the container. For example:
	// 13550340a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de.
	//
	// OCSF: hash (type fingerprint, requirement recommended)
	Hash *Fingerprint `json:"hash,omitempty"`

	// Image is the Image. The container image used as a template to run the
	// container.
	//
	// OCSF: image (type image, requirement recommended)
	Image *Image `json:"image,omitempty"`

	// Name is the Name. The container name.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// NetworkDriver is the Network Driver. The network driver used by the
	// container. For example, bridge, overlay, host, none, etc.
	//
	// OCSF: network_driver (type string_t, requirement optional)
	NetworkDriver string `json:"network_driver,omitempty"`

	// Orchestrator is the Orchestrator. The orchestrator managing the
	// container, such as ECS, EKS, K8s, or OpenShift.
	//
	// OCSF: orchestrator (type string_t, requirement optional)
	Orchestrator string `json:"orchestrator,omitempty"`

	// PodUUID is the Pod UUID. The unique identifier of the pod (or
	// equivalent) that the container is executing on.
	//
	// OCSF: pod_uuid (type uuid_t, requirement optional)
	PodUUID string `json:"pod_uuid,omitempty"`

	// Runtime is the Runtime. The backend running the container, such as
	// containerd or cri-o.
	//
	// OCSF: runtime (type string_t, requirement optional)
	Runtime string `json:"runtime,omitempty"`

	// Size is the Size. The size of the container image.
	//
	// OCSF: size (type long_t, requirement recommended)
	Size int64 `json:"size,omitempty"`

	// Tag is the Image Tag. The tag used by the container. It can indicate
	// version, format, OS.
	//
	// OCSF: tag (type string_t, requirement optional)
	Tag string `json:"tag,omitempty"`

	// UID is the Unique ID. The full container unique identifier for this
	// instantiation of the container. For example:
	// ac2ea168264a08f9aaca0dfc82ff3551418dfd22d02b713142a6843caa2f61bf.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
