// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Cwe describes the OCSF CWE object: The CWE object represents a
// weakness in a software system that can be exploited by a threat actor
// to perform an attack. The CWE object is based on the Common Weakness
// Enumeration (CWE) catalog.
//
// OCSF name: cwe.
type Cwe struct {
	// Caption is the Caption. The caption assigned to the Common Weakness
	// Enumeration unique identifier.
	//
	// OCSF: caption (type string_t, requirement optional)
	Caption string `json:"caption,omitempty"`

	// SrcURL is the Source URL. URL pointing to the CWE Specification. For
	// more information see CWE.
	//
	// OCSF: src_url (type url_t, requirement optional)
	SrcURL string `json:"src_url,omitempty"`

	// UID is the CWE ID. The Common Weakness Enumeration unique number
	// assigned to a specific weakness. A CWE Identifier begins "CWE"
	// followed by a sequence of digits that acts as a unique identifier. For
	// example: CWE-123.
	//
	// OCSF: uid (type string_t, requirement required)
	UID string `json:"uid"`
}
