// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Database describes the OCSF Database object: The database object is
// used for databases which are typically datastore services that contain
// an organized collection of structured and unstructured data or a types
// of data.
//
// OCSF name: database.
type Database struct {
	// CreatedTime is the Created Time. The time when the database was known
	// to have been created.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime int64 `json:"created_time,omitempty"`

	// DataClassification is the Data Classification. The Data Classification
	// object includes information about data classification levels and data
	// category types.
	//
	// OCSF: data_classification (type data_classification, requirement recommended)
	//
	// Deprecated: Use the attribute <code>data_classifications</code> instead
	DataClassification *DataClassification `json:"data_classification,omitempty"`

	// DataClassifications is the Data Classification. A list of Data
	// Classification objects, that include information about data
	// classification levels and data category types, identified by a
	// classifier.
	//
	// OCSF: data_classifications (type []data_classification, requirement recommended)
	DataClassifications []DataClassification `json:"data_classifications,omitempty"`

	// Desc is the Description. The description of the database.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// EmbeddingModel is the Embedding Model. Model used for creating
	// embeddings (if applicable). For example: text-embedding-ada-002 or
	// all-MiniLM-L6-v2.
	//
	// OCSF: embedding_model (type string_t, requirement optional)
	EmbeddingModel string `json:"embedding_model,omitempty"`

	// Groups is the Groups. The group names to which the database belongs.
	//
	// OCSF: groups (type []group, requirement optional)
	Groups []Group `json:"groups,omitempty"`

	// ModifiedTime is the Modified Time. The most recent time when any
	// changes, updates, or modifications were made within the database.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// Name is the Name. The database name, ordinarily as assigned by a
	// database administrator.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Size is the Size. The size of the database in bytes.
	//
	// OCSF: size (type long_t, requirement optional)
	Size int64 `json:"size,omitempty"`

	// Type is the Type. The database type.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The normalized identifier of the database type.
	//
	// OCSF: type_id (type integer_t, requirement required)
	TypeID int `json:"type_id"`

	// UID is the Unique ID. The unique identifier of the database.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
