// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// DataSecurity describes the OCSF Data Security object: The Data
// Security object describes the characteristics, techniques and content
// of a Data Loss Prevention (DLP), Data Loss Detection (DLD), Data
// Classification, or similar tools' finding, alert, or detection
// mechanism(s).
//
// OCSF name: data_security.
type DataSecurity struct {
	// Category is the Category. The name of the data classification category
	// that data matched into, e.g. Financial, Personal, Governmental, etc.
	//
	// OCSF: category (type string_t, requirement optional)
	Category string `json:"category,omitempty"`

	// CategoryID is the Category ID. The normalized identifier of the data
	// classification category.
	//
	// OCSF: category_id (type integer_t, requirement recommended)
	CategoryID int `json:"category_id,omitempty"`

	// ClassifierDetails is the Classifier Details. Describes details about
	// the classifier used for data classification.
	//
	// OCSF: classifier_details (type classifier_details, requirement recommended)
	ClassifierDetails *ClassifierDetails `json:"classifier_details,omitempty"`

	// Confidentiality is the Confidentiality. The file content
	// confidentiality, normalized to the confidentiality_id value. In the
	// case of 'Other', it is defined by the event source.
	//
	// OCSF: confidentiality (type string_t, requirement optional)
	Confidentiality string `json:"confidentiality,omitempty"`

	// ConfidentialityID is the Confidentiality ID. The normalized identifier
	// of the file content confidentiality indicator.
	//
	// OCSF: confidentiality_id (type integer_t, requirement recommended)
	ConfidentialityID int `json:"confidentiality_id,omitempty"`

	// DataLifecycleState is the Data Lifecycle State. The name of the stage
	// or state that the data was in. E.g., Data-at-Rest, Data-in-Transit,
	// etc.
	//
	// OCSF: data_lifecycle_state (type string_t, requirement optional)
	DataLifecycleState string `json:"data_lifecycle_state,omitempty"`

	// DataLifecycleStateID is the Data Lifecycle State ID. The stage or
	// state that the data was in when it was assessed or scanned by a data
	// security tool.
	//
	// OCSF: data_lifecycle_state_id (type integer_t, requirement recommended)
	DataLifecycleStateID int `json:"data_lifecycle_state_id,omitempty"`

	// DetectionPattern is the Detection Pattern. Specific pattern,
	// algorithm, fingerprint, or model used for detection.
	//
	// OCSF: detection_pattern (type string_t, requirement recommended)
	DetectionPattern string `json:"detection_pattern,omitempty"`

	// DetectionSystem is the Detection System. The name of the type of data
	// security tool or system that the finding, detection, or alert
	// originated from. E.g., Endpoint, Secure Email Gateway, etc.
	//
	// OCSF: detection_system (type string_t, requirement optional)
	DetectionSystem string `json:"detection_system,omitempty"`

	// DetectionSystemID is the Detection System ID. The type of data
	// security tool or system that the finding, detection, or alert
	// originated from.
	//
	// OCSF: detection_system_id (type integer_t, requirement recommended)
	DetectionSystemID int `json:"detection_system_id,omitempty"`

	// DiscoveryDetails is the Discovery Details. Details about the data
	// discovered by classification job.
	//
	// OCSF: discovery_details (type []discovery_details, requirement optional)
	DiscoveryDetails []DiscoveryDetails `json:"discovery_details,omitempty"`

	// PatternMatch is the Pattern Match. A text, binary, file name, or
	// datastore that matched against a detection rule.
	//
	// OCSF: pattern_match (type string_t, requirement optional)
	PatternMatch string `json:"pattern_match,omitempty"`

	// Policy is the Policy. Details about the policy that triggered the
	// finding.
	//
	// OCSF: policy (type policy, requirement recommended)
	Policy *Policy `json:"policy,omitempty"`

	// Size is the Size. Size of the data classified.
	//
	// OCSF: size (type long_t, requirement optional)
	Size int64 `json:"size,omitempty"`

	// SrcURL is the Source URL. The source URL pointing towards the full
	// classification job details.
	//
	// OCSF: src_url (type url_t, requirement optional)
	SrcURL string `json:"src_url,omitempty"`

	// Status is the Status. The resultant status of the classification job
	// normalized to the caption of the status_id value. In the case of
	// 'Other', it is defined by the event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusDetails is the Status Details. The contextual description of the
	// status, status_id value.
	//
	// OCSF: status_details (type []string_t, requirement optional)
	StatusDetails []string `json:"status_details,omitempty"`

	// StatusID is the Status ID. The normalized status identifier of the
	// classification job.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Total is the Total. The total count of discovered entities, by the
	// classification job.
	//
	// OCSF: total (type integer_t, requirement optional)
	Total int `json:"total,omitempty"`

	// UID is the Unique ID. The unique identifier of the classification job.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`
}
