// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// DataClassification describes the OCSF Data Classification object: The
// Data Classification object includes information about data
// classification levels and data category types.
//
// OCSF name: data_classification.
type DataClassification struct {
	// Category is the Category. The name of the data classification category
	// that data matched into, e.g. Financial, Personal, Governmental, etc.
	//
	// OCSF: category (type string_t, requirement optional)
	Category string `json:"category,omitempty"`

	// CategoryID is the Category ID. The normalized identifier of the data
	// classification category.
	//
	// OCSF: category_id (type integer_t, requirement recommended)
	CategoryID int `json:"category_id,omitempty"`

	// ClassifierDetails is the Classifier Details. Describes details about
	// the classifier used for data classification.
	//
	// OCSF: classifier_details (type classifier_details, requirement recommended)
	ClassifierDetails *ClassifierDetails `json:"classifier_details,omitempty"`

	// Confidentiality is the Confidentiality. The file content
	// confidentiality, normalized to the confidentiality_id value. In the
	// case of 'Other', it is defined by the event source.
	//
	// OCSF: confidentiality (type string_t, requirement optional)
	Confidentiality string `json:"confidentiality,omitempty"`

	// ConfidentialityID is the Confidentiality ID. The normalized identifier
	// of the file content confidentiality indicator.
	//
	// OCSF: confidentiality_id (type integer_t, requirement recommended)
	ConfidentialityID int `json:"confidentiality_id,omitempty"`

	// DiscoveryDetails is the Discovery Details. Details about the data
	// discovered by classification job.
	//
	// OCSF: discovery_details (type []discovery_details, requirement optional)
	DiscoveryDetails []DiscoveryDetails `json:"discovery_details,omitempty"`

	// Policy is the Policy. Details about the data policy that governs data
	// handling and security measures related to classification.
	//
	// OCSF: policy (type policy, requirement optional)
	Policy *Policy `json:"policy,omitempty"`

	// Size is the Size. Size of the data classified.
	//
	// OCSF: size (type long_t, requirement optional)
	Size int64 `json:"size,omitempty"`

	// SrcURL is the Source URL. The source URL pointing towards the full
	// classification job details.
	//
	// OCSF: src_url (type url_t, requirement optional)
	SrcURL string `json:"src_url,omitempty"`

	// Status is the Status. The resultant status of the classification job
	// normalized to the caption of the status_id value. In the case of
	// 'Other', it is defined by the event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusDetails is the Status Details. The contextual description of the
	// status, status_id value.
	//
	// OCSF: status_details (type []string_t, requirement optional)
	StatusDetails []string `json:"status_details,omitempty"`

	// StatusID is the Status ID. The normalized status identifier of the
	// classification job.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Total is the Total. The total count of discovered entities, by the
	// classification job.
	//
	// OCSF: total (type integer_t, requirement optional)
	Total int `json:"total,omitempty"`

	// UID is the Unique ID. The unique identifier of the classification job.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`
}
