// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// DigitalSignature describes the OCSF Digital Signature object: The
// Digital Signature object contains information about the cryptographic
// mechanism used to verify the authenticity, integrity, and origin of
// the file or application.
//
// OCSF name: digital_signature.
type DigitalSignature struct {
	// Algorithm is the Algorithm. The digital signature algorithm used to
	// create the signature, normalized to the caption of 'algorithm_id'. In
	// the case of 'Other', it is defined by the event source.
	//
	// OCSF: algorithm (type string_t, requirement optional)
	Algorithm string `json:"algorithm,omitempty"`

	// AlgorithmID is the Algorithm ID. The identifier of the normalized
	// digital signature algorithm.
	//
	// OCSF: algorithm_id (type integer_t, requirement required)
	AlgorithmID int `json:"algorithm_id"`

	// Certificate is the Certificate. The certificate object containing
	// information about the digital certificate.
	//
	// OCSF: certificate (type certificate, requirement recommended)
	Certificate *Certificate `json:"certificate,omitempty"`

	// CreatedTime is the Created Time. The time when the digital signature
	// was created.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime *int64 `json:"created_time,omitempty"`

	// DeveloperUID is the Developer UID. The developer ID on the certificate
	// that signed the file.
	//
	// OCSF: developer_uid (type string_t, requirement optional)
	DeveloperUID string `json:"developer_uid,omitempty"`

	// Digest is the Message Digest. The message digest attribute contains
	// the fixed length message hash representation and the corresponding
	// hashing algorithm information.
	//
	// OCSF: digest (type fingerprint, requirement optional)
	Digest *Fingerprint `json:"digest,omitempty"`

	// State is the State. The digital signature state defines the signature
	// state, normalized to the caption of 'state_id'. In the case of
	// 'Other', it is defined by the event source.
	//
	// OCSF: state (type string_t, requirement optional)
	State string `json:"state,omitempty"`

	// StateID is the State ID. The normalized identifier of the signature
	// state.
	//
	// OCSF: state_id (type integer_t, requirement optional)
	StateID *int `json:"state_id,omitempty"`
}
