// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// DNSAnswer describes the OCSF DNS Answer object: The DNS Answer object
// represents a specific response provided by the Domain Name System
// (DNS) when querying for information about a domain or performing a DNS
// operation. It encapsulates the relevant details and data returned by
// the DNS server in response to a query.
//
// OCSF name: dns_answer.
type DNSAnswer struct {
	// Class is the Resource Record Class. The class of DNS data contained in
	// this resource record. See RFC1035. For example: IN.
	//
	// OCSF: class (type string_t, requirement recommended)
	Class string `json:"class,omitempty"`

	// FlagIds is the DNS Header Flags. The list of DNS answer header flag
	// IDs.
	//
	// OCSF: flag_ids (type []integer_t, requirement recommended)
	FlagIds []int `json:"flag_ids,omitempty"`

	// Flags is the DNS Header Flags. The list of DNS answer header flags.
	//
	// OCSF: flags (type []string_t, requirement optional)
	Flags []string `json:"flags,omitempty"`

	// PacketUID is the Packet UID. The DNS packet identifier assigned by the
	// program that generated the query. The identifier is copied to the
	// response.
	//
	// OCSF: packet_uid (type integer_t, requirement recommended)
	PacketUID int `json:"packet_uid,omitempty"`

	// Rdata is the DNS RData. The data describing the DNS resource. The
	// meaning of this data depends on the type and class of the resource
	// record.
	//
	// OCSF: rdata (type string_t, requirement required)
	Rdata string `json:"rdata"`

	// TTL is the TTL. The time interval that the resource record may be
	// cached. Zero value means that the resource record can only be used for
	// the transaction in progress, and should not be cached.
	//
	// OCSF: ttl (type integer_t, requirement recommended)
	TTL int `json:"ttl,omitempty"`

	// Type is the Resource Record Type. The type of data contained in this
	// resource record. See RFC1035. For example: CNAME.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`
}
