// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// EncryptionDetails describes the OCSF Encryption Details object:
// Details about the encryption methodology utilized.
//
// OCSF name: encryption_details.
type EncryptionDetails struct {
	// Algorithm is the Encryption Algorithm. The encryption algorithm used,
	// normalized to the caption of 'algorithm_id
	//
	// OCSF: algorithm (type string_t, requirement optional)
	Algorithm string `json:"algorithm,omitempty"`

	// AlgorithmID is the Encryption Algorithm ID. The encryption algorithm
	// used.
	//
	// OCSF: algorithm_id (type integer_t, requirement recommended)
	AlgorithmID *int `json:"algorithm_id,omitempty"`

	// KeyLength is the Encryption Key Length. The length of the encryption
	// key used.
	//
	// OCSF: key_length (type integer_t, requirement optional)
	KeyLength *int `json:"key_length,omitempty"`

	// KeyUID is the Key UID. The unique identifier of the key used for
	// encryption. For example, AWS KMS Key ARN.
	//
	// OCSF: key_uid (type string_t, requirement optional)
	KeyUID string `json:"key_uid,omitempty"`

	// Type is the Encryption Type. The type of the encryption used.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`
}
