// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// EndpointConnection describes the OCSF Endpoint Connection object: The
// Endpoint Connection object contains information detailing a connection
// attempt to an endpoint.
//
// OCSF name: endpoint_connection.
type EndpointConnection struct {
	// Code is the Response Code. A numerical response status code providing
	// details about the connection.
	//
	// OCSF: code (type integer_t, requirement recommended)
	Code int `json:"code,omitempty"`

	// NetworkEndpoint is the Network Endpoint. Provides characteristics of
	// the network endpoint.
	//
	// OCSF: network_endpoint (type network_endpoint, requirement recommended)
	NetworkEndpoint *NetworkEndpoint `json:"network_endpoint,omitempty"`
}
