// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Entity describes the OCSF Entity object: The Entity object is an
// unordered collection of attributes, with a name and unique identifier.
// It serves as a base object that defines a set of attributes and
// default constraints available in all objects that extend it.
//
// OCSF name: _entity.
type Entity struct {
	// Name is the Name. The name of the entity.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// UID is the Unique ID. The unique identifier of the entity.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
