// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// EnvironmentVariable describes the OCSF Environment Variable object: An
// environment variable.
//
// OCSF name: environment_variable.
type EnvironmentVariable struct {
	// Name is the Name. The name of the environment variable.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Value is the Value. The value of the environment variable.
	//
	// OCSF: value (type string_t, requirement required)
	Value string `json:"value"`
}
