// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Extension describes the OCSF Schema Extension object: The OCSF Schema
// Extension object provides detailed information about the schema
// extension used to construct the event. The schema extensions are
// registered in the extensions.md file.
//
// OCSF name: extension.
type Extension struct {
	// Name is the Name. The schema extension name. For example: dev.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// UID is the Unique ID. The schema extension unique identifier. For
	// example: 999.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The schema extension version. For example:
	// 1.0.0-alpha.2.
	//
	// OCSF: version (type string_t, requirement required)
	Version string `json:"version"`
}
