// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Feature describes the OCSF Feature object: The Feature object provides
// information about the software product feature that generated a
// specific event. It encompasses details related to the capabilities,
// components, user interface (UI) design, and performance upgrades
// associated with the feature.
//
// OCSF name: feature.
type Feature struct {
	// Name is the Name. The name of the feature.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// UID is the Unique ID. The unique identifier of the feature.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The version of the feature.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
