// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// FindingInfo describes the OCSF Finding Information object: The Finding
// Information object describes metadata related to a security finding
// generated by a security tool or system.
//
// OCSF name: finding_info.
type FindingInfo struct {
	// Analytic is the Analytic. The analytic technique used to analyze and
	// derive insights from the data or information that led to the finding
	// or conclusion.
	//
	// OCSF: analytic (type analytic, requirement recommended)
	Analytic *Analytic `json:"analytic,omitempty"`

	// Attacks is the MITRE ATT&CK® Details. The MITRE ATT&CK® technique
	// and associated tactics related to the finding.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []Attack `json:"attacks,omitempty"`

	// CreatedTime is the Created Time. The time when the finding was
	// created.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime int64 `json:"created_time,omitempty"`

	// DataSources is the Data Sources. A list of data sources utilized in
	// generation of the finding.
	//
	// OCSF: data_sources (type []string_t, requirement optional)
	DataSources []string `json:"data_sources,omitempty"`

	// Desc is the Description. The description of the reported finding.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// FirstSeenTime is the First Seen. The time when the finding was first
	// observed. e.g. The time when a vulnerability was first observed. It
	// can differ from the created_time timestamp, which reflects the time
	// this finding was created.
	//
	// OCSF: first_seen_time (type timestamp_t, requirement optional)
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`

	// KillChain is the Kill Chain. The Cyber Kill Chain® provides a
	// detailed description of each phase and its associated activities
	// within the broader context of a cyber attack.
	//
	// OCSF: kill_chain (type []kill_chain_phase, requirement optional)
	KillChain []KillChainPhase `json:"kill_chain,omitempty"`

	// LastSeenTime is the Last Seen. The time when the finding was most
	// recently observed. e.g. The time when a vulnerability was most
	// recently observed. It can differ from the modified_time timestamp,
	// which reflects the time this finding was last modified.
	//
	// OCSF: last_seen_time (type timestamp_t, requirement optional)
	LastSeenTime int64 `json:"last_seen_time,omitempty"`

	// ModifiedTime is the Modified Time. The time when the finding was last
	// modified.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// ProductUID is the Product Identifier. The unique identifier of the
	// product that reported the finding.
	//
	// OCSF: product_uid (type string_t, requirement optional)
	ProductUID string `json:"product_uid,omitempty"`

	// RelatedAnalytics is the Related Analytics. Other analytics related to
	// this finding.
	//
	// OCSF: related_analytics (type []analytic, requirement optional)
	RelatedAnalytics []Analytic `json:"related_analytics,omitempty"`

	// RelatedEvents is the Related Events. Describes events and/or other
	// findings related to the finding as identified by the security product.
	//
	// OCSF: related_events (type []related_event, requirement optional)
	RelatedEvents []RelatedEvent `json:"related_events,omitempty"`

	// SrcURL is the Source URL. The URL pointing to the source of the
	// finding.
	//
	// OCSF: src_url (type url_t, requirement optional)
	SrcURL string `json:"src_url,omitempty"`

	// Title is the Title. A title or a brief phrase summarizing the reported
	// finding.
	//
	// OCSF: title (type string_t, requirement required)
	Title string `json:"title"`

	// Types is the Types. One or more types of the reported finding.
	//
	// OCSF: types (type []string_t, requirement optional)
	Types []string `json:"types,omitempty"`

	// UID is the Unique ID. The unique identifier of the reported finding.
	//
	// OCSF: uid (type string_t, requirement required)
	UID string `json:"uid"`
}
