// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// FirewallRule describes the OCSF Firewall Rule object: The Firewall
// Rule object represents a specific rule within a firewall policy or
// event. It contains information about a rule's configuration,
// properties, and associated actions that define how network traffic is
// handled by the firewall.
//
// OCSF name: firewall_rule.
type FirewallRule struct {
	// Category is the Category. The rule category.
	//
	// OCSF: category (type string_t, requirement optional)
	Category string `json:"category,omitempty"`

	// Condition is the Condition. The rule trigger condition for the rule.
	// For example: SQL_INJECTION.
	//
	// OCSF: condition (type string_t, requirement optional)
	Condition string `json:"condition,omitempty"`

	// Desc is the Description. The description of the rule that generated
	// the event.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Duration is the Duration Milliseconds. The rule response time
	// duration, usually used for challenge completion time.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration *int64 `json:"duration,omitempty"`

	// MatchDetails is the Match Details. The data in a request that rule
	// matched. For example: '["10","and","1"]'.
	//
	// OCSF: match_details (type []string_t, requirement optional)
	MatchDetails []string `json:"match_details,omitempty"`

	// MatchLocation is the Match Location. The location of the matched data
	// in the source which resulted in the triggered firewall rule. For
	// example: HEADER.
	//
	// OCSF: match_location (type string_t, requirement optional)
	MatchLocation string `json:"match_location,omitempty"`

	// Name is the Name. The name of the rule that generated the event.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// RateLimit is the Rate Limit. The rate limit for a rate-based rule.
	//
	// OCSF: rate_limit (type integer_t, requirement optional)
	RateLimit *int `json:"rate_limit,omitempty"`

	// Sensitivity is the Sensitivity. The sensitivity of the firewall rule
	// in the matched event. For example: HIGH.
	//
	// OCSF: sensitivity (type string_t, requirement optional)
	Sensitivity string `json:"sensitivity,omitempty"`

	// Type is the Type. The rule type.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// UID is the Unique ID. The unique identifier of the rule that generated
	// the event.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The rule version. For example: 1.1.
	//
	// OCSF: version (type string_t, requirement optional)
	Version string `json:"version,omitempty"`
}
