// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// GPUInfo describes the OCSF GPU Information object: The GPU information
// object contains attributes describing graphical processing hardware.
//
// OCSF name: gpu_info.
type GPUInfo struct {
	// BusType is the Bus Type. The attachment bus or interface standard,
	// normalized to the caption of the bus_type_id value. In the case of
	// 'Other', it is defined by the event source.
	//
	// OCSF: bus_type (type string_t, requirement optional)
	BusType string `json:"bus_type,omitempty"`

	// BusTypeID is the Bus Type ID. The normalized identifier of the
	// attachment bus or interface standard.
	//
	// OCSF: bus_type_id (type integer_t, requirement optional)
	BusTypeID *int `json:"bus_type_id,omitempty"`

	// Cores is the Cores. The number of processing cores or compute units
	// for the component.
	//
	// OCSF: cores (type integer_t, requirement optional)
	Cores *int `json:"cores,omitempty"`

	// Model is the Model. The model name of the GPU. For example: GeForce
	// RTX A6000, Radeon PRO W7900, or Intel Data Center GPU Max 1550.
	//
	// OCSF: model (type string_t, requirement recommended)
	Model string `json:"model,omitempty"`

	// VendorName is the Vendor Name. The name of the vendor of the GPU. For
	// example: NVIDIA, AMD, or Intel.
	//
	// OCSF: vendor_name (type string_t, requirement recommended)
	VendorName string `json:"vendor_name,omitempty"`

	// VramMode is the VRAM Mode. The video memory attachment mode,
	// indicating how the VRAM hardware is integrated with the system (e.g.,
	// shared or dedicated), normalized to the caption of the vram_mode_id
	// value. For 'Other', the exact attachment mode is defined by the event
	// source.
	//
	// OCSF: vram_mode (type string_t, requirement recommended)
	VramMode string `json:"vram_mode,omitempty"`

	// VramModeID is the VRAM Mode ID. The normalized identifier of the video
	// memory attachment mode.
	//
	// OCSF: vram_mode_id (type integer_t, requirement recommended)
	VramModeID *int `json:"vram_mode_id,omitempty"`

	// VramSize is the VRAM Size. The total amount of installed video RAM.
	//
	// OCSF: vram_size (type integer_t, requirement recommended)
	VramSize *int `json:"vram_size,omitempty"`
}
