// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Group describes the OCSF Group object: The Group object represents a
// collection or association of entities, such as users, policies, or
// devices. It serves as a logical grouping mechanism to organize and
// manage entities with similar characteristics or permissions within a
// system or organization, including but not limited to purposes of
// access control.
//
// OCSF name: group.
type Group struct {
	// Desc is the Description. The group description.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Domain is the Domain. The domain where the group is defined. For
	// example: the LDAP or Active Directory domain.
	//
	// OCSF: domain (type string_t, requirement optional)
	Domain string `json:"domain,omitempty"`

	// Name is the Name. The group name.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Privileges is the Privileges. The group privileges.
	//
	// OCSF: privileges (type []string_t, requirement optional)
	Privileges []string `json:"privileges,omitempty"`

	// Type is the Group Type. The type of the group.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// UID is the Unique ID. The unique identifier of the group. For example,
	// for Windows events this is the security identifier (SID) of the group.
	// Another example, pool id or desktop id that the device belongs to.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// UIDAlt is the Alternate ID. The alternate unique identifier.
	//
	// OCSF: uid_alt (type string_t, requirement optional)
	UIDAlt string `json:"uid_alt,omitempty"`
}
