// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// HTTPRequest describes the OCSF HTTP Request object: The HTTP Request
// object represents the attributes of a request made to a web server. It
// encapsulates the details and metadata associated with an HTTP request,
// including the request method, headers, URL, query parameters, body
// content, and other relevant information.
//
// OCSF name: http_request.
type HTTPRequest struct {
	// Args is the HTTP Arguments. The arguments sent along with the HTTP
	// request.
	//
	// OCSF: args (type string_t, requirement optional)
	Args string `json:"args,omitempty"`

	// BodyLength is the Request Body Length. The actual length of the HTTP
	// request body, in number of bytes, independent of a potentially
	// existing Content-Length header.
	//
	// OCSF: body_length (type integer_t, requirement optional)
	BodyLength *int `json:"body_length,omitempty"`

	// HTTPHeaders is the HTTP Headers. Additional HTTP headers of an HTTP
	// request or response.
	//
	// OCSF: http_headers (type []http_header, requirement recommended)
	HTTPHeaders []HTTPHeader `json:"http_headers,omitempty"`

	// HTTPMethod is the HTTP Method. The HTTP request method indicates the
	// desired action to be performed for a given resource.
	//
	// OCSF: http_method (type string_t, requirement recommended)
	HTTPMethod string `json:"http_method,omitempty"`

	// Length is the Request Length. The length of the entire HTTP request,
	// in number of bytes.
	//
	// OCSF: length (type integer_t, requirement optional)
	Length *int `json:"length,omitempty"`

	// Referrer is the HTTP Referrer. The request header that identifies the
	// address of the previous web page, which is linked to the current web
	// page or resource being requested.
	//
	// OCSF: referrer (type string_t, requirement optional)
	Referrer string `json:"referrer,omitempty"`

	// UID is the Unique ID. The unique identifier of the http request.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`

	// URL is the URL. The URL object that pertains to the request.
	//
	// OCSF: url (type url, requirement recommended)
	URL *URL `json:"url,omitempty"`

	// UserAgent is the HTTP User-Agent. The request header that identifies
	// the operating system and web browser.
	//
	// OCSF: user_agent (type string_t, requirement recommended)
	UserAgent string `json:"user_agent,omitempty"`

	// Version is the HTTP Version. The Hypertext Transfer Protocol (HTTP)
	// version.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`

	// XForwardedFor is the X-Forwarded-For. The X-Forwarded-For header
	// identifying the originating IP address(es) of a client connecting to a
	// web server through an HTTP proxy or a load balancer.
	//
	// OCSF: x_forwarded_for (type []ip_t, requirement optional)
	XForwardedFor []string `json:"x_forwarded_for,omitempty"`
}
