// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// HTTPHeader describes the OCSF HTTP Header object: TThe HTTP Header
// object represents the headers sent in an HTTP request or response.
// HTTP headers are key-value pairs that convey additional information
// about the HTTP message, including details about the content, caching,
// authentication, encoding, and other aspects of the communication.
//
// OCSF name: http_header.
type HTTPHeader struct {
	// Name is the Name. The name of the header
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Value is the Value. The value of the header
	//
	// OCSF: value (type string_t, requirement required)
	Value string `json:"value"`
}
