// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Idp describes the OCSF Identity Provider object: The Identity Provider
// object contains detailed information about a provider responsible for
// creating, maintaining, and managing identity information while
// offering authentication services to applications. An Identity Provider
// (IdP) serves as a trusted authority that verifies the identity of
// users and issues authentication tokens or assertions to enable secure
// access to applications or services.
//
// OCSF name: idp.
type Idp struct {
	// Name is the Name. The name of the identity provider.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// UID is the Unique ID. The unique identifier of the identity provider.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
