// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Image describes the OCSF Image object: The Image object provides a
// description of a specific Virtual Machine (VM) or Container image.
//
// OCSF name: image.
type Image struct {
	// Labels is the Labels. The list of labels associated to the image.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// Name is the Name. The image name. For example: elixir.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Path is the Path. The full path to the image file.
	//
	// OCSF: path (type file_path_t, requirement optional)
	Path string `json:"path,omitempty"`

	// Tag is the Image Tag. The image tag. For example: 1.11-alpine.
	//
	// OCSF: tag (type string_t, requirement optional)
	Tag string `json:"tag,omitempty"`

	// Tags is the Tags. The list of tags; {key:value} pairs associated to
	// the image.
	//
	// OCSF: tags (type []key_value_object, requirement optional)
	Tags []KeyValueObject `json:"tags,omitempty"`

	// UID is the Unique ID. The unique image ID. For example: 77af4d6b9913.
	//
	// OCSF: uid (type string_t, requirement required)
	UID string `json:"uid"`
}
