// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Ja4Fingerprint describes the OCSF JA4+ Fingerprint object: The JA4+
// fingerprint object provides detailed fingerprint information about
// various aspects of network traffic which is both machine and human
// readable.
//
// OCSF name: ja4_fingerprint.
type Ja4Fingerprint struct {
	// SectionA is the JA4 Section A. The 'a' section of the JA4 fingerprint.
	//
	// OCSF: section_a (type string_t, requirement optional)
	SectionA string `json:"section_a,omitempty"`

	// SectionB is the JA4 Section B. The 'b' section of the JA4 fingerprint.
	//
	// OCSF: section_b (type string_t, requirement optional)
	SectionB string `json:"section_b,omitempty"`

	// SectionC is the JA4 Section C. The 'c' section of the JA4 fingerprint.
	//
	// OCSF: section_c (type string_t, requirement optional)
	SectionC string `json:"section_c,omitempty"`

	// SectionD is the JA4 Section D. The 'd' section of the JA4 fingerprint.
	//
	// OCSF: section_d (type string_t, requirement optional)
	SectionD string `json:"section_d,omitempty"`

	// Type is the Type. The JA4+ fingerprint type as defined by FoxIO,
	// normalized to the caption of 'type_id'. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The identifier of the JA4+ fingerprint type.
	//
	// OCSF: type_id (type integer_t, requirement required)
	TypeID int `json:"type_id"`

	// Value is the Value. The JA4+ fingerprint value.
	//
	// OCSF: value (type string_t, requirement required)
	Value string `json:"value"`
}
