// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Job describes the OCSF Job object: The Job object provides information
// about a scheduled job or task, including its name, command line, and
// state. It encompasses attributes that describe the properties and
// status of the scheduled job.
//
// OCSF name: job.
type Job struct {
	// CmdLine is the Command Line. The job command line.
	//
	// OCSF: cmd_line (type string_t, requirement recommended)
	CmdLine string `json:"cmd_line,omitempty"`

	// CreatedTime is the Created Time. The time when the job was created.
	//
	// OCSF: created_time (type timestamp_t, requirement recommended)
	CreatedTime int64 `json:"created_time,omitempty"`

	// Desc is the Description. The description of the job.
	//
	// OCSF: desc (type string_t, requirement recommended)
	Desc string `json:"desc,omitempty"`

	// File is the File. The file that pertains to the job.
	//
	// OCSF: file (type file, requirement optional)
	File *File `json:"file,omitempty"`

	// LastRunTime is the Last Run. The time when the job was last run.
	//
	// OCSF: last_run_time (type timestamp_t, requirement recommended)
	LastRunTime int64 `json:"last_run_time,omitempty"`

	// Name is the Name. The name of the job.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// NextRunTime is the Next Run. The time when the job will next be run.
	//
	// OCSF: next_run_time (type timestamp_t, requirement optional)
	NextRunTime int64 `json:"next_run_time,omitempty"`

	// RunState is the Run State. The run state of the job.
	//
	// OCSF: run_state (type string_t, requirement optional)
	RunState string `json:"run_state,omitempty"`

	// RunStateID is the Run State ID. The run state ID of the job.
	//
	// OCSF: run_state_id (type integer_t, requirement recommended)
	RunStateID int `json:"run_state_id,omitempty"`

	// User is the User. The user that created the job.
	//
	// OCSF: user (type user, requirement optional)
	User *User `json:"user,omitempty"`
}
