// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// KernelDriver describes the OCSF Kernel Extension object: The Kernel
// Extension object describes a kernel driver that has been loaded or
// unloaded into the operating system (OS) kernel.
//
// OCSF name: kernel_driver.
type KernelDriver struct {
	// File is the File. The driver/extension file object.
	//
	// OCSF: file (type file, requirement required)
	File *File `json:"file"`
}
