// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// KeyboardInfo describes the OCSF Keyboard Information object: The
// Keyboard Information object contains details and attributes related to
// a computer or device keyboard. It encompasses information that
// describes the characteristics, capabilities, and configuration of the
// keyboard.
//
// OCSF name: keyboard_info.
type KeyboardInfo struct {
	// FunctionKeys is the Function Keys. The number of function keys on
	// client keyboard.
	//
	// OCSF: function_keys (type integer_t, requirement optional)
	FunctionKeys *int `json:"function_keys,omitempty"`

	// Ime is the IME. The Input Method Editor (IME) file name.
	//
	// OCSF: ime (type string_t, requirement optional)
	Ime string `json:"ime,omitempty"`

	// KeyboardLayout is the Keyboard Layout. The keyboard locale identifier
	// name (e.g., en-US).
	//
	// OCSF: keyboard_layout (type string_t, requirement optional)
	KeyboardLayout string `json:"keyboard_layout,omitempty"`

	// KeyboardSubtype is the Keyboard Subtype. The keyboard numeric code.
	//
	// OCSF: keyboard_subtype (type integer_t, requirement optional)
	KeyboardSubtype *int `json:"keyboard_subtype,omitempty"`

	// KeyboardType is the Keyboard Type. The keyboard type (e.g., xt, ico).
	//
	// OCSF: keyboard_type (type string_t, requirement optional)
	KeyboardType string `json:"keyboard_type,omitempty"`
}
