// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// LDAPPerson describes the OCSF LDAP Person object: The additional LDAP
// attributes that describe a person.
//
// OCSF name: ldap_person.
type LDAPPerson struct {
	// CostCenter is the Cost Center. The cost center associated with the
	// user.
	//
	// OCSF: cost_center (type string_t, requirement optional)
	CostCenter string `json:"cost_center,omitempty"`

	// CreatedTime is the Created Time. The timestamp when the user was
	// created.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime *int64 `json:"created_time,omitempty"`

	// DeletedTime is the Deleted Time. The timestamp when the user was
	// deleted. In Active Directory (AD), when a user is deleted they are
	// moved to a temporary container and then removed after 30 days. So,
	// this field can be populated even after a user is deleted for the next
	// 30 days.
	//
	// OCSF: deleted_time (type timestamp_t, requirement optional)
	DeletedTime *int64 `json:"deleted_time,omitempty"`

	// Department is the Department. The name of the department in which the
	// user works.
	//
	// OCSF: department (type string_t, requirement optional)
	Department string `json:"department,omitempty"`

	// DisplayName is the Display Name. The display name of the LDAP person.
	// According to RFC 2798, this is the preferred name of a person to be
	// used when displaying entries.
	//
	// OCSF: display_name (type string_t, requirement optional)
	DisplayName string `json:"display_name,omitempty"`

	// EmailAddrs is the Email Addresses. A list of additional email
	// addresses for the user.
	//
	// OCSF: email_addrs (type []email_t, requirement optional)
	EmailAddrs []string `json:"email_addrs,omitempty"`

	// EmployeeUID is the Employee ID. The employee identifier assigned to
	// the user by the organization.
	//
	// OCSF: employee_uid (type string_t, requirement optional)
	EmployeeUID string `json:"employee_uid,omitempty"`

	// GivenName is the Given Name. The given or first name of the user.
	//
	// OCSF: given_name (type string_t, requirement optional)
	GivenName string `json:"given_name,omitempty"`

	// HireTime is the Hire Time. The timestamp when the user was or will be
	// hired by the organization.
	//
	// OCSF: hire_time (type timestamp_t, requirement optional)
	HireTime *int64 `json:"hire_time,omitempty"`

	// JobTitle is the Job Title. The user's job title.
	//
	// OCSF: job_title (type string_t, requirement optional)
	JobTitle string `json:"job_title,omitempty"`

	// Labels is the Labels. The labels associated with the user. For example
	// in AD this could be the userType, employeeType. For example: Member,
	// Employee.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// LastLoginTime is the Last Login. The last time when the user logged
	// in.
	//
	// OCSF: last_login_time (type timestamp_t, requirement optional)
	LastLoginTime *int64 `json:"last_login_time,omitempty"`

	// LDAPCn is the LDAP Common Name. The LDAP and X.500 commonName
	// attribute, typically the full name of the person. For example, John
	// Doe.
	//
	// OCSF: ldap_cn (type string_t, requirement optional)
	LDAPCn string `json:"ldap_cn,omitempty"`

	// LDAPDN is the LDAP Distinguished Name. The X.500 Distinguished Name
	// (DN) is a structured string that uniquely identifies an entry, such as
	// a user, in an X.500 directory service For example, cn=John
	// Doe,ou=People,dc=example,dc=com.
	//
	// OCSF: ldap_dn (type string_t, requirement optional)
	LDAPDN string `json:"ldap_dn,omitempty"`

	// LeaveTime is the Leave Time. The timestamp when the user left or will
	// be leaving the organization.
	//
	// OCSF: leave_time (type timestamp_t, requirement optional)
	LeaveTime *int64 `json:"leave_time,omitempty"`

	// Location is the Geo Location. The geographical location associated
	// with a user. This is typically the user's usual work location.
	//
	// OCSF: location (type location, requirement optional)
	Location *Location `json:"location,omitempty"`

	// Manager is the Manager. The user's manager. This helps in
	// understanding an org hierarchy. This should only ever be populated
	// once in an event. I.e. there should not be a manager's manager in an
	// event.
	//
	// OCSF: manager (type user, requirement optional)
	Manager *User `json:"manager,omitempty"`

	// ModifiedTime is the Modified Time. The timestamp when the user entry
	// was last modified.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime *int64 `json:"modified_time,omitempty"`

	// OfficeLocation is the Office Location. The primary office location
	// associated with the user. This could be any string and isn't a
	// specific address. For example, South East Virtual.
	//
	// OCSF: office_location (type string_t, requirement optional)
	OfficeLocation string `json:"office_location,omitempty"`

	// PhoneNumber is the Telephone Number. The telephone number of the user.
	// Corresponds to the LDAP Telephone-Number CN.
	//
	// OCSF: phone_number (type string_t, requirement optional)
	PhoneNumber string `json:"phone_number,omitempty"`

	// Surname is the Surname. The last or family name for the user.
	//
	// OCSF: surname (type string_t, requirement optional)
	Surname string `json:"surname,omitempty"`

	// Tags is the Tags. The list of tags; {key:value} pairs associated to
	// the user.
	//
	// OCSF: tags (type []key_value_object, requirement optional)
	Tags []KeyValueObject `json:"tags,omitempty"`
}
