// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Location describes the OCSF Geo Location object: The Geo Location
// object describes a geographical location, usually associated with an
// IP address. Defined by D3FEND d3f:PhysicalLocation.
//
// OCSF name: location.
type Location struct {
	// City is the City. The name of the city.
	//
	// OCSF: city (type string_t, requirement recommended)
	City string `json:"city,omitempty"`

	// Continent is the Continent. The name of the continent.
	//
	// OCSF: continent (type string_t, requirement recommended)
	Continent string `json:"continent,omitempty"`

	// Coordinates is the Coordinates. A two-element array, containing a
	// longitude/latitude pair. The format conforms with GeoJSON. For
	// example: [-73.983, 40.719].
	//
	// OCSF: coordinates (type []float_t, requirement optional)
	Coordinates []float64 `json:"coordinates,omitempty"`

	// Country is the Country. The ISO 3166-1 Alpha-2 country code. For the
	// complete list of country codes see ISO 3166-1 alpha-2 codes.Note: The
	// two letter country code should be capitalized. For example: US or CA.
	//
	// OCSF: country (type string_t, requirement recommended)
	Country string `json:"country,omitempty"`

	// Desc is the Description. The description of the geographical location.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Geohash is the Geohash. Geohash of the geo-coordinates (latitude and
	// longitude).Geohashing is a geocoding system used to encode geographic
	// coordinates in decimal degrees, to a single string.
	//
	// OCSF: geohash (type string_t, requirement optional)
	Geohash string `json:"geohash,omitempty"`

	// IsOnPremises is the On Premises. The indication of whether the
	// location is on premises.
	//
	// OCSF: is_on_premises (type boolean_t, requirement optional)
	IsOnPremises bool `json:"is_on_premises,omitempty"`

	// Isp is the ISP. The name of the Internet Service Provider (ISP).
	//
	// OCSF: isp (type string_t, requirement optional)
	Isp string `json:"isp,omitempty"`

	// Lat is the Latitude. The geographical Latitude coordinate represented
	// in Decimal Degrees (DD). For example: 42.361145.
	//
	// OCSF: lat (type float_t, requirement optional)
	Lat float64 `json:"lat,omitempty"`

	// Long is the Longitude. The geographical Longitude coordinate
	// represented in Decimal Degrees (DD). For example: -71.057083.
	//
	// OCSF: long (type float_t, requirement optional)
	Long float64 `json:"long,omitempty"`

	// PostalCode is the Postal Code. The postal code of the location.
	//
	// OCSF: postal_code (type string_t, requirement optional)
	PostalCode string `json:"postal_code,omitempty"`

	// Provider is the Provider. The provider of the geographical location
	// data.
	//
	// OCSF: provider (type string_t, requirement optional)
	Provider string `json:"provider,omitempty"`

	// Region is the Region. The alphanumeric code that identifies the
	// principal subdivision (e.g. province or state) of the country. Region
	// codes are defined at ISO 3166-2 and have a limit of three characters.
	// For example, see the region codes for the US.
	//
	// OCSF: region (type string_t, requirement optional)
	Region string `json:"region,omitempty"`
}
