// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Logger describes the OCSF Logger object: The Logger object represents
// the device and product where events are stored with times for receipt
// and transmission. This may be at the source device where the event
// occurred, a remote scanning device, intermediate hops, or the ultimate
// destination.
//
// OCSF name: logger.
type Logger struct {
	// Device is the Device. The device where the events are logged.
	//
	// OCSF: device (type device, requirement recommended)
	Device *Device `json:"device,omitempty"`

	// LogLevel is the Log Level. The audit level at which an event was
	// generated.
	//
	// OCSF: log_level (type string_t, requirement optional)
	LogLevel string `json:"log_level,omitempty"`

	// LogName is the Log Name. The event log name. For example, syslog file
	// name or Windows logging subsystem: Security.
	//
	// OCSF: log_name (type string_t, requirement recommended)
	LogName string `json:"log_name,omitempty"`

	// LogProvider is the Log Provider. The logging provider or logging
	// service that logged the event. For example,
	// Microsoft-Windows-Security-Auditing.
	//
	// OCSF: log_provider (type string_t, requirement recommended)
	LogProvider string `json:"log_provider,omitempty"`

	// LogVersion is the Log Version. The event log schema version that
	// specifies the format of the original event. For example syslog version
	// or Cisco Log Schema Version.
	//
	// OCSF: log_version (type string_t, requirement optional)
	LogVersion string `json:"log_version,omitempty"`

	// LoggedTime is the Logged Time. The time when the logging system
	// collected and logged the event.This attribute is distinct from the
	// event time in that event time typically contain the time extracted
	// from the original event. Most of the time, these two times will be
	// different.
	//
	// OCSF: logged_time (type timestamp_t, requirement recommended)
	LoggedTime int64 `json:"logged_time,omitempty"`

	// Name is the Name. The name of the logging product instance.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Product is the Product. The product logging the event. This may be the
	// event source product, a management server product, a scanning product,
	// a SIEM, etc.
	//
	// OCSF: product (type product, requirement recommended)
	Product *Product `json:"product,omitempty"`

	// TransmitTime is the Transmission Time. The time when the event was
	// transmitted from the logging device to it's next destination.
	//
	// OCSF: transmit_time (type timestamp_t, requirement optional)
	TransmitTime int64 `json:"transmit_time,omitempty"`

	// UID is the Unique ID. The unique identifier of the logging product
	// instance.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The version of the logging product.
	//
	// OCSF: version (type string_t, requirement optional)
	Version string `json:"version,omitempty"`
}
