// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// ManagedEntity describes the OCSF Managed Entity object: The Managed
// Entity object describes the type and version of an entity, such as a
// user, device, or policy. For types in the type_id enum list, an
// associated attribute should be populated. If the type of entity is not
// in the type_id list, information can be put into the data attribute
// and the type attribute should identify the entity.
//
// OCSF name: managed_entity.
type ManagedEntity struct {
	// Data is the Data. The managed entity content as a JSON object.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Device is the Device. An addressable device, computer system or host.
	//
	// OCSF: device (type device, requirement recommended)
	Device *Device `json:"device,omitempty"`

	// Email is the Email. The email object.
	//
	// OCSF: email (type email, requirement recommended)
	Email *Email `json:"email,omitempty"`

	// Group is the Group. The group object associated with an entity such as
	// user, policy, or rule.
	//
	// OCSF: group (type group, requirement recommended)
	Group *Group `json:"group,omitempty"`

	// Name is the Name. The name of the managed entity.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Org is the Organization. Organization and org unit relevant to the
	// event or object.
	//
	// OCSF: org (type organization, requirement recommended)
	Org *Organization `json:"org,omitempty"`

	// Policy is the Policy. Describes details of a managed policy.
	//
	// OCSF: policy (type policy, requirement recommended)
	Policy *Policy `json:"policy,omitempty"`

	// Type is the Type. The managed entity type. For example: policy, user,
	// organizational unit, device.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The type of the Managed Entity. It is
	// recommended to also populate the type attribute with the associated
	// label, or the source specific name if Other.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// UID is the Unique ID. The identifier of the managed entity.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// User is the User. The user that pertains to the event or object.
	//
	// OCSF: user (type user, requirement recommended)
	User *User `json:"user,omitempty"`

	// Version is the Version. The version of the managed entity. For
	// example: 1.2.3.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
