// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Module describes the OCSF Module object: The Module object describes
// the load attributes of a module.
//
// OCSF name: module.
type Module struct {
	// BaseAddress is the Base Address. The memory address where the module
	// was loaded.
	//
	// OCSF: base_address (type string_t, requirement recommended)
	BaseAddress string `json:"base_address,omitempty"`

	// File is the File. The module file object.
	//
	// OCSF: file (type file, requirement recommended)
	File *File `json:"file,omitempty"`

	// FunctionName is the Function Name. The entry-point function of the
	// module. The system calls the entry-point function whenever a process
	// or thread loads or unloads the module.
	//
	// OCSF: function_name (type string_t, requirement optional)
	FunctionName string `json:"function_name,omitempty"`

	// LoadType is the Load Type. The load type, normalized to the caption of
	// the load_type_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: load_type (type string_t, requirement optional)
	LoadType string `json:"load_type,omitempty"`

	// LoadTypeID is the Load Type ID. The normalized identifier for how the
	// module was loaded in memory.
	//
	// OCSF: load_type_id (type integer_t, requirement required)
	LoadTypeID int `json:"load_type_id"`

	// StartAddress is the Start Address. The start address of the execution.
	//
	// OCSF: start_address (type string_t, requirement recommended)
	StartAddress string `json:"start_address,omitempty"`

	// Type is the Type. The module type.
	//
	// OCSF: type (type string_t, requirement recommended)
	Type string `json:"type,omitempty"`
}
