// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// NetworkInterface describes the OCSF Network Interface object: The
// Network Interface object describes the type and associated attributes
// of a physical or virtual network interface.
//
// OCSF name: network_interface.
type NetworkInterface struct {
	// Hostname is the Hostname. The hostname associated with the network
	// interface.
	//
	// OCSF: hostname (type hostname_t, requirement recommended)
	Hostname string `json:"hostname,omitempty"`

	// IP is the IP Address. The IP address associated with the network
	// interface.
	//
	// OCSF: ip (type ip_t, requirement recommended)
	IP string `json:"ip,omitempty"`

	// MAC is the MAC Address. The MAC address of the network interface.
	//
	// OCSF: mac (type mac_t, requirement recommended)
	MAC string `json:"mac,omitempty"`

	// Name is the Name. The name of the network interface.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Namespace is the Namespace. The namespace is useful in merger or
	// acquisition situations. For example, when similar entities exist that
	// you need to keep separate.
	//
	// OCSF: namespace (type string_t, requirement optional)
	Namespace string `json:"namespace,omitempty"`

	// OpenPorts is the Open Ports. The list of open ports on a network
	// interface, including port numbers and associated protocol information.
	//
	// OCSF: open_ports (type []port_info, requirement optional)
	OpenPorts []PortInfo `json:"open_ports,omitempty"`

	// SubnetPrefix is the Subnet Prefix Length. The subnet prefix length
	// determines the number of bits used to represent the network part of
	// the IP address. The remaining bits are reserved for identifying
	// individual hosts within that subnet.
	//
	// OCSF: subnet_prefix (type integer_t, requirement optional)
	SubnetPrefix *int `json:"subnet_prefix,omitempty"`

	// Type is the Type. The type of network interface.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The network interface type identifier.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID *int `json:"type_id,omitempty"`

	// UID is the Unique ID. The unique identifier for the network interface.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`
}
