// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// NetworkConnectionInfo describes the OCSF Network Connection
// Information object: The Network Connection Information object
// describes characteristics of a network connection. Defined by D3FEND
// d3f:NetworkSession.
//
// OCSF name: network_connection_info.
type NetworkConnectionInfo struct {
	// Boundary is the Boundary. The boundary of the connection, normalized
	// to the caption of 'boundary_id'. In the case of 'Other', it is defined
	// by the event source. For cloud connections, this translates to the
	// traffic-boundary(same VPC, through IGW, etc.). For traditional
	// networks, this is described as Local, Internal, or External.
	//
	// OCSF: boundary (type string_t, requirement optional)
	Boundary string `json:"boundary,omitempty"`

	// BoundaryID is the Boundary ID. The normalized identifier of the
	// boundary of the connection. For cloud connections, this translates to
	// the traffic-boundary (same VPC, through IGW, etc.). For traditional
	// networks, this is described as Local, Internal, or External.
	//
	// OCSF: boundary_id (type integer_t, requirement recommended)
	BoundaryID int `json:"boundary_id,omitempty"`

	// Direction is the Direction. The direction of the initiated connection,
	// traffic, or email, normalized to the caption of the direction_id
	// value. In the case of 'Other', it is defined by the event source.
	//
	// OCSF: direction (type string_t, requirement optional)
	Direction string `json:"direction,omitempty"`

	// DirectionID is the Direction ID. The normalized identifier of the
	// direction of the initiated connection, traffic, or email.
	//
	// OCSF: direction_id (type integer_t, requirement required)
	DirectionID int `json:"direction_id"`

	// ProtocolName is the Protocol Name. The TCP/IP protocol name in
	// lowercase, as defined by the Internet Assigned Numbers Authority
	// (IANA). See Protocol Numbers. For example: tcp or udp.
	//
	// OCSF: protocol_name (type string_t, requirement recommended)
	ProtocolName string `json:"protocol_name,omitempty"`

	// ProtocolNum is the Protocol Number. The TCP/IP protocol number, as
	// defined by the Internet Assigned Numbers Authority (IANA). Use -1 if
	// the protocol is not defined by IANA. See Protocol Numbers. For
	// example: 6 for TCP and 17 for UDP.
	//
	// OCSF: protocol_num (type integer_t, requirement recommended)
	ProtocolNum int `json:"protocol_num,omitempty"`

	// ProtocolVer is the IP Version. The Internet Protocol version.
	//
	// OCSF: protocol_ver (type string_t, requirement optional)
	ProtocolVer string `json:"protocol_ver,omitempty"`

	// ProtocolVerID is the IP Version ID. The Internet Protocol version
	// identifier.
	//
	// OCSF: protocol_ver_id (type integer_t, requirement recommended)
	ProtocolVerID int `json:"protocol_ver_id,omitempty"`

	// Session is the Session. The authenticated user or service session.
	//
	// OCSF: session (type session, requirement optional)
	Session *Session `json:"session,omitempty"`

	// TCPFlags is the TCP Flags. The network connection TCP header flags
	// (i.e., control bits).
	//
	// OCSF: tcp_flags (type integer_t, requirement optional)
	TCPFlags int `json:"tcp_flags,omitempty"`

	// UID is the Connection UID. The unique identifier of the connection.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
