// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// NetworkProxy describes the OCSF Network Proxy Endpoint object: The
// network proxy endpoint object describes a proxy server, which acts as
// an intermediary between a client requesting a resource and the server
// providing that resource. Defined by D3FEND d3f:ProxyServer.
//
// OCSF name: network_proxy.
type NetworkProxy struct {
	// AgentList is the Agent List. A list of agent objects associated with a
	// device, endpoint, or resource.
	//
	// OCSF: agent_list (type []agent, requirement optional)
	AgentList []Agent `json:"agent_list,omitempty"`

	// AutonomousSystem is the Autonomous System. The Autonomous System
	// details associated with an IP address.
	//
	// OCSF: autonomous_system (type autonomous_system, requirement optional)
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`

	// Container is the Container. The information describing an instance of
	// a container. A container is a prepackaged, portable system image that
	// runs isolated on an existing system using a container runtime like
	// containerd.
	//
	// OCSF: container (type container, requirement recommended)
	Container *Container `json:"container,omitempty"`

	// Domain is the Domain. The name of the domain.
	//
	// OCSF: domain (type string_t, requirement optional)
	Domain string `json:"domain,omitempty"`

	// Hostname is the Hostname. The fully qualified name of the endpoint.
	//
	// OCSF: hostname (type hostname_t, requirement recommended)
	Hostname string `json:"hostname,omitempty"`

	// HwInfo is the Hardware Info. The endpoint hardware information.
	//
	// OCSF: hw_info (type device_hw_info, requirement optional)
	HwInfo *DeviceHwInfo `json:"hw_info,omitempty"`

	// InstanceUID is the Instance ID. The unique identifier of a VM
	// instance.
	//
	// OCSF: instance_uid (type string_t, requirement recommended)
	InstanceUID string `json:"instance_uid,omitempty"`

	// InterfaceName is the Network Interface Name. The name of the network
	// interface (e.g. eth2).
	//
	// OCSF: interface_name (type string_t, requirement recommended)
	InterfaceName string `json:"interface_name,omitempty"`

	// InterfaceUID is the Network Interface ID. The unique identifier of the
	// network interface.
	//
	// OCSF: interface_uid (type string_t, requirement recommended)
	InterfaceUID string `json:"interface_uid,omitempty"`

	// IntermediateIps is the Intermediate IP Addresses. The intermediate IP
	// Addresses. For example, the IP addresses in the HTTP X-Forwarded-For
	// header.
	//
	// OCSF: intermediate_ips (type []ip_t, requirement optional)
	IntermediateIps []string `json:"intermediate_ips,omitempty"`

	// IP is the IP Address. The IP address of the endpoint, in either IPv4
	// or IPv6 format.
	//
	// OCSF: ip (type ip_t, requirement recommended)
	IP string `json:"ip,omitempty"`

	// Location is the Geo Location. The geographical location of the
	// endpoint.
	//
	// OCSF: location (type location, requirement optional)
	Location *Location `json:"location,omitempty"`

	// MAC is the MAC Address. The Media Access Control (MAC) address of the
	// endpoint.
	//
	// OCSF: mac (type mac_t, requirement optional)
	MAC string `json:"mac,omitempty"`

	// Name is the Name. The short name of the endpoint.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// NamespacePID is the Namespace PID. If running under a process
	// namespace (such as in a container), the process identifier within that
	// process namespace.
	//
	// OCSF: namespace_pid (type integer_t, requirement recommended)
	NamespacePID int `json:"namespace_pid,omitempty"`

	// OS is the OS. The endpoint operating system.
	//
	// OCSF: os (type os, requirement optional)
	OS *OS `json:"os,omitempty"`

	// Owner is the Owner. The identity of the service or user account that
	// owns the endpoint or was last logged into it.
	//
	// OCSF: owner (type user, requirement recommended)
	Owner *User `json:"owner,omitempty"`

	// Port is the Port. The port used for communication within the network
	// connection.
	//
	// OCSF: port (type port_t, requirement recommended)
	Port int `json:"port,omitempty"`

	// ProxyEndpoint is the Proxy Endpoint. The network proxy information
	// pertaining to a specific endpoint. This can be used to describe
	// information pertaining to network address translation (NAT).
	//
	// OCSF: proxy_endpoint (type network_proxy, requirement optional)
	ProxyEndpoint *NetworkProxy `json:"proxy_endpoint,omitempty"`

	// SubnetUID is the Subnet UID. The unique identifier of a virtual
	// subnet.
	//
	// OCSF: subnet_uid (type string_t, requirement optional)
	SubnetUID string `json:"subnet_uid,omitempty"`

	// SvcName is the Service Name. The service name in service-to-service
	// connections. For example, AWS VPC logs the pkt-src-aws-service and
	// pkt-dst-aws-service fields identify the connection is coming from or
	// going to an AWS service.
	//
	// OCSF: svc_name (type string_t, requirement recommended)
	SvcName string `json:"svc_name,omitempty"`

	// Type is the Type. The network endpoint type. For example: unknown,
	// server, desktop, laptop, tablet, mobile, virtual, browser, or other.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The network endpoint type ID.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// UID is the Unique ID. The unique identifier of the endpoint.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// VLANUID is the VLAN. The Virtual LAN identifier.
	//
	// OCSF: vlan_uid (type string_t, requirement optional)
	VLANUID string `json:"vlan_uid,omitempty"`

	// VpcUID is the VPC UID. The unique identifier of the Virtual Private
	// Cloud (VPC).
	//
	// OCSF: vpc_uid (type string_t, requirement optional)
	VpcUID string `json:"vpc_uid,omitempty"`

	// Zone is the Network Zone. The network zone or LAN segment.
	//
	// OCSF: zone (type string_t, requirement optional)
	Zone string `json:"zone,omitempty"`
}
