// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Observation describes the OCSF Observation object: A record of an
// observed value or event that captures the timing and frequency of its
// occurrence. Used to track when values/events were first detected, last
// detected, and their total occurrence count.
//
// OCSF name: observation.
type Observation struct {
	// Count is the Count. Integer representing the total number of times
	// this specific value/event was observed across all occurrences. Helps
	// establish prevalence and patterns.
	//
	// OCSF: count (type integer_t, requirement recommended)
	Count int `json:"count,omitempty"`

	// Timespan is the Time Span. The time window when the value or event was
	// first observed. It is used to analyze activity patterns, detect
	// trends, or correlate events within a specific timeframe.
	//
	// OCSF: timespan (type timespan, requirement recommended)
	Timespan *Timespan `json:"timespan,omitempty"`

	// Value is the Value. The specific value, event, indicator or data point
	// that was observed and recorded. This is the core piece of information
	// being tracked.
	//
	// OCSF: value (type string_t, requirement required)
	Value string `json:"value"`
}
