// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Observable describes the OCSF Observable object: The observable object
// is a pivot element that contains related information found in many
// places in the event.
//
// OCSF name: observable.
type Observable struct {
	// Name is the Name. The full name of the observable attribute. The name
	// is a pointer/reference to an attribute within the event data. For
	// example: file.name.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Reputation is the Reputation Scores. Contains the original and
	// normalized reputation scores.
	//
	// OCSF: reputation (type reputation, requirement optional)
	Reputation *Reputation `json:"reputation,omitempty"`

	// Type is the Type. The observable value type name.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The observable value type identifier.
	//
	// OCSF: type_id (type integer_t, requirement required)
	TypeID int `json:"type_id"`

	// Value is the Value. The value associated with the observable
	// attribute. The meaning of the value depends on the observable type.If
	// the name refers to a scalar attribute, then the value is the value of
	// the attribute.If the name refers to an object attribute, then the
	// value is not populated.
	//
	// OCSF: value (type string_t, requirement optional)
	Value string `json:"value,omitempty"`
}
