// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Organization describes the OCSF Organization object: The Organization
// object describes characteristics of an organization or company and its
// division if any.
//
// OCSF name: organization.
type Organization struct {
	// Name is the Name. The name of the organization. For example, Widget,
	// Inc.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// OuName is the Org Unit Name. The name of the organizational unit,
	// within an organization. For example, Finance, IT, R&D
	//
	// OCSF: ou_name (type string_t, requirement recommended)
	OuName string `json:"ou_name,omitempty"`

	// OuUID is the Org Unit ID. The alternate identifier for an entity's
	// unique identifier. For example, its Active Directory OU DN or AWS OU
	// ID.
	//
	// OCSF: ou_uid (type string_t, requirement optional)
	OuUID string `json:"ou_uid,omitempty"`

	// UID is the Unique ID. The unique identifier of the organization. For
	// example, its Active Directory or AWS Org ID.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
