// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Osint describes the OCSF OSINT object: The OSINT (Open Source
// Intelligence) object contains details related to an indicator such as
// the indicator itself, related indicators, geolocation, registrar
// information, subdomains, analyst commentary, and other contextual
// information. This information can be used to further enrich a
// detection or finding by providing decisioning support to other
// analysts and engineers.
//
// OCSF name: osint.
type Osint struct {
	// Answers is the Related DNS Answers. Any pertinent DNS answers
	// information related to an indicator or OSINT analysis.
	//
	// OCSF: answers (type []dns_answer, requirement optional)
	Answers []DNSAnswer `json:"answers,omitempty"`

	// Attacks is the MITRE ATT&CK® Details. MITRE ATT&CK Tactics,
	// Techniques, and/or Procedures (TTPs) pertinent to an indicator or
	// OSINT analysis.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []Attack `json:"attacks,omitempty"`

	// AutonomousSystem is the Autonomous System. Any pertinent autonomous
	// system information related to an indicator or OSINT analysis.
	//
	// OCSF: autonomous_system (type autonomous_system, requirement optional)
	AutonomousSystem *AutonomousSystem `json:"autonomous_system,omitempty"`

	// Comment is the Analyst Comments. Analyst commentary or source
	// commentary about an indicator or OSINT analysis.
	//
	// OCSF: comment (type string_t, requirement optional)
	Comment string `json:"comment,omitempty"`

	// Confidence is the Confidence. The confidence of an indicator being
	// malicious and/or pertinent, normalized to the caption of the
	// confidence_id value. In the case of 'Other', it is defined by the
	// event source or analyst.
	//
	// OCSF: confidence (type string_t, requirement optional)
	Confidence string `json:"confidence,omitempty"`

	// ConfidenceID is the Confidence Id. The normalized confidence refers to
	// the accuracy of collected information related to the OSINT or how
	// pertinent an indicator or analysis is to a specific event or finding.
	// A low confidence means that the information collected or analysis
	// conducted lacked detail or is not accurate enough to qualify an
	// indicator as fully malicious.
	//
	// OCSF: confidence_id (type integer_t, requirement recommended)
	ConfidenceID int `json:"confidence_id,omitempty"`

	// Email is the Related Email. Any email information pertinent to an
	// indicator or OSINT analysis.
	//
	// OCSF: email (type email, requirement optional)
	Email *Email `json:"email,omitempty"`

	// EmailAuth is the Related Email Authentication. Any email
	// authentication information pertinent to an indicator or OSINT
	// analysis.
	//
	// OCSF: email_auth (type email_auth, requirement optional)
	EmailAuth *EmailAuth `json:"email_auth,omitempty"`

	// KillChain is the Kill Chain. Lockheed Martin Kill Chain Phases
	// pertinent to an indicator or OSINT analysis.
	//
	// OCSF: kill_chain (type []kill_chain_phase, requirement optional)
	KillChain []KillChainPhase `json:"kill_chain,omitempty"`

	// Location is the Geo Location. Any pertinent geolocation information
	// related to an indicator or OSINT analysis.
	//
	// OCSF: location (type location, requirement optional)
	Location *Location `json:"location,omitempty"`

	// Name is the Name. The name of the entity.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Signatures is the Related Digital Signatures. Any digital signatures
	// or hashes related to an indicator or OSINT analysis.
	//
	// OCSF: signatures (type []digital_signature, requirement optional)
	Signatures []DigitalSignature `json:"signatures,omitempty"`

	// SrcURL is the Source URL. The source URL of an indicator or OSINT
	// analysis, e.g., a URL back to a TIP, report, or otherwise.
	//
	// OCSF: src_url (type url_t, requirement optional)
	SrcURL string `json:"src_url,omitempty"`

	// Subdomains is the Related Subdomains. Any pertinent subdomain
	// information - such as those generated by a Domain Generation Algorithm
	// - related to an indicator or OSINT analysis.
	//
	// OCSF: subdomains (type []string_t, requirement optional)
	Subdomains []string `json:"subdomains,omitempty"`

	// Tlp is the Traffic Light Protocol. The Traffic Light Protocol was
	// created to facilitate greater sharing of potentially sensitive
	// information and more effective collaboration. TLP provides a simple
	// and intuitive schema for indicating with whom potentially sensitive
	// information can be shared.
	//
	// OCSF: tlp (type string_t, requirement recommended)
	Tlp string `json:"tlp,omitempty"`

	// Type is the Type. The OSINT indicator type.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Indicator Type ID. The OSINT indicator type ID.
	//
	// OCSF: type_id (type integer_t, requirement required)
	TypeID int `json:"type_id"`

	// UID is the Unique ID. The unique identifier of the entity.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Value is the Indicator. The actual indicator value in scope, e.g., a
	// SHA-256 hash hexdigest or a domain name.
	//
	// OCSF: value (type string_t, requirement required)
	Value string `json:"value"`

	// VendorName is the Vendor Name. The vendor name of a tool which
	// generates intelligence or provides indicators.
	//
	// OCSF: vendor_name (type string_t, requirement optional)
	VendorName string `json:"vendor_name,omitempty"`

	// Vulnerabilities is the Related Vulnerabilities. Any vulnerabilities
	// related to an indicator or OSINT analysis.
	//
	// OCSF: vulnerabilities (type []vulnerability, requirement optional)
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty"`

	// Whois is the WHOIS. Any pertinent WHOIS information related to an
	// indicator or OSINT analysis.
	//
	// OCSF: whois (type whois, requirement optional)
	Whois *Whois `json:"whois,omitempty"`
}
