// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Parameter describes the OCSF Parameter object: The Parameter object
// provides details regarding a parameter of a a function.
//
// OCSF name: parameter.
type Parameter struct {
	// Name is the Name. The parameter name.
	//
	// OCSF: name (type string_t, requirement optional)
	Name string `json:"name,omitempty"`

	// PostValue is the Post-Value. The parameter value after function
	// execution.
	//
	// OCSF: post_value (type string_t, requirement optional)
	PostValue string `json:"post_value,omitempty"`

	// PreValue is the Pre-Value. The parameter value before function
	// execution.
	//
	// OCSF: pre_value (type string_t, requirement optional)
	PreValue string `json:"pre_value,omitempty"`
}
