// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Policy describes the OCSF Policy object: The Policy object describes
// the policies that are applicable. Policy attributes provide
// traceability to the operational state of the security product at the
// time that the event was captured, facilitating forensics,
// troubleshooting, and policy tuning/adjustments.
//
// OCSF name: policy.
type Policy struct {
	// Desc is the Description. The description of the policy.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Group is the Group. The policy group.
	//
	// OCSF: group (type group, requirement optional)
	Group *Group `json:"group,omitempty"`

	// IsApplied is the Applied. A determination if the content of a policy
	// was applied to a target or request, or not.
	//
	// OCSF: is_applied (type boolean_t, requirement recommended)
	IsApplied bool `json:"is_applied,omitempty"`

	// Name is the Name. The policy name. For example: IAM Policy.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// UID is the Unique ID. A unique identifier of the policy instance.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The policy version number.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
