// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// PrivilegeInfo describes the OCSF Privilege Info object: The Privilege
// Info object describes information about a specific privilege, action,
// or permission. It captures the privilege name, type, usage status, and
// when it was last used.
//
// OCSF name: privilege_info.
type PrivilegeInfo struct {
	// IsUnused is the Is Unused. Indicates whether the privilege is unused
	// within the analysis timeframe.
	//
	// OCSF: is_unused (type boolean_t, requirement optional)
	IsUnused *bool `json:"is_unused,omitempty"`

	// LastUsedTime is the Last Used Time. The most recent time this
	// privilege was used.
	//
	// OCSF: last_used_time (type timestamp_t, requirement optional)
	LastUsedTime *int64 `json:"last_used_time,omitempty"`

	// Name is the Name. The name of the privilege, action, or permission.
	// Examples: GetObject, CreateStoreImageTask (AWS);
	// Microsoft.Storage/storageAccounts/read (Azure); storage.objects.get
	// (GCP).
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Type is the Type. The type or category of the privilege, normalized to
	// the caption of the type_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The normalized type of the privilege.
	//
	// OCSF: type_id (type integer_t, requirement optional)
	TypeID *int `json:"type_id,omitempty"`
}
