// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// PrivilegeAttackInfo describes the OCSF Privilege Attack Info object:
// The Privilege Attack Info object groups privileges by the potential
// attack they could enable. It maps specific privileges to MITRE ATT&CK
// techniques, helping identify security risks associated with granted
// permissions.
//
// OCSF name: privilege_attack_info.
type PrivilegeAttackInfo struct {
	// Attack is the MITRE ATT&CK® Details. The MITRE ATT&CK technique that
	// these privileges could enable.
	//
	// OCSF: attack (type attack, requirement required)
	Attack *Attack `json:"attack"`

	// PrivilegeInfoList is the Privilege Info List. The list of privilege
	// information objects, where each element describes a specific privilege
	// that could enable the associated attack technique.
	//
	// OCSF: privilege_info_list (type []privilege_info, requirement required)
	PrivilegeInfoList []PrivilegeInfo `json:"privilege_info_list"`
}
