// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// QueryInfo describes the OCSF Query Information object: The query info
// object holds information related to data access within a datastore. To
// access, manipulate, delete, or retrieve data from a datastore, a query
// must be written using a specific syntax.
//
// OCSF name: query_info.
type QueryInfo struct {
	// Bytes is the Total Bytes. The size of the data returned from the
	// query.
	//
	// OCSF: bytes (type long_t, requirement optional)
	Bytes *int64 `json:"bytes,omitempty"`

	// Data is the Data. The data returned from the query execution.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Name is the Name. The query name for a saved or scheduled query.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// QueryString is the Query String. A string representing the query code
	// being run. For example: SELECT * FROM my_table
	//
	// OCSF: query_string (type string_t, requirement required)
	QueryString string `json:"query_string"`

	// QueryTime is the Query Time. The time when the query was run.
	//
	// OCSF: query_time (type timestamp_t, requirement optional)
	QueryTime *int64 `json:"query_time,omitempty"`

	// UID is the Unique ID. The unique identifier of the query.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
