// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// Request describes the OCSF Request Elements object: The Request
// Elements object describes characteristics of an API request.
//
// OCSF name: request.
type Request struct {
	// Containers is the Containers. When working with containerized
	// applications, the set of containers which write to the standard the
	// output of a particular logging driver. For example, this may be the
	// set of containers involved in handling api requests and responses for
	// a containerized application.
	//
	// OCSF: containers (type []container, requirement optional)
	Containers []Container `json:"containers,omitempty"`

	// Data is the Data. The additional data that is associated with the api
	// request.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Flags is the Flags. The communication flags that are associated with
	// the api request.
	//
	// OCSF: flags (type []string_t, requirement optional)
	Flags []string `json:"flags,omitempty"`

	// UID is the Unique ID. The unique request identifier.
	//
	// OCSF: uid (type string_t, requirement required)
	UID string `json:"uid"`
}
