// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// Resource describes the OCSF Resource object: The Resource object
// contains attributes that provide information about a particular
// resource. It serves as a base object, offering attributes that help
// identify and classify the resource effectively.
//
// OCSF name: _resource.
type Resource struct {
	// Data is the Data. Additional data describing the resource.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// DataClassification is the Data Classification. The Data Classification
	// object includes information about data classification levels and data
	// category types.
	//
	// OCSF: data_classification (type data_classification, requirement recommended)
	DataClassification *DataClassification `json:"data_classification,omitempty"`

	// Labels is the Labels. The list of labels/tags associated to a
	// resource.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// Name is the Name. The name of the resource.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Type is the Type. The resource type as defined by the event source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// UID is the Unique ID. The unique identifier of the resource.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
