// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Sbom describes the OCSF Software Bill of Materials object: The
// Software Bill of Materials object describes characteristics of a
// generated SBOM.
//
// OCSF name: sbom.
type Sbom struct {
	// CreatedTime is the Created Time. The time when the SBOM was created.
	//
	// OCSF: created_time (type timestamp_t, requirement recommended)
	CreatedTime int64 `json:"created_time,omitempty"`

	// Package is the Software Package. The software package or library that
	// is being discovered or inventoried by an SBOM.
	//
	// OCSF: package (type package, requirement required)
	Package *Package `json:"package"`

	// Product is the Product. Details about the upstream product that
	// generated the SBOM e.g. cdxgen or Syft.
	//
	// OCSF: product (type product, requirement recommended)
	Product *Product `json:"product,omitempty"`

	// SoftwareComponents is the Software Components. The list of software
	// components used in the software package.
	//
	// OCSF: software_components (type []software_component, requirement required)
	SoftwareComponents []SoftwareComponent `json:"software_components"`

	// Type is the Type. The type of SBOM, normalized to the caption of the
	// type_id value. In the case of 'Other', it is defined by the source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The type of SBOM.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// UID is the SBOM ID. A unique identifier for the SBOM or the SBOM
	// generation by a source tool, such as the SPDX
	// metadata.component.bom-ref.
	//
	// OCSF: uid (type string_t, requirement optional)
	UID string `json:"uid,omitempty"`

	// Version is the Version. The specification (spec) version of the
	// particular SBOM, e.g., 1.6.
	//
	// OCSF: version (type string_t, requirement optional)
	Version string `json:"version,omitempty"`
}
