// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// Scim describes the OCSF SCIM object: The System for Cross-domain
// Identity Management (SCIM) Configuration object provides a structured
// set of attributes related to SCIM protocols used for identity
// provisioning and management across cloud-based platforms. It
// standardizes user and group provisioning details, enabling identity
// synchronization and lifecycle management with compatible Identity
// Providers (IdPs) and applications. SCIM is defined in RFC-7634
//
// OCSF name: scim.
type Scim struct {
	// AuthProtocol is the Auth Protocol. The authorization protocol as
	// defined by the caption of auth_protocol_id. In the case of Other, it
	// is defined by the event source.
	//
	// OCSF: auth_protocol (type string_t, requirement optional)
	AuthProtocol string `json:"auth_protocol,omitempty"`

	// AuthProtocolID is the Auth Protocol ID. The normalized identifier of
	// the authorization protocol used by the SCIM resource.
	//
	// OCSF: auth_protocol_id (type integer_t, requirement optional)
	AuthProtocolID *int `json:"auth_protocol_id,omitempty"`

	// CreatedTime is the Created Time. When the SCIM resource was added to
	// the service provider.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime *int64 `json:"created_time,omitempty"`

	// ErrorMessage is the Last Error Message. Message or code associated
	// with the last encountered error.
	//
	// OCSF: error_message (type string_t, requirement optional)
	ErrorMessage string `json:"error_message,omitempty"`

	// IsGroupProvisioningEnabled is the SCIM Group Provisioning Enabled.
	// Indicates whether the SCIM resource is configured to provision groups,
	// automatically or otherwise.
	//
	// OCSF: is_group_provisioning_enabled (type boolean_t, requirement optional)
	IsGroupProvisioningEnabled *bool `json:"is_group_provisioning_enabled,omitempty"`

	// IsUserProvisioningEnabled is the SCIM User Provisioning Enabled.
	// Indicates whether the SCIM resource is configured to provision users,
	// automatically or otherwise.
	//
	// OCSF: is_user_provisioning_enabled (type boolean_t, requirement optional)
	IsUserProvisioningEnabled *bool `json:"is_user_provisioning_enabled,omitempty"`

	// LastRunTime is the Last Sync Time. Timestamp of the most recent
	// successful synchronization.
	//
	// OCSF: last_run_time (type timestamp_t, requirement optional)
	LastRunTime *int64 `json:"last_run_time,omitempty"`

	// ModifiedTime is the Modified Time. The most recent time when the SCIM
	// resource was updated at the service provider.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime *int64 `json:"modified_time,omitempty"`

	// Name is the Name. The name of the SCIM resource.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// ProtocolName is the Supported Protocol. The supported protocol for the
	// SCIM resource. E.g., SAML, OIDC, or OAuth2.
	//
	// OCSF: protocol_name (type string_t, requirement optional)
	ProtocolName string `json:"protocol_name,omitempty"`

	// RateLimit is the Rate Limit. Maximum number of requests allowed by the
	// SCIM resource within a specified time frame to avoid throttling.
	//
	// OCSF: rate_limit (type integer_t, requirement optional)
	RateLimit *int `json:"rate_limit,omitempty"`

	// ScimGroupSchema is the SCIM Group Schema. SCIM provides a schema for
	// representing groups, identified using the following schema URI:
	// urn:ietf:params:scim:schemas:core:2.0:Group as defined in RFC-7634.
	// This attribute will capture key-value pairs for the scheme implemented
	// in a SCIM resource.
	//
	// OCSF: scim_group_schema (type json_t, requirement recommended)
	ScimGroupSchema json.RawMessage `json:"scim_group_schema,omitempty"`

	// ScimUserSchema is the SCIM User Schema. SCIM provides a resource type
	// for user resources. The core schema for user is identified using the
	// following schema URI: urn:ietf:params:scim:schemas:core:2.0:User as
	// defined in RFC-7634. his attribute will capture key-value pairs for
	// the scheme implemented in a SCIM resource. This object is inclusive of
	// both the basic and Enterprise User Schema Extension.
	//
	// OCSF: scim_user_schema (type json_t, requirement recommended)
	ScimUserSchema json.RawMessage `json:"scim_user_schema,omitempty"`

	// State is the State. The provisioning state of the SCIM resource,
	// normalized to the caption of the state_id value. In the case of Other,
	// it is defined by the event source.
	//
	// OCSF: state (type string_t, requirement optional)
	State string `json:"state,omitempty"`

	// StateID is the State ID. The normalized state ID of the SCIM resource
	// to reflect its activation status.
	//
	// OCSF: state_id (type integer_t, requirement optional)
	StateID *int `json:"state_id,omitempty"`

	// UID is the Unique ID. A unique identifier for a SCIM resource as
	// defined by the service provider.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// UIDAlt is the External ID. A String that is an identifier for the
	// resource as defined by the provisioning client. The externalId may
	// simplify identification of a resource between the provisioning client
	// and the service provider by allowing the client to use a filter to
	// locate the resource with an identifier from the provisioning domain,
	// obviating the need to store a local mapping between the provisioning
	// domain's identifier of the resource and the identifier used by the
	// service provider.
	//
	// OCSF: uid_alt (type string_t, requirement optional)
	UIDAlt string `json:"uid_alt,omitempty"`

	// URLString is the SCIM Endpoint URL. The primary URL for SCIM API
	// requests.
	//
	// OCSF: url_string (type url_t, requirement optional)
	URLString string `json:"url_string,omitempty"`

	// VendorName is the Service Provider. Name of the vendor or service
	// provider implementing SCIM. E.g., Okta, Auth0, Microsoft.
	//
	// OCSF: vendor_name (type string_t, requirement optional)
	VendorName string `json:"vendor_name,omitempty"`

	// Version is the SCIM Version. SCIM protocol version supported e.g.,
	// SCIM 2.0.
	//
	// OCSF: version (type string_t, requirement recommended)
	Version string `json:"version,omitempty"`
}
