// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// ServicePrivilegeAnalysis describes the OCSF Service Privilege Analysis
// object: The Service Privilege Analysis object describes privilege
// analysis results for a single cloud service or resource namespace. It
// provides metrics on privilege usage, counts by type, and mappings to
// potential attack techniques.
//
// OCSF name: service_privilege_analysis.
type ServicePrivilegeAnalysis struct {
	// AllPrivilegesUnused is the All Privileges Unused. Indicates whether
	// all privileges within this service are unused.
	//
	// OCSF: all_privileges_unused (type boolean_t, requirement optional)
	AllPrivilegesUnused bool `json:"all_privileges_unused,omitempty"`

	// AnalyzedPrivilegesCount is the Analyzed Privileges Count. The total
	// count of privileges analyzed within this service.
	//
	// OCSF: analyzed_privileges_count (type integer_t, requirement optional)
	AnalyzedPrivilegesCount int `json:"analyzed_privileges_count,omitempty"`

	// ExecuteCount is the Execute Privilege Count. The count of execute-type
	// privileges within this service.
	//
	// OCSF: execute_count (type integer_t, requirement optional)
	ExecuteCount int `json:"execute_count,omitempty"`

	// LastUsedTime is the Last Used Time. The most recent time any privilege
	// in this service was used.
	//
	// OCSF: last_used_time (type timestamp_t, requirement optional)
	LastUsedTime int64 `json:"last_used_time,omitempty"`

	// Name is the Name. The service or namespace identifier. Examples: s3,
	// ec2 (AWS); Microsoft.Storage (Azure); storage (GCP).
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// PrivilegeAttackInfoList is the Privilege Attack Info List. The list of
	// privilege-to-attack mappings for this service.
	//
	// OCSF: privilege_attack_info_list (type []privilege_attack_info, requirement optional)
	PrivilegeAttackInfoList []PrivilegeAttackInfo `json:"privilege_attack_info_list,omitempty"`

	// ReadCount is the Read Privilege Count. The count of read-type
	// privileges within this service.
	//
	// OCSF: read_count (type integer_t, requirement optional)
	ReadCount int `json:"read_count,omitempty"`

	// UnusedPrivilegesCount is the Unused Privileges Count. The count of
	// unused privileges within this service.
	//
	// OCSF: unused_privileges_count (type integer_t, requirement optional)
	UnusedPrivilegesCount int `json:"unused_privileges_count,omitempty"`

	// WriteCount is the Write Privilege Count. The count of write-type
	// privileges within this service.
	//
	// OCSF: write_count (type integer_t, requirement optional)
	WriteCount int `json:"write_count,omitempty"`
}
