// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// SoftwareComponent describes the OCSF Software Component object: The
// Software Component object describes characteristics of a software
// component within a software package.
//
// OCSF name: software_component.
type SoftwareComponent struct {
	// Author is the Author. The author(s) who published the software
	// component.
	//
	// OCSF: author (type string_t, requirement recommended)
	Author string `json:"author,omitempty"`

	// Hash is the Hash. Cryptographic hash to identify the binary instance
	// of a software component.
	//
	// OCSF: hash (type fingerprint, requirement optional)
	Hash *Fingerprint `json:"hash,omitempty"`

	// License is the Software License. The software license applied to this
	// component.
	//
	// OCSF: license (type string_t, requirement optional)
	License string `json:"license,omitempty"`

	// Name is the Name. The software component name.
	//
	// OCSF: name (type string_t, requirement required)
	Name string `json:"name"`

	// Purl is the Package URL. The Package URL (PURL) to identify the
	// software component. This is a URL that uniquely identifies the
	// component, including the component's name, version, and type. The URL
	// is used to locate and retrieve the component's metadata and content.
	//
	// OCSF: purl (type string_t, requirement recommended)
	Purl string `json:"purl,omitempty"`

	// RelatedComponent is the Related Component. The package URL (PURL) of
	// the component that this software component has a relationship with.
	//
	// OCSF: related_component (type string_t, requirement recommended)
	RelatedComponent string `json:"related_component,omitempty"`

	// Relationship is the Relationship. The relationship between two
	// software components, normalized to the caption of the relationship_id
	// value. In the case of 'Other', it is defined by the source.
	//
	// OCSF: relationship (type string_t, requirement optional)
	Relationship string `json:"relationship,omitempty"`

	// RelationshipID is the Relationship ID. The normalized identifier of
	// the relationship between two software components.
	//
	// OCSF: relationship_id (type integer_t, requirement recommended)
	RelationshipID int `json:"relationship_id,omitempty"`

	// Type is the Type. The type of software component, normalized to the
	// caption of the type_id value. In the case of 'Other', it is defined by
	// the source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The type of software component.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`

	// Version is the Version. The software component version.
	//
	// OCSF: version (type string_t, requirement required)
	Version string `json:"version"`
}
