// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Ticket describes the OCSF Ticket object: The Ticket object represents
// ticket in the customer's systems like Salesforce, jira etc.
//
// OCSF name: ticket.
type Ticket struct {
	// SrcURL is the Source URL. The url of a ticket in the ticket system.
	//
	// OCSF: src_url (type url_t, requirement recommended)
	SrcURL string `json:"src_url,omitempty"`

	// Title is the Title. The title of the ticket.
	//
	// OCSF: title (type string_t, requirement optional)
	Title string `json:"title,omitempty"`

	// Type is the Ticket Type. The linked ticket type determines whether the
	// ticket is internal or in an external ticketing system.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Ticket Type ID. The normalized identifier for the ticket
	// type.
	//
	// OCSF: type_id (type integer_t, requirement optional)
	TypeID int `json:"type_id,omitempty"`

	// UID is the Unique ID. Unique ticket identifier like ticket id.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`
}
