// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// Timespan describes the OCSF Time Span object: The Time Span object
// represents different time period durations. If a timespan is
// fractional, i.e. crosses one period, e.g. a week and 3 days, more than
// one may be populated since each member is of integral type. In that
// case type_id if present should be set to Other.A timespan may also be
// defined by its time interval boundaries, start_time and end_time.
//
// OCSF name: timespan.
type Timespan struct {
	// Duration is the Duration Milliseconds. The duration of the time span
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement recommended)
	Duration int64 `json:"duration,omitempty"`

	// DurationDays is the Duration Days. The duration of the time span in
	// days.
	//
	// OCSF: duration_days (type integer_t, requirement recommended)
	DurationDays int `json:"duration_days,omitempty"`

	// DurationHours is the Duration Hours. The duration of the time span in
	// hours.
	//
	// OCSF: duration_hours (type integer_t, requirement recommended)
	DurationHours int `json:"duration_hours,omitempty"`

	// DurationMins is the Duration Minutes. The duration of the time span in
	// minutes.
	//
	// OCSF: duration_mins (type integer_t, requirement recommended)
	DurationMins int `json:"duration_mins,omitempty"`

	// DurationMonths is the Duration Months. The duration of the time span
	// in months.
	//
	// OCSF: duration_months (type integer_t, requirement recommended)
	DurationMonths int `json:"duration_months,omitempty"`

	// DurationSecs is the Duration Seconds. The duration of the time span in
	// seconds.
	//
	// OCSF: duration_secs (type integer_t, requirement recommended)
	DurationSecs int `json:"duration_secs,omitempty"`

	// DurationWeeks is the Duration Weeks. The duration of the time span in
	// weeks.
	//
	// OCSF: duration_weeks (type integer_t, requirement recommended)
	DurationWeeks int `json:"duration_weeks,omitempty"`

	// DurationYears is the Duration Years. The duration of the time span in
	// years.
	//
	// OCSF: duration_years (type integer_t, requirement recommended)
	DurationYears int `json:"duration_years,omitempty"`

	// EndTime is the End Time. The end time or conclusion of the timespan's
	// interval.
	//
	// OCSF: end_time (type timestamp_t, requirement recommended)
	EndTime int64 `json:"end_time,omitempty"`

	// StartTime is the Start Time. The start time or beginning of the
	// timespan's interval.
	//
	// OCSF: start_time (type timestamp_t, requirement recommended)
	StartTime int64 `json:"start_time,omitempty"`

	// Type is the Time Span Type. The type of time span duration the object
	// represents.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Time Span Type ID. The normalized identifier for the
	// time span duration type.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID int `json:"type_id,omitempty"`
}
