// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// TLSExtension describes the OCSF TLS Extension object: The TLS
// Extension object describes additional attributes that extend the base
// Transport Layer Security (TLS) object.
//
// OCSF name: tls_extension.
type TLSExtension struct {
	// Data is the Data. The data contains information specific to the
	// particular extension type.
	//
	// OCSF: data (type json_t, requirement recommended)
	Data json.RawMessage `json:"data,omitempty"`

	// Type is the Type. The TLS extension type. For example: Server Name.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The TLS extension type identifier. See The
	// Transport Layer Security (TLS) extension page.
	//
	// OCSF: type_id (type integer_t, requirement required)
	TypeID int `json:"type_id"`
}
