// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

// User describes the OCSF User object: The User object describes the
// characteristics of a user/person or a security principal.
//
// OCSF name: user.
type User struct {
	// Account is the Account. The user's account or the account associated
	// with the user.
	//
	// OCSF: account (type account, requirement optional)
	Account *Account `json:"account,omitempty"`

	// CredentialUID is the User Credential ID. The unique identifier of the
	// user's credential. For example, AWS Access Key ID.
	//
	// OCSF: credential_uid (type string_t, requirement optional)
	//
	// Deprecated: Use <code>programmatic_credentials</code> instead.
	CredentialUID string `json:"credential_uid,omitempty"`

	// DisplayName is the Display Name. The display name of the user, as
	// reported by the product.
	//
	// OCSF: display_name (type string_t, requirement optional)
	DisplayName string `json:"display_name,omitempty"`

	// Domain is the Domain. The domain where the user is defined. For
	// example: the LDAP or Active Directory domain.
	//
	// OCSF: domain (type string_t, requirement optional)
	Domain string `json:"domain,omitempty"`

	// EmailAddr is the Email Address. The user's primary email address.
	//
	// OCSF: email_addr (type email_t, requirement optional)
	EmailAddr string `json:"email_addr,omitempty"`

	// ForwardAddr is the Forwarding Address. The user's forwarding email
	// address.
	//
	// OCSF: forward_addr (type email_t, requirement optional)
	ForwardAddr string `json:"forward_addr,omitempty"`

	// FullName is the Full Name. The full name of the user, as reported by
	// the product.
	//
	// OCSF: full_name (type string_t, requirement optional)
	FullName string `json:"full_name,omitempty"`

	// Groups is the Groups. The administrative groups to which the user
	// belongs.
	//
	// OCSF: groups (type []group, requirement optional)
	Groups []Group `json:"groups,omitempty"`

	// HasMFA is the MFA Assigned. The user has a multi-factor or
	// secondary-factor device assigned.
	//
	// OCSF: has_mfa (type boolean_t, requirement recommended)
	HasMFA *bool `json:"has_mfa,omitempty"`

	// LDAPPerson is the LDAP Person. The additional LDAP attributes that
	// describe a person.
	//
	// OCSF: ldap_person (type ldap_person, requirement optional)
	LDAPPerson *LDAPPerson `json:"ldap_person,omitempty"`

	// Name is the Name. The username. For example, janedoe1.
	//
	// OCSF: name (type username_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Org is the Organization. Organization and org unit related to the
	// user.
	//
	// OCSF: org (type organization, requirement optional)
	Org *Organization `json:"org,omitempty"`

	// PhoneNumber is the Telephone Number. The telephone number of the user.
	//
	// OCSF: phone_number (type string_t, requirement optional)
	PhoneNumber string `json:"phone_number,omitempty"`

	// ProgrammaticCredentials is the Programmatic Credentials. Details about
	// the programmatic credential (API keys, access tokens, certificates,
	// etc) associated to the user.
	//
	// OCSF: programmatic_credentials (type []programmatic_credential, requirement optional)
	ProgrammaticCredentials []ProgrammaticCredential `json:"programmatic_credentials,omitempty"`

	// RiskLevel is the Risk Level. The risk level, normalized to the caption
	// of the risk_level_id value.
	//
	// OCSF: risk_level (type string_t, requirement optional)
	RiskLevel string `json:"risk_level,omitempty"`

	// RiskLevelID is the Risk Level ID. The normalized risk level id.
	//
	// OCSF: risk_level_id (type integer_t, requirement optional)
	RiskLevelID *int `json:"risk_level_id,omitempty"`

	// RiskScore is the Risk Score. The risk score as reported by the event
	// source.
	//
	// OCSF: risk_score (type integer_t, requirement optional)
	RiskScore *int `json:"risk_score,omitempty"`

	// Type is the Type. The type of the user. For example, System, AWS IAM
	// User, etc.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// TypeID is the Type ID. The account type identifier.
	//
	// OCSF: type_id (type integer_t, requirement recommended)
	TypeID *int `json:"type_id,omitempty"`

	// UID is the Unique ID. The unique user identifier. For example, the
	// Windows user SID, ActiveDirectory DN or AWS user ARN.
	//
	// OCSF: uid (type string_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// UIDAlt is the Alternate ID. The alternate user identifier. For
	// example, the Active Directory user GUID or AWS user Principal ID.
	//
	// OCSF: uid_alt (type string_t, requirement optional)
	UIDAlt string `json:"uid_alt,omitempty"`
}
