// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package objects

import (
	"encoding/json"
)

// WebResource describes the OCSF Web Resource object: The Web Resource
// object describes characteristics of a web resource that was affected
// by the activity/event.
//
// OCSF name: web_resource.
type WebResource struct {
	// CreatedTime is the Created Time. The time when the resource was
	// created.
	//
	// OCSF: created_time (type timestamp_t, requirement optional)
	CreatedTime int64 `json:"created_time,omitempty"`

	// Data is the Data. Details of the web resource, e.g, file details,
	// search results or application-defined resource.
	//
	// OCSF: data (type json_t, requirement optional)
	Data json.RawMessage `json:"data,omitempty"`

	// DataClassification is the Data Classification. The Data Classification
	// object includes information about data classification levels and data
	// category types.
	//
	// OCSF: data_classification (type data_classification, requirement recommended)
	//
	// Deprecated: Use the attribute <code>data_classifications</code> instead
	DataClassification *DataClassification `json:"data_classification,omitempty"`

	// DataClassifications is the Data Classification. A list of Data
	// Classification objects, that include information about data
	// classification levels and data category types, identified by a
	// classifier.
	//
	// OCSF: data_classifications (type []data_classification, requirement recommended)
	DataClassifications []DataClassification `json:"data_classifications,omitempty"`

	// Desc is the Description. Description of the web resource.
	//
	// OCSF: desc (type string_t, requirement optional)
	Desc string `json:"desc,omitempty"`

	// Labels is the Labels. The list of labels associated to the resource.
	//
	// OCSF: labels (type []string_t, requirement optional)
	Labels []string `json:"labels,omitempty"`

	// ModifiedTime is the Modified Time. The time when the resource was last
	// modified.
	//
	// OCSF: modified_time (type timestamp_t, requirement optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// Name is the Name. The name of the web resource.
	//
	// OCSF: name (type string_t, requirement recommended)
	Name string `json:"name,omitempty"`

	// Tags is the Tags. The list of tags; {key:value} pairs associated to
	// the resource.
	//
	// OCSF: tags (type []key_value_object, requirement optional)
	Tags []KeyValueObject `json:"tags,omitempty"`

	// Type is the Type. The web resource type as defined by the event
	// source.
	//
	// OCSF: type (type string_t, requirement optional)
	Type string `json:"type,omitempty"`

	// UID is the Unique ID. The unique identifier of the web resource.
	//
	// OCSF: uid (type resource_uid_t, requirement recommended)
	UID string `json:"uid,omitempty"`

	// UIDAlt is the Alternate ID. The alternative unique identifier of the
	// resource.
	//
	// OCSF: uid_alt (type resource_uid_t, requirement optional)
	UIDAlt string `json:"uid_alt,omitempty"`

	// URLString is the URL String. The URL pointing towards the source of
	// the web resource.
	//
	// OCSF: url_string (type url_t, requirement recommended)
	URLString string `json:"url_string,omitempty"`
}
