// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package application

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// ScanActivity describes the OCSF Scan Activity event class: Scan events
// report the start, completion, and results of a scan job. The scan
// event includes the number of items that were scanned and the number of
// detections that were resolved.
//
// OCSF name: scan_activity. class_uid: 6007.
type ScanActivity struct {
	// Action is the Action. The normalized caption of action_id.
	//
	// OCSF: action (type string_t, requirement optional)
	Action string `json:"action,omitempty"`

	// ActionID is the Action ID. The action taken by a control or other
	// policy-based system leading to an outcome or disposition. An unknown
	// action may still correspond to a known disposition. Refer to
	// disposition_id for the outcome of the action.
	//
	// OCSF: action_id (type integer_t, requirement recommended)
	ActionID int `json:"action_id,omitempty"`

	// ActivityID is the Activity ID. The normalized identifier of the
	// activity that triggered the event.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The event activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. The actor object describes details about the
	// user/role/process that was the source of the activity. Note that this
	// is not the threat actor of a campaign but may be part of a campaign.
	//
	// OCSF: actor (type actor, requirement optional)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// Attacks is the MITRE ATT&CK® and ATLAS™ Details. An array of MITRE
	// ATT&CK® objects describing identified tactics, techniques &
	// sub-techniques. The objects are compatible with MITRE ATLAS™
	// tactics, techniques & sub-techniques.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []objects.Attack `json:"attacks,omitempty"`

	// Authorizations is the Authorization Information. Provides details
	// about an authorization, such as authorization outcome, and any
	// associated policies related to the activity/event.
	//
	// OCSF: authorizations (type []authorization, requirement optional)
	Authorizations []objects.Authorization `json:"authorizations,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event or finding was created.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// CommandUID is the Command UID. The command identifier that is
	// associated with this scan event. This ID uniquely identifies the
	// proactive scan command, e.g., if remotely initiated.
	//
	// OCSF: command_uid (type string_t, requirement recommended)
	CommandUID string `json:"command_uid,omitempty"`

	// Confidence is the Confidence. The confidence, normalized to the
	// caption of the confidence_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: confidence (type string_t, requirement optional)
	Confidence string `json:"confidence,omitempty"`

	// ConfidenceID is the Confidence ID. The normalized confidence refers to
	// the accuracy of the rule that created the finding. A rule with a low
	// confidence means that the finding scope is wide and may create finding
	// reports that may not be malicious in nature.
	//
	// OCSF: confidence_id (type integer_t, requirement recommended)
	ConfidenceID int `json:"confidence_id,omitempty"`

	// ConfidenceScore is the Confidence Score. The confidence score as
	// reported by the event source.
	//
	// OCSF: confidence_score (type integer_t, requirement optional)
	ConfidenceScore int `json:"confidence_score,omitempty"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Device is the Device. An addressable device, computer system or host.
	//
	// OCSF: device (type device, requirement recommended)
	Device *objects.Device `json:"device,omitempty"`

	// Disposition is the Disposition. The disposition name, normalized to
	// the caption of the disposition_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: disposition (type string_t, requirement optional)
	Disposition string `json:"disposition,omitempty"`

	// DispositionID is the Disposition ID. Describes the outcome or action
	// taken by a security control, such as access control checks, malware
	// detections or various types of policy violations.
	//
	// OCSF: disposition_id (type integer_t, requirement recommended)
	DispositionID int `json:"disposition_id,omitempty"`

	// Duration is the Duration Milliseconds. The duration of the scan
	//
	// OCSF: duration (type long_t, requirement recommended)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The end time of the scan job.
	//
	// OCSF: end_time (type timestamp_t, requirement recommended)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// FirewallRule is the Firewall Rule. The firewall rule that pertains to
	// the control that triggered the event, if applicable.
	//
	// OCSF: firewall_rule (type firewall_rule, requirement optional)
	FirewallRule *objects.FirewallRule `json:"firewall_rule,omitempty"`

	// IsAlert is the Alert. Indicates that the event is considered to be an
	// alertable signal. Should be set to true if disposition_id = Alert
	// among other dispositions, and/or risk_level_id or severity_id of the
	// event is elevated. Not all control events will be alertable, for
	// example if disposition_id = Exonerated or disposition_id = Allowed.
	//
	// OCSF: is_alert (type boolean_t, requirement recommended)
	IsAlert bool `json:"is_alert,omitempty"`

	// Malware is the Malware. A list of Malware objects, describing details
	// about the identified malware.
	//
	// OCSF: malware (type []malware, requirement optional)
	Malware []objects.Malware `json:"malware,omitempty"`

	// MalwareScanInfo is the Malware Scan Info. Describes details about the
	// scan job that identified malware on the target system.
	//
	// OCSF: malware_scan_info (type malware_scan_info, requirement optional)
	MalwareScanInfo *objects.MalwareScanInfo `json:"malware_scan_info,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// NumDetections is the Detections. The number of detections.
	//
	// OCSF: num_detections (type integer_t, requirement recommended)
	NumDetections int `json:"num_detections,omitempty"`

	// NumFiles is the Scanned Files. The number of files scanned.
	//
	// OCSF: num_files (type integer_t, requirement recommended)
	NumFiles int `json:"num_files,omitempty"`

	// NumFolders is the Scanned Folders. The number of folders scanned.
	//
	// OCSF: num_folders (type integer_t, requirement recommended)
	NumFolders int `json:"num_folders,omitempty"`

	// NumNetworkItems is the Scanned Network Items. The number of network
	// items scanned.
	//
	// OCSF: num_network_items (type integer_t, requirement recommended)
	NumNetworkItems int `json:"num_network_items,omitempty"`

	// NumProcesses is the Scanned Processes. The number of processes
	// scanned.
	//
	// OCSF: num_processes (type integer_t, requirement recommended)
	NumProcesses int `json:"num_processes,omitempty"`

	// NumRegistryItems is the Scanned Registry Items. The number of registry
	// items scanned.
	//
	// OCSF: num_registry_items (type integer_t, requirement recommended)
	NumRegistryItems int `json:"num_registry_items,omitempty"`

	// NumResolutions is the Resolutions. The number of items that were
	// resolved.
	//
	// OCSF: num_resolutions (type integer_t, requirement recommended)
	NumResolutions int `json:"num_resolutions,omitempty"`

	// NumSkippedItems is the Skipped. The number of skipped items.
	//
	// OCSF: num_skipped_items (type integer_t, requirement recommended)
	NumSkippedItems int `json:"num_skipped_items,omitempty"`

	// NumTrustedItems is the Trusted. The number of trusted items.
	//
	// OCSF: num_trusted_items (type integer_t, requirement recommended)
	NumTrustedItems int `json:"num_trusted_items,omitempty"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// Policy is the Policy. The policy associated with this Scan event;
	// required if the scan was initiated by a policy.
	//
	// OCSF: policy (type policy, requirement recommended)
	Policy *objects.Policy `json:"policy,omitempty"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// RawDataHash is the Raw Data Hash. The hash, which describes the
	// content of the raw_data field.
	//
	// OCSF: raw_data_hash (type fingerprint, requirement optional)
	RawDataHash *objects.Fingerprint `json:"raw_data_hash,omitempty"`

	// RawDataSize is the Raw Data Size. The size of the raw data which was
	// transformed into an OCSF event, in bytes.
	//
	// OCSF: raw_data_size (type long_t, requirement optional)
	RawDataSize int64 `json:"raw_data_size,omitempty"`

	// RiskDetails is the Risk Details. Describes the risk associated with
	// the finding.
	//
	// OCSF: risk_details (type string_t, requirement optional)
	RiskDetails string `json:"risk_details,omitempty"`

	// RiskLevel is the Risk Level. The risk level, normalized to the caption
	// of the risk_level_id value.
	//
	// OCSF: risk_level (type string_t, requirement optional)
	RiskLevel string `json:"risk_level,omitempty"`

	// RiskLevelID is the Risk Level ID. The normalized risk level id.
	//
	// OCSF: risk_level_id (type integer_t, requirement optional)
	RiskLevelID int `json:"risk_level_id,omitempty"`

	// RiskScore is the Risk Score. The risk score as reported by the event
	// source.
	//
	// OCSF: risk_score (type integer_t, requirement optional)
	RiskScore int `json:"risk_score,omitempty"`

	// Scan is the Scan. The Scan object describes characteristics of the
	// scan job.
	//
	// OCSF: scan (type scan, requirement required)
	Scan *objects.Scan `json:"scan"`

	// ScheduleUID is the Schedule UID. The unique identifier of the schedule
	// associated with a scan job.
	//
	// OCSF: schedule_uid (type string_t, requirement recommended)
	ScheduleUID string `json:"schedule_uid,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// StartTime is the Start Time. The start time of the scan job.
	//
	// OCSF: start_time (type timestamp_t, requirement recommended)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The event status, normalized to the caption of
	// the status_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized identifier of the event
	// status.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// Total is the Total. The total number of items that were scanned; zero
	// if no items were scanned.
	//
	// OCSF: total (type integer_t, requirement recommended)
	Total int `json:"total,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for Scan Activity (6007).
// Computed as CategoryUID*1000 + class identifier within the category.
func (ScanActivity) OCSFClassUID() int { return 6007 }

// OCSFClassName returns the OCSF class_name for Scan Activity.
func (ScanActivity) OCSFClassName() string { return "Scan Activity" }

// OCSFCategoryUID returns the OCSF category_uid for the application category (6).
func (ScanActivity) OCSFCategoryUID() int { return 6 }

// OCSFCategoryName returns the OCSF category_name (application).
func (ScanActivity) OCSFCategoryName() string { return "application" }

// Validate checks the required-field rules for ScanActivity.
// Returns the first violation found, or nil if all required fields are present.
func (e ScanActivity) Validate() error {
	if e.Cloud == nil {
		return &ocsf.ValidationError{ClassUID: 6007, Field: "cloud", Rule: "required", Reason: "required field is missing"}
	}
	if e.Metadata == nil {
		return &ocsf.ValidationError{ClassUID: 6007, Field: "metadata", Rule: "required", Reason: "required field is missing"}
	}
	if len(e.Osint) == 0 {
		return &ocsf.ValidationError{ClassUID: 6007, Field: "osint", Rule: "required", Reason: "required field is missing"}
	}
	if e.Scan == nil {
		return &ocsf.ValidationError{ClassUID: 6007, Field: "scan", Rule: "required", Reason: "required field is missing"}
	}
	switch e.ActionID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "action_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Action != "" {
		switch e.ActionID {
		case 0:
			if e.Action != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Action != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Action != "Denied" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Action != "Observed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Action != "Modified" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ActivityID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.ActivityName != "" {
		switch e.ActivityID {
		case 0:
			if e.ActivityName != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.ActivityName != "Started" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.ActivityName != "Completed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.ActivityName != "Cancelled" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.ActivityName != "Duration Violation" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.ActivityName != "Pause Violation" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.ActivityName != "Error" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.ActivityName != "Paused" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.ActivityName != "Resumed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.ActivityName != "Restarted" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.ActivityName != "Delayed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.ActivityName != "Unlock" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.ActivityName != "Share" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 13:
			if e.ActivityName != "Unshare" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 14:
			if e.ActivityName != "Open" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 15:
			if e.ActivityName != "Sync" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 16:
			if e.ActivityName != "Unsync" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 17:
			if e.ActivityName != "Access Check" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ConfidenceID {
	case 0, 1, 2, 3, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "confidence_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Confidence != "" {
		switch e.ConfidenceID {
		case 0:
			if e.Confidence != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Confidence != "Low" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Confidence != "Medium" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Confidence != "High" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.DispositionID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Disposition != "" {
		switch e.DispositionID {
		case 0:
			if e.Disposition != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Disposition != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Disposition != "Blocked" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Disposition != "Quarantined" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Disposition != "Isolated" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Disposition != "Deleted" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Disposition != "Dropped" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.Disposition != "Custom Action" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.Disposition != "Approved" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.Disposition != "Restored" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.Disposition != "Exonerated" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.Disposition != "Corrected" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.Disposition != "Partially Corrected" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 13:
			if e.Disposition != "Uncorrected" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 14:
			if e.Disposition != "Delayed" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 15:
			if e.Disposition != "Detected" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 16:
			if e.Disposition != "No Action" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 17:
			if e.Disposition != "Logged" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 18:
			if e.Disposition != "Tagged" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 19:
			if e.Disposition != "Alert" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 20:
			if e.Disposition != "Count" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 21:
			if e.Disposition != "Reset" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 22:
			if e.Disposition != "Captcha" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 23:
			if e.Disposition != "Challenge" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 24:
			if e.Disposition != "Access Revoked" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 25:
			if e.Disposition != "Rejected" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 26:
			if e.Disposition != "Unauthorized" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 27:
			if e.Disposition != "Error" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.RiskLevelID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.RiskLevel != "" {
		switch e.RiskLevelID {
		case 0:
			if e.RiskLevel != "Info" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.RiskLevel != "Low" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.RiskLevel != "Medium" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.RiskLevel != "High" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.RiskLevel != "Critical" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.SeverityID {
	case 0, 1, 2, 3, 4, 5, 6, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "severity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Severity != "" {
		switch e.SeverityID {
		case 0:
			if e.Severity != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Severity != "Informational" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Severity != "Low" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Severity != "Medium" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Severity != "High" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Severity != "Critical" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Severity != "Fatal" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.StatusID {
	case 0, 1, 2, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 6007, Field: "status_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Status != "" {
		switch e.StatusID {
		case 0:
			if e.Status != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Status != "Success" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Status != "Failure" {
				return &ocsf.ValidationError{ClassUID: 6007, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	return nil
}

func init() {
	ocsf.RegisterClass(6007, func() ocsf.Event { return &ScanActivity{} })
}
