// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package iam

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// Authentication describes the OCSF Authentication event class:
// Authentication events report authentication session activities,
// including user attempts to log on or log off, regardless of success,
// as well as other key stages within the authentication process. These
// events are typically generated by authentication services, such as
// Kerberos, OIDC, or SAML, and may include information about the user,
// the authentication method used, and the status of the authentication
// attempt.
//
// OCSF name: authentication. class_uid: 3002.
type Authentication struct {
	// AccountSwitchType is the Account Switch Type. The account switch
	// method, normalized to the caption of the account_switch_type_id value.
	// In the case of 'Other', it is defined by the event source.
	//
	// OCSF: account_switch_type (type string_t, requirement recommended)
	AccountSwitchType string `json:"account_switch_type,omitempty"`

	// AccountSwitchTypeID is the Account Switch Type ID. The normalized
	// identifier of the account switch method.
	//
	// OCSF: account_switch_type_id (type integer_t, requirement recommended)
	AccountSwitchTypeID int `json:"account_switch_type_id,omitempty"`

	// Action is the Action. The normalized caption of action_id.
	//
	// OCSF: action (type string_t, requirement optional)
	Action string `json:"action,omitempty"`

	// ActionID is the Action ID. The action taken by a control or other
	// policy-based system leading to an outcome or disposition. An unknown
	// action may still correspond to a known disposition. Refer to
	// disposition_id for the outcome of the action.
	//
	// OCSF: action_id (type integer_t, requirement recommended)
	ActionID int `json:"action_id,omitempty"`

	// ActivityID is the Activity ID. The normalized identifier of the
	// activity that triggered the event.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The event activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. The actor object describes details about the
	// user/role/process that was the source of the activity. Note that this
	// is not the threat actor of a campaign but may be part of a campaign.
	//
	// OCSF: actor (type actor, requirement recommended)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// Attacks is the MITRE ATT&CK® and ATLAS™ Details. An array of MITRE
	// ATT&CK® objects describing identified tactics, techniques &
	// sub-techniques. The objects are compatible with MITRE ATLAS™
	// tactics, techniques & sub-techniques.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []objects.Attack `json:"attacks,omitempty"`

	// AuthFactors is the Authentication Factors. Describes a category of
	// methods used for identity verification in an authentication attempt.
	//
	// OCSF: auth_factors (type []auth_factor, requirement optional)
	AuthFactors []objects.AuthFactor `json:"auth_factors,omitempty"`

	// AuthProtocol is the Auth Protocol. The authentication protocol as
	// defined by the caption of auth_protocol_id. In the case of Other, it
	// is defined by the event source.
	//
	// OCSF: auth_protocol (type string_t, requirement recommended)
	AuthProtocol string `json:"auth_protocol,omitempty"`

	// AuthProtocolID is the Auth Protocol ID. The normalized identifier of
	// the authentication protocol used to create the user session.
	//
	// OCSF: auth_protocol_id (type integer_t, requirement recommended)
	AuthProtocolID int `json:"auth_protocol_id,omitempty"`

	// AuthenticationToken is the Authentication Token. The authentication
	// token, ticket, or assertion, e.g. Kerberos, OIDC, SAML.
	//
	// OCSF: authentication_token (type authentication_token, requirement optional)
	AuthenticationToken *objects.AuthenticationToken `json:"authentication_token,omitempty"`

	// Authorizations is the Authorization Information. Provides details
	// about an authorization, such as authorization outcome, and any
	// associated policies related to the activity/event.
	//
	// OCSF: authorizations (type []authorization, requirement optional)
	Authorizations []objects.Authorization `json:"authorizations,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// Certificate is the Certificate. The certificate associated with the
	// authentication or pre-authentication (Kerberos).
	//
	// OCSF: certificate (type certificate, requirement recommended)
	Certificate *objects.Certificate `json:"certificate,omitempty"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event or finding was created.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Confidence is the Confidence. The confidence, normalized to the
	// caption of the confidence_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: confidence (type string_t, requirement optional)
	Confidence string `json:"confidence,omitempty"`

	// ConfidenceID is the Confidence ID. The normalized confidence refers to
	// the accuracy of the rule that created the finding. A rule with a low
	// confidence means that the finding scope is wide and may create finding
	// reports that may not be malicious in nature.
	//
	// OCSF: confidence_id (type integer_t, requirement recommended)
	ConfidenceID int `json:"confidence_id,omitempty"`

	// ConfidenceScore is the Confidence Score. The confidence score as
	// reported by the event source.
	//
	// OCSF: confidence_score (type integer_t, requirement optional)
	ConfidenceScore int `json:"confidence_score,omitempty"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Device is the Device. An addressable device, computer system or host.
	//
	// OCSF: device (type device, requirement recommended)
	Device *objects.Device `json:"device,omitempty"`

	// Disposition is the Disposition. The disposition name, normalized to
	// the caption of the disposition_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: disposition (type string_t, requirement optional)
	Disposition string `json:"disposition,omitempty"`

	// DispositionID is the Disposition ID. Describes the outcome or action
	// taken by a security control, such as access control checks, malware
	// detections or various types of policy violations.
	//
	// OCSF: disposition_id (type integer_t, requirement recommended)
	DispositionID int `json:"disposition_id,omitempty"`

	// DstEndpoint is the Destination Endpoint. The endpoint to which the
	// authentication was targeted.
	//
	// OCSF: dst_endpoint (type network_endpoint, requirement recommended)
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The end time of a time period, or the time of
	// the most recent event included in the aggregate event.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// FirewallRule is the Firewall Rule. The firewall rule that pertains to
	// the control that triggered the event, if applicable.
	//
	// OCSF: firewall_rule (type firewall_rule, requirement optional)
	FirewallRule *objects.FirewallRule `json:"firewall_rule,omitempty"`

	// HTTPRequest is the HTTP Request. Details about the underlying HTTP
	// request.
	//
	// OCSF: http_request (type http_request, requirement optional)
	HTTPRequest *objects.HTTPRequest `json:"http_request,omitempty"`

	// HTTPResponse is the HTTP Response. Details about the underlying HTTP
	// response.
	//
	// OCSF: http_response (type http_response, requirement optional)
	HTTPResponse *objects.HTTPResponse `json:"http_response,omitempty"`

	// IsAlert is the Alert. Indicates that the event is considered to be an
	// alertable signal. Should be set to true if disposition_id = Alert
	// among other dispositions, and/or risk_level_id or severity_id of the
	// event is elevated. Not all control events will be alertable, for
	// example if disposition_id = Exonerated or disposition_id = Allowed.
	//
	// OCSF: is_alert (type boolean_t, requirement recommended)
	IsAlert bool `json:"is_alert,omitempty"`

	// IsCleartext is the Cleartext Credentials. Indicates whether the
	// credentials were passed in clear text.Note: True if the credentials
	// were passed in a clear text protocol such as FTP or TELNET, or if
	// Windows detected that a user's logon password was passed to the
	// authentication package in clear text.
	//
	// OCSF: is_cleartext (type boolean_t, requirement optional)
	IsCleartext bool `json:"is_cleartext,omitempty"`

	// IsMFA is the Multi Factor Authentication. Indicates whether Multi
	// Factor Authentication was used during authentication.
	//
	// OCSF: is_mfa (type boolean_t, requirement recommended)
	IsMFA bool `json:"is_mfa,omitempty"`

	// IsNewLogon is the New Logon. Indicates logon is from a device not seen
	// before or a first time account logon.
	//
	// OCSF: is_new_logon (type boolean_t, requirement optional)
	IsNewLogon bool `json:"is_new_logon,omitempty"`

	// IsRemote is the Remote. The attempted authentication is over a remote
	// connection.
	//
	// OCSF: is_remote (type boolean_t, requirement recommended)
	IsRemote bool `json:"is_remote,omitempty"`

	// LogonProcess is the Logon Process. The trusted process that validated
	// the authentication credentials.
	//
	// OCSF: logon_process (type process, requirement optional)
	LogonProcess *objects.Process `json:"logon_process,omitempty"`

	// LogonType is the Logon Type. The logon type, normalized to the caption
	// of the logon_type_id value. In the case of 'Other', it is defined by
	// the event source.
	//
	// OCSF: logon_type (type string_t, requirement recommended)
	LogonType string `json:"logon_type,omitempty"`

	// LogonTypeID is the Logon Type ID. The normalized logon type
	// identifier.
	//
	// OCSF: logon_type_id (type integer_t, requirement recommended)
	LogonTypeID int `json:"logon_type_id,omitempty"`

	// Malware is the Malware. A list of Malware objects, describing details
	// about the identified malware.
	//
	// OCSF: malware (type []malware, requirement optional)
	Malware []objects.Malware `json:"malware,omitempty"`

	// MalwareScanInfo is the Malware Scan Info. Describes details about the
	// scan job that identified malware on the target system.
	//
	// OCSF: malware_scan_info (type malware_scan_info, requirement optional)
	MalwareScanInfo *objects.MalwareScanInfo `json:"malware_scan_info,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// Policy is the Policy. The policy that pertains to the control that
	// triggered the event, if applicable. For example the name of an
	// anti-malware policy or an access control policy.
	//
	// OCSF: policy (type policy, requirement optional)
	Policy *objects.Policy `json:"policy,omitempty"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// RawDataHash is the Raw Data Hash. The hash, which describes the
	// content of the raw_data field.
	//
	// OCSF: raw_data_hash (type fingerprint, requirement optional)
	RawDataHash *objects.Fingerprint `json:"raw_data_hash,omitempty"`

	// RawDataSize is the Raw Data Size. The size of the raw data which was
	// transformed into an OCSF event, in bytes.
	//
	// OCSF: raw_data_size (type long_t, requirement optional)
	RawDataSize int64 `json:"raw_data_size,omitempty"`

	// RiskDetails is the Risk Details. Describes the risk associated with
	// the finding.
	//
	// OCSF: risk_details (type string_t, requirement optional)
	RiskDetails string `json:"risk_details,omitempty"`

	// RiskLevel is the Risk Level. The risk level, normalized to the caption
	// of the risk_level_id value.
	//
	// OCSF: risk_level (type string_t, requirement optional)
	RiskLevel string `json:"risk_level,omitempty"`

	// RiskLevelID is the Risk Level ID. The normalized risk level id.
	//
	// OCSF: risk_level_id (type integer_t, requirement optional)
	RiskLevelID int `json:"risk_level_id,omitempty"`

	// RiskScore is the Risk Score. The risk score as reported by the event
	// source.
	//
	// OCSF: risk_score (type integer_t, requirement optional)
	RiskScore int `json:"risk_score,omitempty"`

	// Service is the Service. The service or gateway to which the user or
	// process is being authenticated
	//
	// OCSF: service (type service, requirement recommended)
	Service *objects.Service `json:"service,omitempty"`

	// Session is the Session. The authenticated user or service session.
	//
	// OCSF: session (type session, requirement recommended)
	Session *objects.Session `json:"session,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// SrcEndpoint is the Source Endpoint. Details about the source of the
	// IAM activity.
	//
	// OCSF: src_endpoint (type network_endpoint, requirement recommended)
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`

	// StartTime is the Start Time. The start time of a time period, or the
	// time of the least recent event included in the aggregate event.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The event status, normalized to the caption of
	// the status_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The details about the
	// authentication request. For example, possible details for Windows
	// logon or logoff events
	// are:SuccessLOGOFF_USER_INITIATEDLOGOFF_OTHERFailureUSER_DOES_NOT_EXISTINVALID_CREDENTIALSACCOUNT_DISABLEDACCOUNT_LOCKED_OUTPASSWORD_EXPIRED
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized identifier of the event
	// status.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`

	// User is the User. The subject (user/role or account) to authenticate.
	//
	// OCSF: user (type user, requirement required)
	User *objects.User `json:"user"`
}

// OCSFClassUID returns the OCSF class_uid for Authentication (3002).
// Computed as CategoryUID*1000 + class identifier within the category.
func (Authentication) OCSFClassUID() int { return 3002 }

// OCSFClassName returns the OCSF class_name for Authentication.
func (Authentication) OCSFClassName() string { return "Authentication" }

// OCSFCategoryUID returns the OCSF category_uid for the iam category (3).
func (Authentication) OCSFCategoryUID() int { return 3 }

// OCSFCategoryName returns the OCSF category_name (iam).
func (Authentication) OCSFCategoryName() string { return "iam" }

// Validate checks the required-field rules for Authentication.
// Returns the first violation found, or nil if all required fields are present.
func (e Authentication) Validate() error {
	if e.Cloud == nil {
		return &ocsf.ValidationError{ClassUID: 3002, Field: "cloud", Rule: "required", Reason: "required field is missing"}
	}
	if e.Metadata == nil {
		return &ocsf.ValidationError{ClassUID: 3002, Field: "metadata", Rule: "required", Reason: "required field is missing"}
	}
	if len(e.Osint) == 0 {
		return &ocsf.ValidationError{ClassUID: 3002, Field: "osint", Rule: "required", Reason: "required field is missing"}
	}
	if e.User == nil {
		return &ocsf.ValidationError{ClassUID: 3002, Field: "user", Rule: "required", Reason: "required field is missing"}
	}
	switch e.AccountSwitchTypeID {
	case 0, 1, 2, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "account_switch_type_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.AccountSwitchType != "" {
		switch e.AccountSwitchTypeID {
		case 0:
			if e.AccountSwitchType != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "account_switch_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.AccountSwitchType != "Substitute User" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "account_switch_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.AccountSwitchType != "Impersonate" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "account_switch_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ActionID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "action_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Action != "" {
		switch e.ActionID {
		case 0:
			if e.Action != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Action != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Action != "Denied" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Action != "Observed" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Action != "Modified" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ActivityID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.ActivityName != "" {
		switch e.ActivityID {
		case 0:
			if e.ActivityName != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.ActivityName != "Logon" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.ActivityName != "Logoff" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.ActivityName != "Authentication Ticket" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.ActivityName != "Service Ticket Request" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.ActivityName != "Service Ticket Renew" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.ActivityName != "Preauth" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.ActivityName != "Account Switch" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.ActivityName != "Detach Policy" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.ActivityName != "Lock" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.ActivityName != "MFA Factor Enable" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.ActivityName != "MFA Factor Disable" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.ActivityName != "Unlock" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.AuthProtocolID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.AuthProtocol != "" {
		switch e.AuthProtocolID {
		case 0:
			if e.AuthProtocol != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.AuthProtocol != "NTLM" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.AuthProtocol != "Kerberos" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.AuthProtocol != "Digest" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.AuthProtocol != "OpenID" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.AuthProtocol != "SAML" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.AuthProtocol != "OAUTH 2.0" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.AuthProtocol != "PAP" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.AuthProtocol != "CHAP" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.AuthProtocol != "EAP" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.AuthProtocol != "RADIUS" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.AuthProtocol != "Basic Authentication" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.AuthProtocol != "LDAP" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "auth_protocol", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ConfidenceID {
	case 0, 1, 2, 3, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "confidence_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Confidence != "" {
		switch e.ConfidenceID {
		case 0:
			if e.Confidence != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Confidence != "Low" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Confidence != "Medium" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Confidence != "High" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "confidence", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.DispositionID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Disposition != "" {
		switch e.DispositionID {
		case 0:
			if e.Disposition != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Disposition != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Disposition != "Blocked" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Disposition != "Quarantined" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Disposition != "Isolated" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Disposition != "Deleted" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Disposition != "Dropped" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.Disposition != "Custom Action" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.Disposition != "Approved" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.Disposition != "Restored" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.Disposition != "Exonerated" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.Disposition != "Corrected" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.Disposition != "Partially Corrected" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 13:
			if e.Disposition != "Uncorrected" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 14:
			if e.Disposition != "Delayed" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 15:
			if e.Disposition != "Detected" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 16:
			if e.Disposition != "No Action" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 17:
			if e.Disposition != "Logged" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 18:
			if e.Disposition != "Tagged" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 19:
			if e.Disposition != "Alert" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 20:
			if e.Disposition != "Count" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 21:
			if e.Disposition != "Reset" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 22:
			if e.Disposition != "Captcha" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 23:
			if e.Disposition != "Challenge" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 24:
			if e.Disposition != "Access Revoked" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 25:
			if e.Disposition != "Rejected" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 26:
			if e.Disposition != "Unauthorized" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 27:
			if e.Disposition != "Error" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.LogonTypeID {
	case 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.LogonType != "" {
		switch e.LogonTypeID {
		case 0:
			if e.LogonType != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.LogonType != "System" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.LogonType != "Interactive" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.LogonType != "Network" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.LogonType != "Batch" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.LogonType != "OS Service" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.LogonType != "Unlock" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.LogonType != "Network Cleartext" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.LogonType != "New Credentials" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.LogonType != "Remote Interactive" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.LogonType != "Cached Interactive" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.LogonType != "Cached Remote Interactive" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 13:
			if e.LogonType != "Cached Unlock" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "logon_type", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.RiskLevelID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.RiskLevel != "" {
		switch e.RiskLevelID {
		case 0:
			if e.RiskLevel != "Info" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.RiskLevel != "Low" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.RiskLevel != "Medium" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.RiskLevel != "High" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.RiskLevel != "Critical" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.SeverityID {
	case 0, 1, 2, 3, 4, 5, 6, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "severity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Severity != "" {
		switch e.SeverityID {
		case 0:
			if e.Severity != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Severity != "Informational" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Severity != "Low" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Severity != "Medium" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Severity != "High" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Severity != "Critical" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Severity != "Fatal" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.StatusID {
	case 0, 1, 2, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 3002, Field: "status_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Status != "" {
		switch e.StatusID {
		case 0:
			if e.Status != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Status != "Success" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Status != "Failure" {
				return &ocsf.ValidationError{ClassUID: 3002, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	if !(e.Service != nil || e.DstEndpoint != nil) {
		return &ocsf.ValidationError{ClassUID: 3002, Field: "service,dst_endpoint", Rule: "constraint", Reason: "at_least_one: at least one of these fields must be set"}
	}
	return nil
}

func init() {
	ocsf.RegisterClass(3002, func() ocsf.Event { return &Authentication{} })
}
