// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package base

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// BaseEvent describes the OCSF Base Event event class: The base event is
// a generic and concrete event. It also defines a set of attributes
// available in most event classes. As a generic event that does not
// belong to any event category, it could be used to log events that are
// not otherwise defined by the schema.
//
// OCSF name: base_event. class_uid: 0.
type BaseEvent struct {
	// ActivityID is the Activity ID. The normalized identifier of the
	// activity that triggered the event.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The event activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event was originally created or logged.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The end time of a time period, or the time of
	// the most recent event included in the aggregate event.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// StartTime is the Start Time. The start time of a time period, or the
	// time of the least recent event included in the aggregate event.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The event status, normalized to the caption of
	// the status_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized identifier of the event
	// status.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for Base Event (0).
// Computed as CategoryUID*1000 + class identifier within the category.
func (BaseEvent) OCSFClassUID() int { return 0 }

// OCSFClassName returns the OCSF class_name for Base Event.
func (BaseEvent) OCSFClassName() string { return "Base Event" }

// OCSFCategoryUID returns the OCSF category_uid for the other category (0).
func (BaseEvent) OCSFCategoryUID() int { return 0 }

// OCSFCategoryName returns the OCSF category_name (other).
func (BaseEvent) OCSFCategoryName() string { return "other" }

// Validate checks the required-field rules for BaseEvent.
// Returns the first violation found, or nil if all required fields are present.
func (e BaseEvent) Validate() error {
	if e.Cloud == nil {
		return &ocsf.ValidationError{ClassUID: 0, Field: "cloud", Rule: "required", Reason: "required field is missing"}
	}
	if e.Metadata == nil {
		return &ocsf.ValidationError{ClassUID: 0, Field: "metadata", Rule: "required", Reason: "required field is missing"}
	}
	if len(e.Osint) == 0 {
		return &ocsf.ValidationError{ClassUID: 0, Field: "osint", Rule: "required", Reason: "required field is missing"}
	}
	switch e.ActivityID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 0, Field: "activity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.ActivityName != "" {
		switch e.ActivityID {
		case 0:
			if e.ActivityName != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.ActivityName != "Create" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.ActivityName != "Read" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.ActivityName != "Update" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.ActivityName != "Delete" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.ActivityName != "Search" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.ActivityName != "Import" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.ActivityName != "Export" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.ActivityName != "Share" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.ActivityName != "Restarted" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.ActivityName != "Delayed" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.SeverityID {
	case 0, 1, 2, 3, 4, 5, 6, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 0, Field: "severity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Severity != "" {
		switch e.SeverityID {
		case 0:
			if e.Severity != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Severity != "Informational" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Severity != "Low" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Severity != "Medium" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Severity != "High" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Severity != "Critical" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Severity != "Fatal" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.StatusID {
	case 0, 1, 2, 3, 4, 5, 6, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 0, Field: "status_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Status != "" {
		switch e.StatusID {
		case 0:
			if e.Status != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Status != "New" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Status != "In Progress" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Status != "On Hold" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Status != "Resolved" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Status != "Closed" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Status != "Error" {
				return &ocsf.ValidationError{ClassUID: 0, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	return nil
}
