// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package findings

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// ComplianceFinding describes the OCSF Compliance Finding event class:
// Compliance Finding events describe results of evaluations performed
// against resources, to check compliance with various Industry
// Frameworks or Security Standards such as NIST SP 800-53, CIS AWS
// Foundations Benchmark v1.4.0, ISO/IEC 27001 etc.
//
// OCSF name: compliance_finding. class_uid: 2003.
type ComplianceFinding struct {
	// ActivityID is the Activity ID. The normalized identifier of the
	// finding activity.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The finding activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. The actor object describes details about the
	// user/role/process that was the source of the activity.
	//
	// OCSF: actor (type actor, requirement optional)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event was originally created or logged.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Comment is the Comment. A user provided comment about the finding.
	//
	// OCSF: comment (type string_t, requirement optional)
	Comment string `json:"comment,omitempty"`

	// Compliance is the Compliance. The compliance object provides context
	// to compliance findings (e.g., a check against a specific regulatory or
	// best practice framework such as CIS, NIST etc.) and contains
	// compliance related details.
	//
	// OCSF: compliance (type compliance, requirement required)
	Compliance *objects.Compliance `json:"compliance"`

	// Confidence is the Confidence. The confidence, normalized to the
	// caption of the confidence_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: confidence (type string_t, requirement optional)
	Confidence string `json:"confidence,omitempty"`

	// ConfidenceID is the Confidence Id. The normalized confidence refers to
	// the accuracy of the rule that created the finding. A rule with a low
	// confidence means that the finding scope is wide and may create finding
	// reports that may not be malicious in nature.
	//
	// OCSF: confidence_id (type integer_t, requirement recommended)
	ConfidenceID int `json:"confidence_id,omitempty"`

	// ConfidenceScore is the Confidence Score. The confidence score as
	// reported by the event source.
	//
	// OCSF: confidence_score (type integer_t, requirement optional)
	ConfidenceScore int `json:"confidence_score,omitempty"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Device is the Device. Describes the affected device/host. It can be
	// used in conjunction with Affected Resource(s). e.g. Specific details
	// about an AWS EC2 instance, that is affected by the Finding.
	//
	// OCSF: device (type device, requirement recommended)
	Device *objects.Device `json:"device,omitempty"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The time of the most recent event included in
	// the finding.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// FindingInfo is the Finding Information. Describes the supporting
	// information about a generated finding.
	//
	// OCSF: finding_info (type finding_info, requirement required)
	FindingInfo *objects.FindingInfo `json:"finding_info"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// Remediation is the Remediation Guidance. Describes the recommended
	// remediation steps to address identified issue(s).
	//
	// OCSF: remediation (type remediation, requirement recommended)
	Remediation *objects.Remediation `json:"remediation,omitempty"`

	// Resource is the Resource. Describes details about the resource that is
	// the subject of the compliance check.
	//
	// OCSF: resource (type resource_details, requirement recommended)
	//
	// Deprecated: Use the <code>resources</code> attribute instead.
	Resource *objects.ResourceDetails `json:"resource,omitempty"`

	// Resources is the Resources Array. Describes details about the
	// resource/resouces that are the subject of the compliance check.
	//
	// OCSF: resources (type []resource_details, requirement recommended)
	Resources []objects.ResourceDetails `json:"resources,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// StartTime is the Start Time. The time of the least recent event
	// included in the finding.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The normalized status of the Finding set by the
	// consumer normalized to the caption of the status_id value. In the case
	// of 'Other', it is defined by the source.
	//
	// OCSF: status (type string_t, requirement optional)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized status identifier of the
	// Finding, set by the consumer.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for Compliance Finding (2003).
// Computed as CategoryUID*1000 + class identifier within the category.
func (ComplianceFinding) OCSFClassUID() int { return 2003 }

// OCSFClassName returns the OCSF class_name for Compliance Finding.
func (ComplianceFinding) OCSFClassName() string { return "Compliance Finding" }

// OCSFCategoryUID returns the OCSF category_uid for the findings category (2).
func (ComplianceFinding) OCSFCategoryUID() int { return 2 }

// OCSFCategoryName returns the OCSF category_name (findings).
func (ComplianceFinding) OCSFCategoryName() string { return "findings" }

func init() {
	ocsf.RegisterClass(2003, func() ocsf.Event { return &ComplianceFinding{} })
}
