// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package findings

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// DataSecurityFinding describes the OCSF Data Security Finding event
// class: A Data Security Finding describes detections or alerts
// generated by various data security products such as Data Loss
// Prevention (DLP), Data Classification, Secrets Management, Digital
// Rights Management (DRM), Data Security Posture Management (DSPM), and
// similar tools. These detections or alerts can be created using
// fingerprinting, statistical analysis, machine learning or other
// methodologies. The finding describes the actors and endpoints who
// accessed or own the sensitive data, as well as the resources which
// store the sensitive data.
//
// OCSF name: data_security_finding. class_uid: 2006.
type DataSecurityFinding struct {
	// Action is the Action. The normalized caption of action_id.
	//
	// OCSF: action (type string_t, requirement optional)
	Action string `json:"action,omitempty"`

	// ActionID is the Action ID. The action taken by a control or other
	// policy-based system leading to an outcome or disposition. Dispositions
	// conform to an action of 1 'Allowed' or 2 'Denied' in most cases. Note
	// that 99 'Other' is not an option. No action would equate to 1
	// 'Allowed'. An unknown action may still correspond to a known
	// disposition. Refer to disposition_id for the outcome of the action.
	//
	// OCSF: action_id (type integer_t, requirement required)
	ActionID int `json:"action_id"`

	// ActivityID is the Activity ID. The normalized identifier of the Data
	// Security Finding activity.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The Data Security finding activity name,
	// as defined by the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. Describes details about the actor implicated in
	// the data security finding. Either an actor that owns a particular
	// digital file or information store, or an actor which accessed
	// classified or sensitive data.
	//
	// OCSF: actor (type actor, requirement recommended)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// Attacks is the MITRE ATT&CK® Details. An array of MITRE ATT&CK®
	// objects describing the tactics, techniques & sub-techniques identified
	// by a security control or finding.
	//
	// OCSF: attacks (type []attack, requirement optional)
	Attacks []objects.Attack `json:"attacks,omitempty"`

	// Authorizations is the Authorization Information. Provides details
	// about an authorization, such as authorization outcome, and any
	// associated policies related to the activity/event.
	//
	// OCSF: authorizations (type []authorization, requirement optional)
	Authorizations []objects.Authorization `json:"authorizations,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event was originally created or logged.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Comment is the Comment. A user provided comment about the finding.
	//
	// OCSF: comment (type string_t, requirement optional)
	Comment string `json:"comment,omitempty"`

	// Confidence is the Confidence. The confidence, normalized to the
	// caption of the confidence_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: confidence (type string_t, requirement optional)
	Confidence string `json:"confidence,omitempty"`

	// ConfidenceID is the Confidence Id. The normalized confidence refers to
	// the accuracy of the rule that created the finding. A rule with a low
	// confidence means that the finding scope is wide and may create finding
	// reports that may not be malicious in nature.
	//
	// OCSF: confidence_id (type integer_t, requirement recommended)
	ConfidenceID int `json:"confidence_id,omitempty"`

	// ConfidenceScore is the Confidence Score. The confidence score as
	// reported by the event source.
	//
	// OCSF: confidence_score (type integer_t, requirement optional)
	ConfidenceScore int `json:"confidence_score,omitempty"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// DataSecurity is the Data Security. The Data Security object describes
	// the characteristics, techniques and content of a Data Loss Prevention
	// (DLP), Data Loss Detection (DLD), Data Classification, or similar
	// tools' finding, alert, or detection mechanism(s).
	//
	// OCSF: data_security (type data_security, requirement recommended)
	DataSecurity *objects.DataSecurity `json:"data_security,omitempty"`

	// Database is the Database. Describes the database where classified or
	// sensitive data is stored in, or was accessed from. Databases are
	// typically datastore services that contain an organized collection of
	// structured and/or semi-structured data.
	//
	// OCSF: database (type database, requirement recommended)
	Database *objects.Database `json:"database,omitempty"`

	// Databucket is the Databucket. Describes the databucket where
	// classified or sensitive data is stored in, or was accessed from. The
	// data bucket object is a basic container that holds data, typically
	// organized through the use of data partitions.
	//
	// OCSF: databucket (type databucket, requirement recommended)
	Databucket *objects.Databucket `json:"databucket,omitempty"`

	// Device is the Device. Describes the device where classified or
	// sensitive data is stored in, or was accessed from.
	//
	// OCSF: device (type device, requirement recommended)
	Device *objects.Device `json:"device,omitempty"`

	// Disposition is the Disposition. The disposition name, normalized to
	// the caption of the disposition_id value. In the case of 'Other', it is
	// defined by the event source.
	//
	// OCSF: disposition (type string_t, requirement optional)
	Disposition string `json:"disposition,omitempty"`

	// DispositionID is the Disposition ID. Describes the outcome or action
	// taken by a security control, such as access control checks, malware
	// detections or various types of policy violations.
	//
	// OCSF: disposition_id (type integer_t, requirement recommended)
	DispositionID int `json:"disposition_id,omitempty"`

	// DstEndpoint is the Destination Endpoint. Describes the endpoint where
	// classified or sensitive data is stored in, or was accessed from.
	//
	// OCSF: dst_endpoint (type network_endpoint, requirement recommended)
	DstEndpoint *objects.NetworkEndpoint `json:"dst_endpoint,omitempty"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The time of the most recent event included in
	// the finding.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// File is the File. Describes a file that contains classified or
	// sensitive data.
	//
	// OCSF: file (type file, requirement recommended)
	File *objects.File `json:"file,omitempty"`

	// FindingInfo is the Finding Information. Describes the supporting
	// information about a generated finding.
	//
	// OCSF: finding_info (type finding_info, requirement required)
	FindingInfo *objects.FindingInfo `json:"finding_info"`

	// FirewallRule is the Firewall Rule. The firewall rule that triggered
	// the event.
	//
	// OCSF: firewall_rule (type firewall_rule, requirement optional)
	FirewallRule *objects.FirewallRule `json:"firewall_rule,omitempty"`

	// Impact is the Impact. The impact , normalized to the caption of the
	// impact_id value. In the case of 'Other', it is defined by the event
	// source.
	//
	// OCSF: impact (type string_t, requirement optional)
	Impact string `json:"impact,omitempty"`

	// ImpactID is the Impact ID. The normalized impact of the finding.
	//
	// OCSF: impact_id (type integer_t, requirement optional)
	ImpactID int `json:"impact_id,omitempty"`

	// ImpactScore is the Impact. The impact of the finding, valid range
	// 0-100.
	//
	// OCSF: impact_score (type integer_t, requirement optional)
	ImpactScore int `json:"impact_score,omitempty"`

	// Malware is the Malware. A list of Malware objects, describing details
	// about the identified malware.
	//
	// OCSF: malware (type []malware, requirement optional)
	Malware []objects.Malware `json:"malware,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// Resources is the Affected Resources. Describes details about resources
	// where classified or sensitive data is stored in, or was accessed from.
	//
	// OCSF: resources (type []resource_details, requirement recommended)
	Resources []objects.ResourceDetails `json:"resources,omitempty"`

	// RiskLevel is the Risk Level. The risk level, normalized to the caption
	// of the risk_level_id value.
	//
	// OCSF: risk_level (type string_t, requirement optional)
	RiskLevel string `json:"risk_level,omitempty"`

	// RiskLevelID is the Risk Level ID. The normalized risk level id.
	//
	// OCSF: risk_level_id (type integer_t, requirement optional)
	RiskLevelID int `json:"risk_level_id,omitempty"`

	// RiskScore is the Risk Score. The risk score as reported by the event
	// source.
	//
	// OCSF: risk_score (type integer_t, requirement optional)
	RiskScore int `json:"risk_score,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// SrcEndpoint is the Affected Resources. Details about the source
	// endpoint where classified or sensitive data was accessed from.
	//
	// OCSF: src_endpoint (type network_endpoint, requirement recommended)
	SrcEndpoint *objects.NetworkEndpoint `json:"src_endpoint,omitempty"`

	// StartTime is the Start Time. The time of the least recent event
	// included in the finding.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// Status is the Status. The normalized status of the Finding set by the
	// consumer normalized to the caption of the status_id value. In the case
	// of 'Other', it is defined by the source.
	//
	// OCSF: status (type string_t, requirement optional)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized status identifier of the
	// Finding, set by the consumer.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Table is the Table. Describes the table where classified or sensitive
	// data is stored in, or was accessed from. The table object represents a
	// table within a structured relational database, warehouse, lake, or
	// similar.
	//
	// OCSF: table (type table, requirement recommended)
	Table *objects.Table `json:"table,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for Data Security Finding (2006).
// Computed as CategoryUID*1000 + class identifier within the category.
func (DataSecurityFinding) OCSFClassUID() int { return 2006 }

// OCSFClassName returns the OCSF class_name for Data Security Finding.
func (DataSecurityFinding) OCSFClassName() string { return "Data Security Finding" }

// OCSFCategoryUID returns the OCSF category_uid for the findings category (2).
func (DataSecurityFinding) OCSFCategoryUID() int { return 2 }

// OCSFCategoryName returns the OCSF category_name (findings).
func (DataSecurityFinding) OCSFCategoryName() string { return "findings" }

// Validate checks the required-field rules for DataSecurityFinding.
// Returns the first violation found, or nil if all required fields are present.
func (e DataSecurityFinding) Validate() error {
	if e.Cloud == nil {
		return &ocsf.ValidationError{ClassUID: 2006, Field: "cloud", Rule: "required", Reason: "required field is missing"}
	}
	if e.FindingInfo == nil {
		return &ocsf.ValidationError{ClassUID: 2006, Field: "finding_info", Rule: "required", Reason: "required field is missing"}
	}
	if e.Metadata == nil {
		return &ocsf.ValidationError{ClassUID: 2006, Field: "metadata", Rule: "required", Reason: "required field is missing"}
	}
	if len(e.Osint) == 0 {
		return &ocsf.ValidationError{ClassUID: 2006, Field: "osint", Rule: "required", Reason: "required field is missing"}
	}
	switch e.ActionID {
	case 0, 1, 2, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "action_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Action != "" {
		switch e.ActionID {
		case 0:
			if e.Action != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Action != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Action != "Denied" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "action", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ActivityID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.ActivityName != "" {
		switch e.ActivityID {
		case 0:
			if e.ActivityName != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.ActivityName != "Create" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.ActivityName != "Update" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.ActivityName != "Close" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.ActivityName != "Suppressed" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "activity_name", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ConfidenceID {
	case 0, 1, 2, 3, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "confidence_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	switch e.DispositionID {
	case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Disposition != "" {
		switch e.DispositionID {
		case 0:
			if e.Disposition != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Disposition != "Allowed" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Disposition != "Blocked" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Disposition != "Quarantined" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Disposition != "Isolated" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Disposition != "Deleted" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Disposition != "Dropped" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 7:
			if e.Disposition != "Custom Action" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 8:
			if e.Disposition != "Approved" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 9:
			if e.Disposition != "Restored" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 10:
			if e.Disposition != "Exonerated" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 11:
			if e.Disposition != "Corrected" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 12:
			if e.Disposition != "Partially Corrected" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 13:
			if e.Disposition != "Uncorrected" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 14:
			if e.Disposition != "Delayed" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 15:
			if e.Disposition != "Detected" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 16:
			if e.Disposition != "No Action" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 17:
			if e.Disposition != "Logged" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 18:
			if e.Disposition != "Tagged" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 19:
			if e.Disposition != "Alert" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 20:
			if e.Disposition != "Count" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 21:
			if e.Disposition != "Reset" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 22:
			if e.Disposition != "Captcha" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 23:
			if e.Disposition != "Challenge" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 24:
			if e.Disposition != "Access Revoked" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 25:
			if e.Disposition != "Rejected" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 26:
			if e.Disposition != "Unauthorized" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 27:
			if e.Disposition != "Error" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "disposition", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.ImpactID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "impact_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Impact != "" {
		switch e.ImpactID {
		case 0:
			if e.Impact != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "impact", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Impact != "Low" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "impact", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Impact != "Medium" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "impact", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Impact != "High" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "impact", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Impact != "Critical" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "impact", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.RiskLevelID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.RiskLevel != "" {
		switch e.RiskLevelID {
		case 0:
			if e.RiskLevel != "Info" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.RiskLevel != "Low" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.RiskLevel != "Medium" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.RiskLevel != "High" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.RiskLevel != "Critical" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "risk_level", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.SeverityID {
	case 0, 1, 2, 3, 4, 5, 6, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "severity_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Severity != "" {
		switch e.SeverityID {
		case 0:
			if e.Severity != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Severity != "Informational" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Severity != "Low" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Severity != "Medium" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Severity != "High" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 5:
			if e.Severity != "Critical" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 6:
			if e.Severity != "Fatal" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "severity", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	switch e.StatusID {
	case 0, 1, 2, 3, 4, 99:
	default:
		return &ocsf.ValidationError{ClassUID: 2006, Field: "status_id", Rule: "enum", Reason: "value outside the schema's enum range"}
	}
	if e.Status != "" {
		switch e.StatusID {
		case 0:
			if e.Status != "Unknown" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 1:
			if e.Status != "New" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 2:
			if e.Status != "In Progress" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 3:
			if e.Status != "Suppressed" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		case 4:
			if e.Status != "Resolved" {
				return &ocsf.ValidationError{ClassUID: 2006, Field: "status", Rule: "enum", Reason: "sibling does not match enum caption"}
			}
		}
	}
	return nil
}

func init() {
	ocsf.RegisterClass(2006, func() ocsf.Event { return &DataSecurityFinding{} })
}
