// Code generated by internal/gen; DO NOT EDIT.

// Copyright 2026 The go-ocsf Authors
// SPDX-License-Identifier: Apache-2.0

package discovery

import (
	"encoding/json"
	"github.com/hstern/go-ocsf"
	"github.com/hstern/go-ocsf/objects"
)

// DeviceConfigStateChange describes the OCSF Device Config State Change
// event class: Device Config State Change events report state changes
// that impact the security of the device.
//
// OCSF name: device_config_state_change. class_uid: 5019.
type DeviceConfigStateChange struct {
	// ActivityID is the Activity ID. The normalized identifier of the
	// activity that triggered the event.
	//
	// OCSF: activity_id (type integer_t, requirement required)
	ActivityID int `json:"activity_id"`

	// ActivityName is the Activity. The event activity name, as defined by
	// the activity_id.
	//
	// OCSF: activity_name (type string_t, requirement optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Actor is the Actor. The actor object describes details about the
	// user/role/process that was the source of the activity.
	//
	// OCSF: actor (type actor, requirement optional)
	Actor *objects.Actor `json:"actor,omitempty"`

	// API is the API Details. Describes details about a typical API
	// (Application Programming Interface) call.
	//
	// OCSF: api (type api, requirement optional)
	API *objects.API `json:"api,omitempty"`

	// CategoryName is the Category. The event category name, as defined by
	// category_uid value.
	//
	// OCSF: category_name (type string_t, requirement optional)
	CategoryName string `json:"category_name,omitempty"`

	// CategoryUID is the Category ID. The category unique identifier of the
	// event.
	//
	// OCSF: category_uid (type integer_t, requirement required)
	CategoryUID int `json:"category_uid"`

	// ClassName is the Class. The event class name, as defined by class_uid
	// value.
	//
	// OCSF: class_name (type string_t, requirement optional)
	ClassName string `json:"class_name,omitempty"`

	// ClassUID is the Class ID. The unique identifier of a class. A class
	// describes the attributes available in an event.
	//
	// OCSF: class_uid (type integer_t, requirement required)
	ClassUID int `json:"class_uid"`

	// Cloud is the Cloud. Describes details about the Cloud environment
	// where the event was originally created or logged.
	//
	// OCSF: cloud (type cloud, requirement required)
	Cloud *objects.Cloud `json:"cloud"`

	// Count is the Count. The number of times that events in the same
	// logical group occurred during the event Start Time to End Time period.
	//
	// OCSF: count (type integer_t, requirement optional)
	Count int `json:"count,omitempty"`

	// Device is the Device. The device that is impacted by the state change.
	//
	// OCSF: device (type device, requirement required)
	Device *objects.Device `json:"device"`

	// Duration is the Duration Milliseconds. The event duration or aggregate
	// time, the amount of time the event covers from start_time to end_time
	// in milliseconds.
	//
	// OCSF: duration (type long_t, requirement optional)
	Duration int64 `json:"duration,omitempty"`

	// EndTime is the End Time. The end time of a time period, or the time of
	// the most recent event included in the aggregate event.
	//
	// OCSF: end_time (type timestamp_t, requirement optional)
	EndTime int64 `json:"end_time,omitempty"`

	// Enrichments is the Enrichments. The additional information from an
	// external data source, which is associated with the event or a finding.
	// For example add location information for the IP address in the DNS
	// answers:[{"name": "answers.ip", "value": "92.24.47.250", "type":
	// "location", "data": {"city": "Socotra", "continent": "Asia",
	// "coordinates": [-25.4153, 17.0743], "country": "YE", "desc":
	// "Yemen"}}]
	//
	// OCSF: enrichments (type []enrichment, requirement optional)
	Enrichments []objects.Enrichment `json:"enrichments,omitempty"`

	// Message is the Message. The description of the event/finding, as
	// defined by the source.
	//
	// OCSF: message (type string_t, requirement recommended)
	Message string `json:"message,omitempty"`

	// Metadata is the Metadata. The metadata associated with the event or a
	// finding.
	//
	// OCSF: metadata (type metadata, requirement required)
	Metadata *objects.Metadata `json:"metadata"`

	// Observables is the Observables. The observables associated with the
	// event or a finding.
	//
	// OCSF: observables (type []observable, requirement recommended)
	Observables []objects.Observable `json:"observables,omitempty"`

	// Osint is the OSINT. The OSINT (Open Source Intelligence) object
	// contains details related to an indicator such as the indicator itself,
	// related indicators, geolocation, registrar information, subdomains,
	// analyst commentary, and other contextual information. This information
	// can be used to further enrich a detection or finding by providing
	// decisioning support to other analysts and engineers.
	//
	// OCSF: osint (type []osint, requirement required)
	Osint []objects.Osint `json:"osint"`

	// PrevSecurityLevel is the Previous Security Level. The previous
	// security level of the entity
	//
	// OCSF: prev_security_level (type string_t, requirement recommended)
	PrevSecurityLevel string `json:"prev_security_level,omitempty"`

	// PrevSecurityLevelID is the Previous Security Level ID. The previous
	// security level of the entity
	//
	// OCSF: prev_security_level_id (type integer_t, requirement recommended)
	PrevSecurityLevelID int `json:"prev_security_level_id,omitempty"`

	// PrevSecurityStates is the Previous Security States. The previous
	// security states of the device.
	//
	// OCSF: prev_security_states (type []security_state, requirement recommended)
	PrevSecurityStates []objects.SecurityState `json:"prev_security_states,omitempty"`

	// RawData is the Raw Data. The raw event/finding data as received from
	// the source.
	//
	// OCSF: raw_data (type string_t, requirement optional)
	RawData string `json:"raw_data,omitempty"`

	// SecurityLevel is the Security Level. The current security level of the
	// entity
	//
	// OCSF: security_level (type string_t, requirement recommended)
	SecurityLevel string `json:"security_level,omitempty"`

	// SecurityLevelID is the Security Level ID. The current security level
	// of the entity
	//
	// OCSF: security_level_id (type integer_t, requirement recommended)
	SecurityLevelID int `json:"security_level_id,omitempty"`

	// SecurityStates is the Security States. The current security states of
	// the device.
	//
	// OCSF: security_states (type []security_state, requirement recommended)
	SecurityStates []objects.SecurityState `json:"security_states,omitempty"`

	// Severity is the Severity. The event/finding severity, normalized to
	// the caption of the severity_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: severity (type string_t, requirement optional)
	Severity string `json:"severity,omitempty"`

	// SeverityID is the Severity ID. The normalized identifier of the
	// event/finding severity.The normalized severity is a measurement the
	// effort and expense required to manage and resolve an event or
	// incident. Smaller numerical values represent lower impact events, and
	// larger numerical values represent higher impact events.
	//
	// OCSF: severity_id (type integer_t, requirement required)
	SeverityID int `json:"severity_id"`

	// StartTime is the Start Time. The start time of a time period, or the
	// time of the least recent event included in the aggregate event.
	//
	// OCSF: start_time (type timestamp_t, requirement optional)
	StartTime int64 `json:"start_time,omitempty"`

	// State is the Config Change State. The Config Change Stat, normalized
	// to the caption of the state_id value. In the case of 'Other', it is
	// defined by the source.
	//
	// OCSF: state (type string_t, requirement optional)
	State string `json:"state,omitempty"`

	// StateID is the Config Change State ID. The Config Change State of the
	// managed entity.
	//
	// OCSF: state_id (type integer_t, requirement recommended)
	StateID int `json:"state_id,omitempty"`

	// Status is the Status. The event status, normalized to the caption of
	// the status_id value. In the case of 'Other', it is defined by the
	// event source.
	//
	// OCSF: status (type string_t, requirement recommended)
	Status string `json:"status,omitempty"`

	// StatusCode is the Status Code. The event status code, as reported by
	// the event source.For example, in a Windows Failed Authentication
	// event, this would be the value of 'Failure Code', e.g. 0x18.
	//
	// OCSF: status_code (type string_t, requirement recommended)
	StatusCode string `json:"status_code,omitempty"`

	// StatusDetail is the Status Detail. The status detail contains
	// additional information about the event/finding outcome.
	//
	// OCSF: status_detail (type string_t, requirement recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// StatusID is the Status ID. The normalized identifier of the event
	// status.
	//
	// OCSF: status_id (type integer_t, requirement recommended)
	StatusID int `json:"status_id,omitempty"`

	// Time is the Event Time. The normalized event occurrence time or the
	// finding creation time.
	//
	// OCSF: time (type timestamp_t, requirement required)
	Time int64 `json:"time"`

	// TimezoneOffset is the Timezone Offset. The number of minutes that the
	// reported event time is ahead or behind UTC, in the range -1,080 to
	// +1,080.
	//
	// OCSF: timezone_offset (type integer_t, requirement recommended)
	TimezoneOffset int `json:"timezone_offset,omitempty"`

	// TypeName is the Type Name. The event/finding type name, as defined by
	// the type_uid.
	//
	// OCSF: type_name (type string_t, requirement optional)
	TypeName string `json:"type_name,omitempty"`

	// TypeUID is the Type ID. The event/finding type ID. It identifies the
	// event's semantics and structure. The value is calculated by the
	// logging system as: class_uid * 100 + activity_id.
	//
	// OCSF: type_uid (type long_t, requirement required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped is the Unmapped Data. The attributes that are not mapped to
	// the event schema. The names and values of those attributes are
	// specific to the event source.
	//
	// OCSF: unmapped (type object, requirement optional)
	Unmapped json.RawMessage `json:"unmapped,omitempty"`
}

// OCSFClassUID returns the OCSF class_uid for Device Config State Change (5019).
// Computed as CategoryUID*1000 + class identifier within the category.
func (DeviceConfigStateChange) OCSFClassUID() int { return 5019 }

// OCSFClassName returns the OCSF class_name for Device Config State Change.
func (DeviceConfigStateChange) OCSFClassName() string { return "Device Config State Change" }

// OCSFCategoryUID returns the OCSF category_uid for the discovery category (5).
func (DeviceConfigStateChange) OCSFCategoryUID() int { return 5 }

// OCSFCategoryName returns the OCSF category_name (discovery).
func (DeviceConfigStateChange) OCSFCategoryName() string { return "discovery" }

// Validate checks the required-field rules for DeviceConfigStateChange.
// Returns the first violation found, or nil if all required fields are present.
func (e DeviceConfigStateChange) Validate() error {
	if e.Cloud == nil {
		return &ocsf.ValidationError{ClassUID: 5019, Field: "cloud", Rule: "required", Reason: "required field is missing"}
	}
	if e.Device == nil {
		return &ocsf.ValidationError{ClassUID: 5019, Field: "device", Rule: "required", Reason: "required field is missing"}
	}
	if e.Metadata == nil {
		return &ocsf.ValidationError{ClassUID: 5019, Field: "metadata", Rule: "required", Reason: "required field is missing"}
	}
	if len(e.Osint) == 0 {
		return &ocsf.ValidationError{ClassUID: 5019, Field: "osint", Rule: "required", Reason: "required field is missing"}
	}
	return nil
}

func init() {
	ocsf.RegisterClass(5019, func() ocsf.Event { return &DeviceConfigStateChange{} })
}
